### ISSUE TITLE
praise(gg): keep up the good work.

### ISSUE THREAD

**Issue by 4thabang** [ulixee/secret-agent#101]
Hi,

This isn't an issue, feature request, or bug fix. I know that maintaining an open-source project can be daunting and challenging. Especially, without a lot of external validation or users willing to submit praise or feedback.

I am just saying thank you for your continued efforts in making scraping/automation an amazing experience!

I've not had a chance to use secret-agent yet but I am going to be using it in my next project.

Hopefully, this isn't spamming the issues feed. If it is, feel free to close/remove this issue but don't stop the good work.

All the best.

**Comment by calebjclark** [comment]
@4thabang thanks for the encouragement!
