### ISSUE TITLE
How can i pass extra args to the chromium?

### ISSUE THREAD

**Issue by Nisthar** [ulixee/secret-agent#102]
How can i pass args like `devtools: false` to the underlying chromium?

**Comment by blakebyrnes** [comment]
@Nisthar I don't think we currently have that capability. We've tried to cover most of the use cases we could think of in other places. For instance, everything related to controlling browser "emulation" - timezone, screensize, language, etc is configurable via the default settings and emulators. 

Replay is intended to show you the full scope of a session where devtools does not impact what's visible during a scraping session.

Are you seeing detection and/or behavior that you're trying to turn off, or just trying to understand the lay of the land?

**Comment by Nisthar** [comment]
@blakebyrnes It currently opens the devtools when its initialized and some of my websites have debugger statements so it automatically stop at the breakpoints. it works fine if i don't open the devtools in a normal browser.

**Comment by blakebyrnes** [comment]
Are you using the SHOW_BROWSER flag to show chrome? Or do we have a bug where we're somehow opening devtools in headless?

**Comment by Nisthar** [comment]
@blakebyrnes I am using the SHOW_BROWSER to run the browser headful. I think i can disable to run it without devtools. But this would be a nice feature to add to secret-agent.

**Comment by blakebyrnes** [comment]
@Nisthar are you using Replay too? Or did you turn that off? Would love to understand your dev process a bit more. We're ultimately planning to provide a "live" capability in Replay, but it's obviously not there yet.

Thanks for the feedback! Will think about how we can implement the ability to turn that off when showing browser in the interim!

**Comment by Nisthar** [comment]
@blakebyrnes I think i am not using replay. Atleast i don't see the replay interface opening with the browser. I am using the `SA_REPLAY_SKIP_BINARY_DOWNLOAD=true` variable.
