### ISSUE TITLE
AwaitedDOM - docs ?

### ISSUE THREAD

**Issue by jig-u** [ulixee/secret-agent#105]
Hello, how to use AwaitedDOM as specified element?

agent.document.querySelector("canvas") => returns ISuperElement

I want to call toDataURL() of HTMLCanvasElement but how would I do it ?

**Comment by calebjclark** [comment]
@jig-u the AwaitedDOM is used exactly the same as the regular DOM except that you use await to call the method or retrieve the property value.

So to call toDataURL() you would do this:

```js
const dataUrl = await agent.document.querySelector("canvas").toDataURL();
```

HOWEVER, SecretAgent is still in alpha and some of the DOM properties and methods are not yet implemented in AwaitedDOM, toDataURL() being one of them. You can use the docs to check which have been implemented: https://secretagent.dev/docs/awaited-dom/html-canvas-element.

@blakebyrnes is going to include this toDataURL method in the next release.
