### ISSUE TITLE
Fails creepjs tests

### ISSUE THREAD

**Issue by felyxjet** [ulixee/secret-agent#108]
[creepjs](https://abrahamjuliot.github.io/creepjs/) is able to detect secret-agent's lies.

**Comment by blakebyrnes** [comment]
@felyxjet Nice profile picture ;) 

Thanks for the report. Looks like a lot of great tests in creepjs that we haven't gotten to in our Double Agent testing quite yet. In particular, we're failing a lot of tests that originate in Service Workers. Will make that a priority in our upcoming additions.

**Comment by felyxjet** [comment]
Nice, looking forward to it. 

P.S. it's not a surprise i like your profile picture as well ))
