### ISSUE TITLE
How to reload tab?

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#112]
What is the equivalent to puppeteer's page.reload? Can't find specific method, should it be performed as `agent.document.location.reload()`?

Seems like such sites as brandshop.ru (with Variti bot protection) can detect this. First load is successful, but such reload does not go through...

**Comment by blakebyrnes** [comment]
We don't have a high level method for this yet. I tried out `agent.document.location.reload()` too and it returned quickly, but it seemed to cause issues in Secret Agent recording (and thus replay). I'll try and dig in to see what's happening underneath.

We will likely simplify this api and probably add an "out-of-dom" option. Are you using it (vs simply a goto) to trigger a specific thing to happen on the page?

**Comment by dmzebrov** [comment]
I just used to use it in puppeteer, that's why I'm asking. But to clarify, on the basic level, are there any core differences between going to the url and reloading current url?

**Comment by blakebyrnes** [comment]
There actually are some underlying differences in several of the browsers now in terms of which headers get sent, and whether it's treated as a "user-action", which then dictates if cookies can be set from third parties, and what origin/referrer headers are sent. So it _is_ slightly different. I would guess you'd see similar behavior in most cases in the interim.

I do agree it feels more intuitive to use a reload than to goto the same url again.
