### ISSUE TITLE
How to block certain types of HTTP Requests from loading?

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#113]
I want to block HTTP Requests that doesn't affect scrapping process like images, styles, etc. How can I do it? Does it increases the chances of detection of Secret Agent?

**Comment by blakebyrnes** [comment]
We do have an option to reduce the loading of assets for Secret Agent. They're called "Rendering options". You can see more about them here: https://secretagent.dev/docs/overview/configuration#rendering

We currently don't have a way to customize further (like by specific url).

@calebjclark will weigh in about increased chances - but for sure, if a site is tracking how often you're only loading certain types of assets, you could fall into a bucket they're tracking. It's going to be very dependent on the end-site though. Your mileage may vary!

**Comment by dmzebrov** [comment]
Thank you for answer! This is definitely something I was looking for. I have read docs (not so thoroughly though), but have missed it. Maybe naming is a little confusing. I may be wrong, but, logically, rendering is happening after resource load and "renderingOptions" parameter prevents resource not only from rendering, but from loading too.

**Comment by blakebyrnes** [comment]
You make a good point. Will brainstorm if we can find a better name

**Comment by calebjclark** [comment]
@blakebyrnes we don't have any stats on increased chance of being blocked if asset loading is disabled... hopefully Mission Impossible will give us a better understanding ;)
