### ISSUE TITLE
Invalid cookie fields

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#142]
Got this error, when I tried to set cookies using setItem method (agent.activeTab.cookieStorage.setItem('test', 'test')):

clientError: 'Error: Storage.setCookies: Invalid cookie fields'

Used simple example code from docs. MacOS.

**Comment by blakebyrnes** [comment]
Hi @dmzebrov,
I can reproduce. It appears that if you don't provide any options, the api fails - which should obviously be fixed :). It works if you do the following: `agent.activeTab.cookieStorage.setItem('test', 'test', {})` 

I'll get a fix into 1.3. Still wrapping up a few more things for that release.

**Comment by dmzebrov** [comment]
Sorry, but it doesn't help...

**Comment by blakebyrnes** [comment]
What version are you running? Let me see if I'm getting the same thing on an older version.

**Comment by dmzebrov** [comment]
alpha 5

**Comment by dmzebrov** [comment]
I mean v1.2.0-alpha.5

**Comment by blakebyrnes** [comment]
Is it possible to share your session database? I'm not actually able to reproduce this using a simple example. This seems to be working fine.

```js
const SecretAgent = require('secret-agent');

(async () => {
    const agent = await new SecretAgent();

    await agent.goto(`https://dataliberationfoundation.org`);
    await agent.activeTab.cookieStorage.setItem('test', 'test');

    const cookie = await agent.activeTab.cookieStorage.getItem('test');
    console.log(cookie);
    await agent.close();
})();

```

**Comment by dmzebrov** [comment]
I see... I am adding cookie before agent.goto... But how I can add cookies before goto? I need cookies to access some part of the site.

**Comment by blakebyrnes** [comment]
Would the UserProfile feature work for you? https://secretagent.dev/docs/advanced/user-profile.

You could save a copy of the cookies/storage after a previous load of the page and then change it as you need to (that's the simplest approach). You could also just create one from scratch.

**Comment by dmzebrov** [comment]
I'll try it tomorrow and give a feedback. Thank you for your immediate assistance!
