### ISSUE TITLE
Some broken relative links in docs

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#151]
Nothing urgent, but fyi there are some broken links in the docs. Example:

[https://secretagent.dev/docs/basic-interfaces/agent/#configure](url)

The 3 links in this quote from that page are slightly wrong:

> See the Configuration page for more details on options and its defaults. You may also want to explore BrowserEmulators and HumanEmulators.

**Comment by blakebyrnes** [comment]
Thanks! Got them fixed up
