### ISSUE TITLE
Some unexpected errors from repetitively goto'ing same URL

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#153]
While testing with a simple loop that repetitively requests the same URL, I've run into a some different unexpected error situations.

In one case, requesting https://www.whatismyip.com/ led to some uncaught DNS-related errors. Sample code & results txt:

```
process.env.SA_SHOW_REPLAY="false";
const { Agent } = require('secret-agent');

async function run() {
  var agent = await new Agent();
  let url = 'https://www.whatismyip.com/';
  for (let i = 0; i < 10; i++) {
    try {
      console.log('here 1');
      let resource = await agent.goto(url, 5000);
      console.log('here 2');
      let statusCode = await resource.response.statusCode;
      console.log(`here 3: ${statusCode}`);
    } catch (err) {
      console.log(`Caught an exception: ${err}`);
    }
  }
  await agent.close();
}
run();
```

Results:
[Results1.txt](https://github.com/ulixee/secret-agent/files/5938243/Results1.txt)

I'm not clear where the reference to ipv6.whatismyip.com came from, does that site sometimes redirect to that as an anti-bot technique? Also not clear if this is the expected behavior from secret-agent for a DNS lookup error, in terms of the unhandled errors?

In a 2nd case, repeatedly requesting https://www.slashdot.org/ using the same loop code, led to:

Results:
[Results2.txt](https://github.com/ulixee/secret-agent/files/5938246/Results2.txt)

Not clear what caused that or if it is important.

Lastly, repeatedly requesting http://www.posthuman.com/ leads to the requests timing out after the 1st success. I've tried removing my 5 sec timeout and then the normal 30 sec timeout eventually occurs. This site is a basic web hosting site on 1and1/Ionos shared hosting. They advertise as providing anti-DDOS protection, could this behavior be some anti-bot detection system, or is it something else? The behavior is perfectly repeatable, always after starting the program it gets 1 working 200 status response, then everything times out after that.

Results:
[Results3.txt](https://github.com/ulixee/secret-agent/files/5938247/Results3.txt)

Results without me catching the error:
[Results4.txt](https://github.com/ulixee/secret-agent/files/5939359/Results4.txt)

**Comment by blakebyrnes** [comment]
@A-Posthuman thanks for reporting! 

It looks like the errors in whatsmip.com are because we don't support ipv6 yet. On the actual page, that site is just trying to show you what your ip is on ipv4 and ipv6. Their ipv6 address doesn't have an ipv4 ip (which is rare on the web), and since we can't find an address, it's unable to load. Depending on your use case, this is likely just ignorable. That said, we should be catching it, so I'll look into that part.

Slashdot: I'm unsure if these errors are impacting loading your pages, but it shouldn't be exploding if the socket is undefined. I see a spot that should be fixed for this one.

I'm seeing the same with Posthuman, but it looks like something is just hanging internally. I'm looking deeper into this one.

**Comment by blakebyrnes** [comment]
@A-Posthuman fyi, we weren't properly handling cached loads for repeatedly loading posthuman. Will be fixed in the next release.

**Comment by A-Posthuman** [comment]
Cool, y'all are the best! BTW I had posted on the discord asking is there a build howto or recipe on how to build the current github codebase if I ever want to clone it, like for example if I want to make a local build to test out some of the latest code before you publish a new official build version?

**Comment by A-Posthuman** [comment]
Testing using 1.3.0 alpha 2, seeing a different issue with trying to get statusCode of the 2nd request to www.posthuman.com:

[debug.txt](https://github.com/ulixee/secret-agent/files/5955350/debug.txt)

Testing https://www.whatismyip.com/ the DNS/IPv6 issue is fixed, however seeing an occasional issue:

> UnhandledPromiseRejectionWarning: Error: Failed to load url

On successive random runs of my program, perhaps 10% of them fail with this. When this happens all my .goto attempts immediately all fail instantly if I try/catch. If I stop and wait a little while and rerun my program then it tends to work ok again for a bit. Sorry I don't have a reliable way to replicate this other than repeatedly running my program several times.

[debug.txt](https://github.com/ulixee/secret-agent/files/5955430/debug.txt)

**Comment by blakebyrnes** [comment]
Would you mind grabbing the session database from the logs? e141c6d0-6b42-11eb-b12b-f16875b05b03.db. Thanks!

**Comment by A-Posthuman** [comment]
Sure, here it is:

[e141c6d0-6b42-11eb-b12b-f16875b05b03.zip](https://github.com/ulixee/secret-agent/files/5963160/e141c6d0-6b42-11eb-b12b-f16875b05b03.zip)

**Comment by A-Posthuman** [comment]
I dumped that session above, may be related to hitting a hCaptcha, but that's as far as I could figure out.

Regarding the other issue with the 2nd requests to posthuman.com not getting a statusCode, do you need the session db for that one? I've attached that one too if you do:

[13f22f50-6b40-11eb-9a69-c9d190609444.zip](https://github.com/ulixee/secret-agent/files/5963321/13f22f50-6b40-11eb-9a69-c9d190609444.zip)

**Comment by blakebyrnes** [comment]
For the e141c6d0-6b42-11eb-b12b-f16875b05b03.zip one, it looks like you're getting sent to a CloudFlare "whatsmyip" site. This site seems to have max-requests allowed per IP.

![image](https://user-images.githubusercontent.com/115056/107668456-b38cb200-6c5e-11eb-8966-ed17b47e8aa7.png)

**Comment by blakebyrnes** [comment]
The second request to Posthuman (BTW, is this your site?) is using cache, so doesn't have a response. I'll tweak the response so that it always returns an object, and adds a parameter for responses loaded from cache

**Comment by A-Posthuman** [comment]
Thanks for the additonal cache fix. On the e141c6d0-6b42-11eb-b12b-f16875b05b03 / whatismyip issue, I'm not clear on if the behavior being returned from the redirect to the captcha is expected, or a bug?

As a user, I would expect the tab should redirect/navigate to whatever page it ends up being sent to, and then if it successfully loads a captcha screen, I should get back access to that content body and a statusCode, etc. I'm not clear on why if it is a captcha then instead I get returned a an unhandled "UnhandledPromiseRejectionWarning: Error: Failed to load url" ?

**Comment by blakebyrnes** [comment]
You're absolutely correct. I was assuming this was coming from the browser, but I see we're actually looking for errors >=400 and sending back a navigation error. I think it makes much more sense to return the status code you landed on as a successful "load" even if you landed on a 404 or 403 (as in this case).

**Comment by A-Posthuman** [comment]
Following up, when testing the cache issue with posthuman.com, on the 2nd and subsequent requests, instead of getting a 200 statusCode back, I'm getting "undefined".

**Comment by blakebyrnes** [comment]
Yeah, there’s no http request since it’s an in memory cache. There’s a field though that indicates if it has been cached. Do you think it would be preferable to return a special code like a negative status code?
