### ISSUE TITLE
Possible function argument error in Handler Step 2 example, and runtime TypeError

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#154]
While experimenting with the Handler Step 2 example in the new blog post, I think maybe the line:

`handler.dispatchAgent(getDatasetCost, link, agentOptions);`

should be:

`handler.dispatchAgent(getDatasetCost, dataset, agentOptions);`

Also, after adjusting that, my slightly modified test code is producing a TypeError:

```
process.env.SA_SHOW_REPLAY="false";
const { Handler } = require('secret-agent');

var handler = new Handler({ maxConcurrency: 1 });

async function run() {
    handler.dispatchAgent(async agent => {
        // agent is automatically created for us
        await agent.goto('https://ulixee.org');
        const datasetLinks = await agent.document.querySelectorAll('a.DatasetSummary');
        for (const link of datasetLinks) {
            const name = await link.querySelector('.title').textContent;
            const href = await link.getAttribute('href');
            const dataset = { name, href };
            // add a name to each agent so we can find each scrape on Replay
            const agentOptions = { name };
            handler.dispatchAgent(getDatasetCost, dataset, agentOptions);
        }
    });
    // only 1 agent will be active at a given time
    await handler.waitForAllDispatches();
    await handler.close();
}

// my data gets passed in once an agent is available
async function getDatasetCost(agent, dataset) {
    const { name, href } = dataset;
    if (!href.startsWith('http')) href = `https://ulixee.org${href}`;
    console.log(href);
    await agent.goto(href);
    await agent.waitForAllContentLoaded();
    const cost = await agent.document.querySelector('.cost .large-text').textContent;
    console.log('Cost of %s is %s', dataset.name, cost);
  }

run();
```

> $ node SecretAgentTest4.js
> 2021-02-07T05:17:24.873Z ERROR [/home/ubuntu/node_modules/@secret-agent/core/server/ConnectionToClient] Client.UnhandledErrorOrRejection {
>   clientError: 'TypeError: Assignment to constant variable.',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> } TypeError: Assignment to constant variable.
>     at Object.revive (/home/ubuntu/node_modules/typeson-registry/types/errors.js:23:39)
>     at executeReviver (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:12346)
>     at reducer (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13874)
>     at Array.reduce (<anonymous>)
>     at _revive (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13772)
>     at /home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13293
>     at Array.forEach (<anonymous>)
>     at _revive (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13266)
>     at /home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13293
>     at Array.forEach (<anonymous>)

Seems to hang after that point.

Also BTW, I replied to closed Issue #146 with an update to the import issue

**Comment by A-Posthuman** [comment]
After further investigation I tracked down 2 other what look like bugs in that Handler Step 2 example:

```
if (!href.startsWith('http')) href = `https://ulixee.org${href}`;
```

This seems to be incorrectly trying to reassign a const. I changed href to a let type variable, which fixed it:

`let { name, href } = dataset;`

Then this function was removed in 1.3.0, so no longer works:

`await agent.waitForAllContentLoaded();`

I replaced it with this:

`await agent.waitForPaintingStable( { timeoutMs: 5000 } );`

However with maxConcurrency of 2, this leads to an error:

> https://ulixee.org/datasets/news/0/headlines/news-ycombinator-com
> 2021-02-08T04:33:12.231Z ERROR [/home/ubuntu/node_modules/@secret-agent/core/ser
> ver/ConnectionToClient] Client.UnhandledErrorOrRejection {
>   clientError: 'Error: Timeout waiting for promise',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> } Error: Timeout waiting for promise
>     at Object.revive (/home/ubuntu/node_modules/typeson-registry/types/error.js:10:23)
>     at executeReviver (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:12346)
>     at reducer (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13874)
>     at Array.reduce (<anonymous>)
>     at _revive (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13772)
>     at /home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13293
>     at Array.forEach (<anonymous>)
>     at _revive (/home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13266)
>     at /home/ubuntu/node_modules/typeson/dist/typeson-commonjs2.min.js:1:13293
>     at Array.forEach (<anonymous>)

Followed then by a few more console prints, and then a neverending hang:

> https://ulixee.org/datasets/code/0/coder/github-com
> https://ulixee.org/datasets/restaurants/0/availability/opentable-com
> https://ulixee.org/datasets/products/0/sku-sellers/amazon-com
> (hangs)

So I tried changing the line to this:

`await agent.activeTab.waitForLoad('PaintingStable', { timeoutMs: 5000 } );`

with same results. So then I tried this, which seems to work:

`await agent.activeTab.waitForLoad('DomContentLoaded', { timeoutMs: 5000 } );`

Perhaps the PaintingStable new stuff isn't quite reliable yet? Not sure

**Comment by blakebyrnes** [comment]
@A-Posthuman Thanks for looking deep into this one. Definitely some typos and apis I didn't properly update in that post. I've had waitForPaintingStable working pretty reliably, but I'm on a mac with a screen. I don't know if that makes a difference. Let me try some things out and I'll get back.

**Comment by A-Posthuman** [comment]
Also a side question, probably not directly related to your project, but do you know how in node I can get it to output the line number from my source code that generated the eventual error? Like in the case above it is reporting a "Assignment to constant variable", but listing it as coming from secret-agent/core/server/ConnectionToClient, which left me guessing for a while as to where in my code that assignment problem was actually at. I'm sure there must be a command line option or something on node to help debug that easier?

**Comment by blakebyrnes** [comment]
Your log traces are really weird for these last couple bugs. I have it on my list to investigate on Ubuntu. We do some work to help connect client and core stack traces, so we actually try to give you "more" info than usual. Will poke around.

**Comment by A-Posthuman** [comment]
Thanks, the updated stack traces are definitely more helpful now.  As for the agent.waitForPaintingStable issue I reported above, that also seems to be behaving better now, not sure if you updated that in 1.3.0 alpha 2.
