### ISSUE TITLE
Possible typo, undocumented method in Handler docs

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#156]
In the 2nd code block on the [Handler docs page](https://secretagent.dev/docs/basic-interfaces/handler), the line:

`await remote.connect();`

should that be remote1 ? Also I couldn't find documentation on that connect() method from RemoteConnectionToCore. Although it looks straightforward as to what it does, is the primary use case for it going to be if you want to try/test making a remote connection as a separate step rather than all at once in a new Hander constructor?

**Comment by blakebyrnes** [comment]
Thanks! Updated the docs
