### ISSUE TITLE
Console logger seems to ignore process.env.NODE_DISABLE_COLORS = 1

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#158]
I was attempting to remove the color codes when dumping some error and debug outputs to text file, but the process.env.NODE_DISABLE_COLORS = 1 option I googled doesn't seem to do the trick. Would it be possible to update your console logger to look for this?

**Comment by A-Posthuman** [comment]
Also added a couple of potential issues onto closed Issue #153

**Comment by blakebyrnes** [comment]
I'm not sure where those would be coming from. If you look in commons/Logger.ts - that's where the logging is happening. There's nothing else being applied to the logs. Perhaps something in the terminal program you're using?

For what it's worth, all logs are in the Session database for each run in SessionLogs (it's a sqlite3 file). You don't need to run DEBUG=true to get those to be captured. It might be what you're looking for...

Thanks for all the issue reports!

**Comment by A-Posthuman** [comment]
I'm not sure, but do the Sessions also capture all the stack traces from errors that halt the program?

I believe the coloring of some of the error messages may come from within Node itself, for example using this simple program to generate an error:

```
// process.env.NODE_DISABLE_COLORS = 1;
const test = "test";
test = "error";
```

Results in my PuTTY getting colored text (some of it grey) like this:

![Untitled](https://user-images.githubusercontent.com/78522671/107601061-34aa6180-6beb-11eb-809b-69d2da2ce60c.png)

If I want to redirect the program outputs to a log file or something to look at later, it ends up having a lot of ugly ANSI color codes in it unless I pipe it all through a sed command to strip those.

So if I uncomment that process.env.NODE_DISABLE_COLORS line, then in that program it does revert to not using colors:

![Untitled](https://user-images.githubusercontent.com/78522671/107601174-8ce16380-6beb-11eb-95c9-470705d820b1.png)

However when I try to use that same line to disable colored output in secret-agent, I still get colored output like this:

![Untitled](https://user-images.githubusercontent.com/78522671/107601260-cca84b00-6beb-11eb-8eb2-7e7bcda918fc.png)

So somehow my ENV variable is being ignored or overridden somewhere?

**Comment by blakebyrnes** [comment]
Oh, I see where we are actually using colors. I'll put a check for the disable colors in here.
