### ISSUE TITLE
Core export problem, possible issue with ECONNREFUSED

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#159]
While experimenting with the "server" part of the Remote docs, running into the issue that Core is requiring adding .default to the require line. Also in that example the log.info lines had to be swapped to console.log.

After then getting the code ready to test on client/server, accidentally tried to first start the "server", which then immediately failed to be able to connect to client, leading to endless huge stream of:

> 2021-02-10T04:52:52.267Z ERROR [/home/ubuntu/node_modules/@secret-agent/client/lib/Handler] UnhandledRejection {
>   error: 'Error: connect ECONNREFUSED

I found I can catch this error by wrapping my agent.goto with try/catch, but wasn't sure if this is the desired way to go. I guess the cleaner way to go would be to use RemoteConnectionToCore and the .connect() method to verify I have an ok connection first. So I've modified my program to try that with some code like this:

```
process.env.SA_SHOW_REPLAY="false";
const { Handler, RemoteConnectionToCore } = require('secret-agent');
async function run() {
    try {
        var remote1 = new RemoteConnectionToCore({ maxConcurrency: 2, host: '172.31.30.34:2600' });
        await remote1.connect();
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up RemoteConnectionToCore, exiting.');
        process.exit();
    }
    
    try {
        var handler = new Handler({ remote1 });
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up Handler, exiting.');
        process.exit();
    }

    handler.dispatchAgent(async agent => {
        // agent is automatically created for us
        try {
            await agent.goto('https://ulixee.org');
        } catch (err) {
            console.log(`Caught an exception: ${err}`);
            console.log('Problem with agent.goto, exiting.');
            process.exit();
        }

more stuff...

}
run();
```

However I'm catching an error where I try to do the first goto with the new Handler:

> 2021-02-10T05:34:20.975Z ERROR [/home/ubuntu/node_modules/@secret-agent/client/c
> onnections/ConnectionFactory] Error connecting to core {
>   error: 'TypeError: Converting circular structure to JSON\n' +
>     "    --> starting at object with constructor 'RemoteConnectionToCore'\n" +
>     "    |     property 'commandQueue' -> object with constructor 'CoreCommandQu
> eue'\n" +
>     "    --- property 'connection' closes the circle",
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> } TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'RemoteConnectionToCore'
>     |     property 'commandQueue' -> object with constructor 'CoreCommandQueue'
>     --- property 'connection' closes the circle
>     at JSON.stringify (<anonymous>)
>     at /home/ubuntu/node_modules/core/lib/CoreProcess.ts:15:38
>     at new Promise (<anonymous>)
>     at Function.spawn (/home/ubuntu/node_modules/core/lib/CoreProcess.ts:14:30)
>     at Function.client_1.ConnectionFactory.createLocalConnection (/home/ubuntu/full-client/index.ts:16:28)
>     at Function.createConnection (/home/ubuntu/node_modules/client/connections/ConnectionFactory.ts:30:25)
>     at new Handler (/home/ubuntu/node_modules/client/lib/Handler.ts:23:44)
>     at run (/home/ubuntu/SecretAgentTest5-server.js:50:23)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Caught an exception: TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'RemoteConnectionToCore'
>     |     property 'commandQueue' -> object with constructor 'CoreCommandQueue'
>     --- property 'connection' closes the circle
> Problem with agent.goto, exiting.
>

**Comment by A-Posthuman** [comment]
Following up, I then went ahead and went back to not trying to use RemoteConnectionToCore, and instead made sure I had my "server" code running on the server (I have my test programs named as the opposite client/server, ignore that):

```
process.env.SA_SHOW_REPLAY="false";
process.env.NODE_DISABLE_COLORS = 1;

// const { Core } = require('@secret-agent/core');
const Core = require('@secret-agent/core').default;

(async () => {
  Core.onShutdown = () => {
    console.log('Exiting Core Process');
    process.exit();
  };
  console.log('Starting Core Process');
  await Core.start({ port: 2600 });
})();
```

> ubuntu@ip-172-31-30-34:~$ node SecretAgentTest5-client.js
> Starting Core Process

And I have my EC2 security policy firewall rules configured on each of the two EC2 instances to allow incoming connections from each other and outgoing connections to everywhere. I can ping the "server" from the "client".

But still getting the ECONNREFUSED error:


> ubuntu@ip-172-31-29-135:~$ node SecretAgentTest5-server.js
> About to waitForAllDispatches
> 2021-02-10T05:41:00.810Z ERROR [/home/ubuntu/node_modules/@secret-agent/client/c
> onnections/ConnectionFactory] Error connecting to core {
>   error: 'Error: connect ECONNREFUSED 172.31.30.34:2600',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> } Error: connect ECONNREFUSED 172.31.30.34:2600
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
>   errno: -111,
>   code: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '172.31.30.34',
>   port: 2600
> }
> Caught an exception: Error: connect ECONNREFUSED 172.31.30.34:2600
> Problem with agent.goto, exiting.
> ubuntu@ip-172-31-29-135:~$ ping 172.31.30.34
> PING 172.31.30.34 (172.31.30.34) 56(84) bytes of data.
> 64 bytes from 172.31.30.34: icmp_seq=1 ttl=64 time=0.319 ms
> 64 bytes from 172.31.30.34: icmp_seq=2 ttl=64 time=0.429 ms

**Comment by blakebyrnes** [comment]
Hi @A-Posthuman, looks like these might be bad documentation problems... sorry! For your snippet, you need to be passing in your connection as a top level param to the Handler constructor:
```
const { Handler, RemoteConnectionToCore } = require('secret-agent');
async function run() {
    try {
        var remote1 = new RemoteConnectionToCore({ maxConcurrency: 2, host: '172.31.30.34:2600' });
        await remote1.connect();
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up RemoteConnectionToCore, exiting.');
        process.exit();
    }
    
    try {
        var handler = new Handler(remote1); **// change to be passed in, not as an object**
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up Handler, exiting.');
        process.exit();
    }

    handler.dispatchAgent(async agent => {
        // agent is automatically created for us
        try {
            await agent.goto('https://ulixee.org');
        } catch (err) {
            console.log(`Caught an exception: ${err}`);
            console.log('Problem with agent.goto, exiting.');
            process.exit();
        }
```

When you're starting core, the docs were wrong (I thought I updated this, but apparently not). The port parameter is `coreServerPort`

```
(async () => {
  Core.onShutdown = () => {
    console.log('Exiting Core Process');
    process.exit();
  };
  console.log('Starting Core Process');
  await Core.start({ coreServerPort: 2600 }); /// changed param here
})();
```

**Comment by A-Posthuman** [comment]
Got it, thx. client/server now working! Yeah passing in that connection as a new object was my bad, misread the docs.

On the Core require line needing to add .default, is that correct or will it be adjusted like you did with some of the other exports?

`const Core = require('@secret-agent/core').default;`

**Comment by blakebyrnes** [comment]
Glad that worked! I need to do some more work to get the core exports working smoothly with regular node export.
