### ISSUE TITLE
AwaitedDOM Docs: Add method args and return types

### ISSUE THREAD

**Issue by calebjclark** [ulixee/secret-agent#16]
At the moment all documented methods in AwaitedDOM show a generic `...args` and a return type of null. This should be fixed to show their true value.

**Comment by blakebyrnes** [comment]
Looking into this task. Seems there are 2 (or maybe 3) parts.
1) Add args and return types to awaited dom
2) Add descriptions from MDN to the args (this requires another level of parsing MDN)
--
3) Semi-related: confirm that docs are in sync with SecretAgent client api

I'm thinking that we might solve 1/3 by traversing AwaitedDom and SecretAgent client library Typescript files using [typedoc](https://github.com/TypeStrong/typedoc). Any thoughts/ideas/better tools?

**Comment by calebjclark** [comment]
@blakebyrnes should this conversation be moved to the AwaitedDOM repo?

Using typedoc feels hacky, especially since we already have the args and return types... and we're using it to create the typescript.

Yes, extracting directly from Noderdom requires _some level of intelligence in figuring out when Supers were used_, but Noderdom already has that intelligence.

**Comment by blakebyrnes** [comment]
The main reason I started the convo here is if we want to knock out point 3) above, it seems like it's reasonable to try to ensure that the generator look at the actual declaration files and typescript files to see what should be on the website.
