### ISSUE TITLE
Is there a way for an agent to determine what remote Handler host it's on?

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#163]
Is there a way via agent.meta or other means for my code to figure out which remote host connection/IP address it's getting a particular result from? There may be some cases I'm imagining where if I'm farming out Handler requests to several different hosts, and one host starts having a problem (say for example its IP address gets blocked from a site I'm scraping), I need to be able to tell which host has the issue, then somehow remove it from the connections the Handler is farming stuff to (I guess I'd have to end the Handler and make a new one?).

**Comment by blakebyrnes** [comment]
I don't think we do have that at the moment, but this does make sense. @calebjclark should we call this property "coreHost" on Agent? Is there any reason you can think of we'd want to expose the whole connection object?

**Comment by A-Posthuman** [comment]
I could see it might be useful if my Handler control code could be able to not only know which IP address/connection is causing a problem, but also be able to dynamically disconnect it from the Handler pool and have no more dispatches sent to the disconnected connection (and any that were internally queued or in progress with that connection be shifted to other connections... not sure how your internal queuing works). Does the ConnectionToCore disconnect() method do something like that?

**Comment by blakebyrnes** [comment]
Good feedback and thought. So perhaps it makes more sense to expose coreConnection.

**Comment by calebjclark** [comment]
@A-Posthuman are you planning to setup/connect to multiple hosts/Cores? I'm curious why, but I also imagine this architecture will impact how we should expose connection capabilities.

Are you thinking each host/Core will be using a single IP address? Have you looked at using a single Core with rotating proxies?

**Comment by A-Posthuman** [comment]
I'm conducting experiments at the moment yes with each remote host having a single IP, and then instituting some type of monitoring of the results each host gets back, and if a host starts to get too much throttling/blockage then terminate that host and setup a fresh one to take its place with new IP.

Not sure if this is the architecture I'll end up using, but if I do it would be on the order of 20 to 100 remote hosts in the production system depending on what throughput I can achieve per host per hour and other factors.

Also not sure yet what are the inherent limits of your Handler dispatcher, in terms of how many remote hosts and queued work/dispatches it can handle in a given server size before hitting mem or cpu limits. I'll have to run some tests to see how far it can scale up.

I totally realize this is still an alpha or early beta quality level project, and I don't want to push you to spend a lot of effort on feature creep if you feel this is getting beyond the core goals of your project. But if you can see a relatively simple way to expose some meta attribute or other way for my code to be able to get some feedback as to when a particular remote host is going awry, then that should also be useful to other folks I guess? Not everyone is going to want to rely on proxies.

**Comment by blakebyrnes** [comment]
Your use case makes total sense. We'll definitely add some form of getting to the connection that's internal. 

I think @calebjclark is thinking about a common case where you see that an IP is suddenly being blocked, and you want to rotate that IP. The host machine's IP is usually a datacenter IP, and there are some bot detectors that do work to identify what "kind" of IP you are, and of course, what volume they've seen from a given IP. So the normal strategy is to proxy/vpn your requests so you can swap out that IP when it gets put into blacklists or throttle-lists.

Per your earlier question, disconnect does terminate all your current sessions from the remote server, but it doesn't have a mechanism to "re-queue" existing dispatched agents, so you'd need to do that yourself upon detecting this error state.

**Comment by A-Posthuman** [comment]
Right, yes I may end up going the more traditional proxy route, but experimenting with this other approach first.

Regarding the disconnect, for the dispatches already in progress to a disconnecting connection, in that case does my user function I setup in dispatchAgent() then get a chance to catch an error from its disconnected agent session as soon as it tries to do something with the disconnected agent?

**Comment by blakebyrnes** [comment]
We're going to add functions to add and remove connections to core in a handler, each agent will expose it's coreHost. 

If a connection disconnects, the agents using it would be interrupted and would throw errors. For now, I think you'd want to catch those and re-queue those agents however you need to (likely just re-queue the data, but it would be dependent on your use case).

**Comment by blakebyrnes** [comment]
NOTE: we'll make sure there's a specific type of error/code for when an agent is disconnected.

**Comment by A-Posthuman** [comment]
Sounds good, thx!
