### ISSUE TITLE
Run example code

### ISSUE THREAD

**Issue by MrPerry300** [ulixee/secret-agent#179]
Hi, I installed secret-agent with npm and I wanted to run the example code to test but when I do node index.js I get an error

** CODE **
```javascript
const agent = require('secret-agent');

(async () => {
    await agent.goto('https://example.org');
    const title = await agent.document.title;
    const intro = await agent.document.querySelector('p').textContent;
    await agent.close();
})();
```
** ERROR **
**Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/CoreProcess' is not defined by "exports" in /Users/haikelouerfelli/Desktop/secAgent/node_modules/@secret-agent/core/package.json**

**Comment by blakebyrnes** [comment]
Thanks for the report. We've had a few issues getting the Es module exports right. There are a few fixes not yet released as well. Could you tell us which version of nodejs, which operating system and which version of secret agent you're using?

Thanks!

**Comment by MrPerry300** [comment]
Np, i use Node v14.12.0
OS: mac OS BigSur v 11.1
Secret agent version ^1.3.1-alpha.1

I can't wait for you to release the update ;)

**Comment by MrPerry300** [comment]
I updated nodejs to version v15.11.0 and it works fine

**Comment by blakebyrnes** [comment]
FYI - It looks like wildcard support was added in node 14.13.0.... We're gonna have to re-think how we're exporting the modules.
