### ISSUE TITLE
Unable to get content of iframe

### ISSUE THREAD

**Issue by olvrschwrz** [ulixee/secret-agent#180]
Hi there,

I am using the Secret Agent for webscraping so I came across of a webpage with an iframe and so I am unable neither to get content of that iframe nor wait for an element to become visible. This only occurs if I wait until the iframe is loaded, prior to that I am able to get an empty body (`<body></body>`) when checking for the body's outerHTML.

For example when there is a captcha challenge, like here: [https://2captcha.com/demo/hcaptcha?difficulty=easy](https://2captcha.com/demo/hcaptcha?difficulty=easy)

I am using this snippet:

```
const { Agent } = require('secret-agent');

(async() => {
  const agent = await new Agent({
    viewport: {
      height: 800,
      width: 1280
    }
  });

  await agent.goto('https://2captcha.com/demo/hcaptcha?difficulty=easy');
  await agent.waitForPaintingStable();

  const { document } = agent;
  let iframe_document = document.querySelector('iframe').contentDocument;
  let content = await iframe_document.body.outerHTML;
  console.log(content);
  await agent.close();
})();
```

I always get `TypeError: Cannot read property 'body' of null`, even though the iframe is rendered properly in a screenshot. Node version 15.11.0

I appreciate any help.

**Comment by olvrschwrz** [comment]
Okay, seems to be because of this: https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame/25098153#25098153

**Comment by blakebyrnes** [comment]
Hi @olvrschwrz, thanks for the report. We haven't yet built support for cross-origin iframes. I have some ideas how we'll do it, but haven't quite gotten to it yet. Let me give some thought to how we can expose the internal iframes we're already tracking.
