### ISSUE TITLE
RemoteConnectionToCore.disconnect() results in loop/oom

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#187]
Testing my old code to see how the 1.4.0-alpha.1 handles RemoteConnectionToCore.disconnect()

This is the old code I'm using on one server to connect to the remote server:

```
// process.env.DEBUG = true;

// Set this ENV variable to make sure secret-agent knows this is a headless server, so don't try to start Replay
process.env.SA_SHOW_REPLAY="false";
process.env.NODE_DISABLE_COLORS = 1;

const { Handler, RemoteConnectionToCore } = require('secret-agent');

async function run() {
    try {
        var remote1 = new RemoteConnectionToCore({ maxConcurrency: 2, host: '3.133.97.97:2600' });
        await remote1.connect();
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up RemoteConnectionToCore, exiting.');
        process.exit();
    }
    
    try {
        // var handler = new Handler( remote1, { maxConcurrency: 1 } );
        var handler = new Handler( remote1 );
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up Handler, exiting.');
        process.exit();
    }

    handler.dispatchAgent(async agent => {
        // agent is automatically created for us
        try {
            await agent.goto('https://ulixee.org');
            const datasetLinks = await agent.document.querySelectorAll('a.DatasetSummary');
            for (const link of datasetLinks) {
                const name = await link.querySelector('.title').textContent;
                const href = await link.getAttribute('href');
                const dataset = { name, href };
                // add a name to each agent so we can find each scrape on Replay
                const agentOptions = { name };
                console.log(`name: ${name}, href: ${href}`);
                handler.dispatchAgent(getDatasetCost, dataset, agentOptions);
            }
        } catch (err) {
            console.log(`Caught an exception: ${err}`);
            console.log('Problem with dispatchAgent');
            process.exit();
        }
    });
    console.log('About to waitForAllDispatches');
    setTimeout( async function () {  
        console.log("setTimeout triggered");
        await remote1.disconnect();
        console.log("Done with disconnect");
    }, 4000);
    // try {
        await handler.waitForAllDispatches();
    // } catch (err) {
    //     console.log(`Caught an exception: ${err}`);
    //     console.log('Problem with waitForAllDispatches.');
    // } finally {
    //     console.log("2nd try at waitForAllDispatches");
    //     await handler.waitForAllDispatches();
    // }
    console.log('Done waiting');
    await handler.close();
}

// my data gets passed in once an agent is available
async function getDatasetCost(agent, dataset) {
    try {
    var { name, href } = dataset;
        // console.log(`here1: ${href}`);
        if (!href.startsWith('http')) href = `https://ulixee.org${href}`;
        console.log(href);
        await agent.goto(href);
        await agent.waitForPaintingStable( { timeoutMs: 5000 } );
        // await agent.activeTab.waitForPaintingStable( { timeoutMs: 5000 } );
        // await agent.activeTab.waitForLoad('PaintingStable', { timeoutMs: 5000 } );
        // await agent.activeTab.waitForLoad('DomContentLoaded');
        const cost = await agent.document.querySelector('.cost .large-text').textContent;
        console.log('Cost of %s is %s', dataset.name, cost);
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log(`Problem with getDatasetCost: ${name}, ${href}`);
        // process.exit();
    }
  }

run();
// run().catch(error => logger.error(error));

```

It uses a setTimeout after 4000 ms to trigger the disconnect.

The result is I get a huge amount of stack trace output that seems to go on endlessly, and the node process gets hung with near 100% cpu and using all available mem on the instance. Control-c doesn't work, have to kill -9 it.

I head and tail'd the debug output, here is the first 1000 lines of debug:

[debug2.txt](https://github.com/ulixee/secret-agent/files/6168052/debug2.txt)

here is the last 1000 lines:

[debug3.txt](https://github.com/ulixee/secret-agent/files/6168054/debug3.txt)

**Comment by blakebyrnes** [comment]
Well, that seems to not be working very well. I probably should have rigged up multiple machines. Will give that a go tomorrow

**Comment by A-Posthuman** [comment]
I still have these 2 instances up if you need any debug session data, but they are spot instances so could be evicted at any time. They are t2.micro instances on AWS running the standard Ubuntu 20.04 AMI (ami-08962a4068733a2b6).

**Comment by blakebyrnes** [comment]
Ok, I feel slightly better about myself... lol. This is an infinite loop if you don't catch errors from run. It's a case I didn't test (obviously). There's a loop failing to report the unhandled exception, and thus, throwing a new unhandled error... doh.

**Comment by A-Posthuman** [comment]
Testing the new 1.4.1-alpha.1, the disconnect() seems to be working better, however am seeing an issue I'm not sure is correct operation or not. When I trigger the disconnect() on a Handler that has both a local and remote connection in operation, it seems to be getting disconnected from both local & remote. Code below triggers a disconnect() after 2000 ms, but when I have the try/catch/finally uncommented it also seems to disconnect from the local agent too:

```
// process.env.DEBUG = true;

// Set this ENV variable to make sure secret-agent knows this is a headless server, so don't try to start Replay
process.env.SA_SHOW_REPLAY="false";
process.env.NODE_DISABLE_COLORS = 1;

const { Handler, RemoteConnectionToCore } = require('secret-agent');

async function run() {
    try {
        var remote1 = new RemoteConnectionToCore({ maxConcurrency: 1, host: '3.239.86.236:2600' });
        await remote1.connect();
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up RemoteConnectionToCore, exiting.');
        process.exit();
    }
    
    try {
        var handler = new Handler( remote1, { maxConcurrency: 1 } );
        // var handler = new Handler( remote1 );
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem setting up Handler, exiting.');
        process.exit();
    }

    handler.dispatchAgent(async agent => {
        // agent is automatically created for us
        try {
            await agent.goto('https://ulixee.org');
            const datasetLinks = await agent.document.querySelectorAll('a.DatasetSummary');
            for (const link of datasetLinks) {
                const name = await link.querySelector('.title').textContent;
                const href = await link.getAttribute('href');
                const dataset = { name, href };
                // add a name to each agent so we can find each scrape on Replay
                const agentOptions = { name };
                console.log(`name: ${name}, href: ${href}`);
                handler.dispatchAgent(getDatasetCost, dataset, agentOptions);
            }
        } catch (err) {
            console.log(`Caught an exception: ${err}`);
            console.log('Problem with dispatchAgent');
            process.exit();
        }
    });
    console.log('About to waitForAllDispatches');
    setTimeout( async function () {  
        console.log("setTimeout triggered");
        await remote1.disconnect();
        console.log("Done with disconnect");
    }, 2000);
    try {
        await handler.waitForAllDispatches();
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log('Problem with waitForAllDispatches.');
    } finally {
        console.log("2nd try at waitForAllDispatches");
        await handler.waitForAllDispatches();
    }
    console.log('Done waiting');
    await handler.close();
}

// my data gets passed in once an agent is available
async function getDatasetCost(agent, dataset) {
    try {
    var { name, href } = dataset;
        // console.log(`here1: ${href}`);
        if (!href.startsWith('http')) href = `https://ulixee.org${href}`;
        console.log(href);
        await agent.goto(href);
        await agent.waitForPaintingStable( { timeoutMs: 5000 } );
        // await agent.activeTab.waitForPaintingStable( { timeoutMs: 5000 } );
        // await agent.activeTab.waitForLoad('PaintingStable', { timeoutMs: 5000 } );
        // await agent.activeTab.waitForLoad('DomContentLoaded');
        const cost = await agent.document.querySelector('.cost .large-text').textContent;
        console.log('Cost of %s is %s', dataset.name, cost);
    } catch (err) {
        console.log(`Caught an exception: ${err}`);
        console.log(`Problem with getDatasetCost: ${name}, ${href}`);
        // process.exit();
    }
  }

run();
// run().catch(error => logger.error(error));
```

console output:

> About to waitForAllDispatches
> name: Wikipedia Entry, href: /datasets/encyclopedia/0/entry/wikipedia-com
> name: Resy Availability, href: /datasets/restaurants/0/availability/resy-com
> name: YcombinatorNews Headlines, href: /datasets/news/0/headlines/news-ycombinator-com
> name: Github Coder, href: /datasets/code/0/coder/github-com
> name: Opentable Availability, href: /datasets/restaurants/0/availability/opentable-com
> name: Amazon ASIN Seller Prices, href: /datasets/products/0/sku-sellers/amazon-com
> https://ulixee.org/datasets/encyclopedia/0/entry/wikipedia-com
> https://ulixee.org/datasets/restaurants/0/availability/resy-com
> setTimeout triggered
> Caught an exception: DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://3.239.86.236:2600)
> Problem with waitForAllDispatches.
> 2nd try at waitForAllDispatches
> Done waiting
> Caught an exception: DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://3.239.86.236:2600)
> Problem with getDatasetCost: Wikipedia Entry, https://ulixee.org/datasets/encyclopedia/0/entry/wikipedia-com
> Caught an exception: DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://localhost:45169)
> Problem with getDatasetCost: Resy Availability, https://ulixee.org/datasets/restaurants/0/availability/resy-com
> Done with disconnect

If I comment out the try/catch/finally part like this:

```
setTimeout( async function () {  
        console.log("setTimeout triggered");
        await remote1.disconnect();
        console.log("Done with disconnect");
    }, 2000);
    // try {
        await handler.waitForAllDispatches();
    // } catch (err) {
    //     console.log(`Caught an exception: ${err}`);
    //     console.log('Problem with waitForAllDispatches.');
    // } finally {
    //     console.log("2nd try at waitForAllDispatches");
    //     await handler.waitForAllDispatches();
    // }
    console.log('Done waiting');
```

Then it will seem to finish getting some of the costs (varies between 1 and 5 randomly) with the local agent after the disconnect triggers, and it then hangs indefinitely, like this:

> About to waitForAllDispatches
> name: Wikipedia Entry, href: /datasets/encyclopedia/0/entry/wikipedia-com
> name: Resy Availability, href: /datasets/restaurants/0/availability/resy-com
> name: YcombinatorNews Headlines, href: /datasets/news/0/headlines/news-ycombinator-com
> name: Github Coder, href: /datasets/code/0/coder/github-com
> name: Opentable Availability, href: /datasets/restaurants/0/availability/opentable-com
> name: Amazon ASIN Seller Prices, href: /datasets/products/0/sku-sellers/amazon-com
> https://ulixee.org/datasets/encyclopedia/0/entry/wikipedia-com
> https://ulixee.org/datasets/news/0/headlines/news-ycombinator-com
> setTimeout triggered
> Caught an exception: DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://3.239.86.236:2600)
> Problem with getDatasetCost: YcombinatorNews Headlines, https://ulixee.org/datasets/news/0/headlines/news-ycombinator-com
> 2021-03-24T04:19:42.797Z ERROR [/home/ubuntu/node_modules/@secret-agent/core/index] UnhandledErrorOrRejection {
>   clientError: 'DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://3.239.86.236:2600)',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> } DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://3.239.86.236:2600)
>     at RemoteConnectionToCore.cancelPendingRequests (/home/ubuntu/node_modules/client/connections/ConnectionToCore.ts:310:28)
>     at RemoteConnectionToCore.internalDisconnect (/home/ubuntu/node_modules/client/connections/ConnectionToCore.ts:219:10)
>     at RemoteConnectionToCore.disconnect (/home/ubuntu/node_modules/client/connections/ConnectionToCore.ts:126:16)
>     at Timeout._onTimeout (/home/ubuntu/SecretAgentTest5-server.js:51:23)
>     at listOnTimeout (internal/timers.js:554:17)
>     at processTimers (internal/timers.js:497:7)
> ------AGENT QUEUE---------------------------------
>     at Queue.run (/home/ubuntu/node_modules/commons/Queue.ts:28:19)
>     at CoreSessions.waitForAvailable (/home/ubuntu/node_modules/client/lib/CoreSessions.ts:20:23)
>     at RemoteConnectionToCore.useAgent (/home/ubuntu/node_modules/client/connections/ConnectionToCore.ts:170:30)
>     at Handler.dispatchAgent (/home/ubuntu/node_modules/client/lib/Handler.ts:80:8)
>     at /home/ubuntu/SecretAgentTest5-server.js:40:25
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at /home/ubuntu/node_modules/client/lib/Handler.ts:83:11
>     at Queue.next (/home/ubuntu/node_modules/commons/Queue.ts:71:19)
> ------WAIT FOR ALL DISPATCHES---------------------
>     at Handler.waitForAllDispatches (/home/ubuntu/node_modules/client/lib/Handler.ts:123:24)
>     at Handler.waitForAllDispatches (/home/ubuntu/node_modules/client/lib/Handler.ts:135:45)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at run (/home/ubuntu/SecretAgentTest5-server.js:55:9) {
>   coreHost: 'ws://3.239.86.236:2600',
>   code: 'DisconnectedFromCore'
> }
> Done with disconnect
> Cost of Wikipedia Entry is $0.00041
> https://ulixee.org/datasets/restaurants/0/availability/resy-com
> Cost of Resy Availability is $0.00060
> https://ulixee.org/datasets/code/0/coder/github-com
> Cost of Github Coder is $0.00035

**Comment by blakebyrnes** [comment]
It sounds like it's not behaving correctly. Will take a look at this issue.

For what it's worth, we added an API that will potentially simplify your code waiting for promises to complete:
https://secretagent.dev/docs/basic-interfaces/handler#wait-for-all-dispatches-settled

**Comment by A-Posthuman** [comment]
Thank you for reminding me of that new waitForAllDispatchesSettled(), I now modifed the code above to use that and no longer have the hanging issue, and it doesn't seem to be disconnecting from the local agent.

There is still one thing I don't understand which is depending on roughly when I schedule the setTimeout to trigger the remote disconnect, the local agent will then to proceed to get differing numbers of Costs. I see 1 console print of the "Problem with getDatasetCost:" in my code where I presume the remote agent that was in progress working on a getDatasetCost call got interrupted, but when I add that to how many Costs are ultimately returned in the console output, it varies.

It should end up as 6 Costs returned on a successful run I think, but with the setTimeout set to 3000 ms, I get sometimes just 1 Cost, plus the interrupted getDatasetCost console print. On other runs the local agent seems to go on a bit further and get 2 or 3 Costs.

Do you know where this variability is coming from, and how could I modify the code to always get all 6 Costs assuming I handle the interrupted getDatasetCost call to requeue that one?

**Comment by blakebyrnes** [comment]
I added another fix. I think the thing you aren't able to catch is "unstarted" dispatches that get canceled. The new PR automatically moves those to another connection, so once you have access to this code, you would just need to requeue the failure in getDatasetCost
