### ISSUE TITLE
Question about limits on saved sessions

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#188]
I haven't tracked how much space each session typically takes to save, but is there any concern of eventually filling up /tmp on long-running scraping tasks? I didn't see anything in the docs on ways to limit it or what might happen if /tmp fills up - in the case of the default Ubuntu AMI it doesn't appear /tmp is a separate partition, so it could fill the entire primary partition.

**Comment by blakebyrnes** [comment]
They can actually be pretty large right now. We haven't gotten to a steps of optimizing for space (sqlite3 in better-sqlite isn't compressed) or speed yet.

You could do a few things:
1. You can control which directory is written to (so use other partitions) using the sessionsDir parameter when you start your core on each server. 
2. You could do a regular cleanup of the sessions directory if you feel confident you don't want/need to go back and look at details (and/or archive them to another location). You can replay the session as long as you have the db somewhere.

I know neither of these are actual solutions, but is that helpful?

**Comment by A-Posthuman** [comment]
Yep will keep those in mind when building a production system, thx

**Comment by blakebyrnes** [comment]
Where would you have looked for this information in the docs? Would putting this in there somewhere be helpful? Or should we close this out?

**Comment by A-Posthuman** [comment]
Perhaps a quick mention of the sessionsDir parameter could be mentioned on the main Sessions docs page, right after where it discusses using the tmp dir location to store things.
