### ISSUE TITLE
Error: CoreServer needs further setup to launch the browserEmulator.

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#206]
`Error: CoreServer needs further setup to launch the browserEmulator. See server logs.`

Got this error immediately after starting my code on new created ubuntu 18.04 or 20.04 server. There is no such error on old server. My assumption is that on old server I updated secret-agent incrementally from secret-agent v1.3.* or maybe even from v1.2.* (if I remember correctly).

Current version secret-agent v1.4.1-alpha.0.

**Comment by blakebyrnes** [comment]
Hi @dmzebrov,
We did two things that might have triggered this message - one was switching to Chrome (from Chromium), and second, we added a "dependency checker" to ubuntu to make sure all the linked libraries that Chrome (and Chromium) need are present on the machine. We did this in a minor version release because the library is still in Alpha. Normally, this would have necessitated a full major version.

Were you able to run the instructions and get running?

**Comment by dmzebrov** [comment]
I am able to run on macOS Big Sur 11.2.1 and on Ubuntu 18.04 and not able to run on new created 18.04 or 20.04 server.

**Comment by blakebyrnes** [comment]
Oh, ok. Can you share logs from your server? Did you attempt to run the debian installer from the logs there and it didn't work?

**Comment by dmzebrov** [comment]
Can you please specify what logs you need?

**Comment by blakebyrnes** [comment]
Are there console output logs on the server?

**Comment by dmzebrov** [comment]
journalctl gives me absolutely nothing connected with secret-agent... In journalctl follow mode there are no new logs when I start my code and get  aforementioned error. I also checked /var/log/syslog, /var/log/dmesg and some others. Nothing...

**Comment by blakebyrnes** [comment]
How did you start SecretAgent on that server? Could you start again as a foreground process and look at the logs? Should just be outputting as normal stdout.

**Comment by dmzebrov** [comment]
Oh, you mean normal stdout, sorry for my misunderstanding. Here is file with node output:
[logs.txt](https://github.com/ulixee/secret-agent/files/6222584/logs.txt)

**Comment by blakebyrnes** [comment]
Are you running full-client all from that server? Ie, no special setup with a core process? If so, it looks like the log that shows you the command to run is being hidden from view. It should be telling you that you have missing dependencies and provides a script to correct it.

Do you have a session database you could share? It might show me more about what exactly is failing here.

Thanks

**Comment by dmzebrov** [comment]
Sure, here is database:

[cd63b450-90a1-11eb-910c-d3d7e1aa8173.db.zip](https://github.com/ulixee/secret-agent/files/6222936/cd63b450-90a1-11eb-910c-d3d7e1aa8173.db.zip)

**Comment by blakebyrnes** [comment]
Thanks! Unfortunately, doesn't have any details about the error. It _should_ be printing out that you have dependencies missing, and link to running this script:
`sudo $(npx puppet-install-deps)`

Just running this `npx puppet-install-deps` will tell you the script path, which you should be able to inspect first. If it's there correctly, running it will install all your dependencies.

**Comment by dmzebrov** [comment]
I ran script from output and it resolves the problem! Thank you!
