### ISSUE TITLE
Can mitm-socket be used with curl?

### ISSUE THREAD

**Issue by vkey** [ulixee/secret-agent#208]
Trying to understand is it possible to use mitm-socket with curl without spinning up the whole secret-agent instance. Tested with next scenario:
- run socket like this
`./connect /tmp/socks.sock '{"host":"www.google.com","port":"443","isSsl":true,"servername":"www.google.com","rejectUnauthorized":false,"clientHelloId":"Chrome83","keepAlive":false,"debug":true,"tcpTtl":64,"tcpWindowSize":65535,"proxyUrl":""}'`
- make request from curl like this
`curl -v -k --unix-socket /tmp/socks.sock https://www.google.com`

but instead of response receiving an error
```
Connected to www.google.com (/tmp/socks.sock) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
* stopped the pause stream!
```

Thank you in advance for any help with understanding what I am missing here.

**Comment by blakebyrnes** [comment]
Hi @vkey, unfortunately, the mitm-socket library is only really built at the moment to work as part of the wrapper nodejs project. The socket also really only emulates TLS and TCP settings. It doesn't deal with any of the http headers or http2 layers. Have you considered using the regular framework, but just turning off the Assets and Javascript? It turns Chrome/Secret Agent into basically just an http engine.
