### ISSUE TITLE
manually set user agent

### ISSUE THREAD

**Issue by Nisthar** [ulixee/secret-agent#227]
Is there currently an option to manually set the user agent ?

**Comment by calebjclark** [comment]
Not directly, although you can pass in browserEmulatorId, which controls the general range of the user-agent (https://secretagent.dev/docs/advanced/browser-emulators#preloaded-plugins).

Do browser emulators give you what you need or are you looking for something more?

**Comment by calebjclark** [comment]
This feature has been added to the new 1.5 release which we are in the middle of pushing to NPM.
