### ISSUE TITLE
TypeError with example code

### ISSUE THREAD

**Issue by Sandy-Garrido** [ulixee/secret-agent#228]
I am just running the following code but even this seems to throw an error for me...

```
import agent from 'secret-agent';

(async () => {
	await agent.goto('https://example.org');
	const title = await agent.document.title;
	const intro = await agent.document.querySelector('p').textContent;
	await agent.close();

	console.log('Retrieved from https://example.org', {
		title,
		intro,
	});
})();
```

I then run yarn start which pointts at this file `node index.js` but then I just get the following error

```
user@computer:~/Documents/projects/myproject$ yarn start
yarn run v1.22.10
$ node ./src/test.js
2021-05-02T14:59:10.343Z ERROR [/home/username/Documents/projects/myproject/node_modules/@secret-agent/core/index] UnhandledErrorOrRejection {
  clientError: "Error: TypeError: Cannot read property '0' of null\n" +
    '    at new ObjectAtPath (<anonymous>:212:38)\n' +
    '    at Function.exec (<anonymous>:128:30)\n' +
    '    at <anonymous>:1:53',
  context: {},
  sessionId: null,
  sessionName: undefined
} TypeError: Cannot read property '0' of null
    at new ObjectAtPath (<anonymous>:212:38)
    at Function.exec (<anonymous>:128:30)
    at <anonymous>:1:53
------CONNECTION----------------------------------
    at Object.createPromise (/home/username/Documents/projects/myproject/node_modules/commons/utils.ts:39:10)
    at RemoteConnectionToCore.createPendingResult (/home/username/Documents/projects/myproject/node_modules/client/connections/ConnectionToCore.ts:310:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (/home/username/Documents/projects/myproject/node_modules/client/connections/ConnectionToCore.ts:237:43)
    at RemoteConnectionToCore.sendRequest (/home/username/Documents/projects/myproject/node_modules/client/connections/ConnectionToCore.ts:149:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at CoreCommandQueue.runRequest (/home/username/Documents/projects/myproject/node_modules/client/lib/CoreCommandQueue.ts:41:22)
    at Queue.next (/home/username/Documents/projects/myproject/node_modules/commons/Queue.ts:70:19)
------CORE COMMANDS-------------------------------
    at Queue.run (/home/username/Documents/projects/myproject/node_modules/commons/Queue.ts:27:19)
    at CoreCommandQueue.run (/home/username/Documents/projects/myproject/node_modules/client/lib/CoreCommandQueue.ts:30:31)
    at CoreTab.execJsPath (/home/username/Documents/projects/myproject/node_modules/client/lib/CoreTab.ts:62:36)
    at execJsPath (/home/username/Documents/projects/myproject/node_modules/client/lib/SetupAwaitedHandler.ts:115:18)
    at Object.getProperty (/home/username/Documents/projects/myproject/node_modules/client/lib/SetupAwaitedHandler.ts:31:24)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at AwaitedHandler.getProperty (/home/username/Documents/projects/myproject/files/2-finalized/awaited-dom/base/AwaitedHandler.ts:23:12)
    at file:///home/username/Documents/projects/myproject/src/test.js:5:16

--------------------------------------------------
------default-session-----------------------------
------f2745720-ab56-11eb-8440-cb8dd35f1f7a--------
-------------------------------------------------- {
  isDisconnecting: false
}
```

many thanks for this as I have been able to see some parts working like the browser display and getting past some anti-bot control ! The hardwork hasn't gone unnoticed and I'm hopeful with this! (If I could get past this part)

I've tried with the latest alpha and also gone back as far as `1.4.0-alpha.0`

```
{
  "name": "project",
  "version": "1.0.0",
  "main": "index.js",
  "author": "me",
  "license": "MIT",
  "type": "module",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "secret-agent": "^1.4.1-alpha.4"
  }
}
```

OS: `ubuntu 20.04`

**Comment by blakebyrnes** [comment]
Thanks for reporting this. I accidentally broke this with a new version of awaited-dom: older versions of SecretAgent were allowing for minor versions to be resolved to the new breaking version. I'm going to push out a new release that fixes the awaited-dom version to the correct dependency.

You can fix in the interim by "pegging" awaited dom (add the following to your package.json: 

```
"resolutions": {
        "awaited-dom": "1.1.12"
    }
```

**Comment by Sandy-Garrido** [comment]
> Thanks for reporting this. I accidentally broke this with a new version of awaited-dom: older versions of SecretAgent were allowing for minor versions to be resolved to the new breaking version. I'm going to push out a new release that fixes the awaited-dom version to the correct dependency.
> 
> You can fix in the interim by "pegging" awaited dom (add the following to your package.json:
> 
> ```
> "resolutions": {
>         "awaited-dom": "1.1.12"
>     }
> ```

:joy: I just spent the last 3 hours digging down into awaited-dom trying to debug it...That worked! thanks Blake!

**Comment by blakebyrnes** [comment]
Oh geez. 🤦 Sorry..

Glad it worked.

**Comment by Sandy-Garrido** [comment]
No stress :) - I'm actually just really happy that you've been able to respond today!

**Comment by blakebyrnes** [comment]
I saw it come through and knew we fixed this in main shortly after that last release. Then I realized we never did the follow-on release, as we're still working through reorganizing the browser-emulators so they're easy to fork.

I just pushed out the new version too that pegs awaited-dom (1.4.1-alpha.5). Gonna go ahead and close this one. Thanks again!

**Comment by H0r53** [comment]
I'm experiencing the same error, but it's basically anytime I try to 'click'. For example, `await agent.interact({ move: email }, 'click');` where `email` is a result from `document.querySelector`. I added "resolutions" to the package.json but that didn't change anything. That field should be at the top level of the package.json right?

**Comment by blakebyrnes** [comment]
@H0r53 I think you might be running into a different error. If you change that to `await agent.interact({ click: email })`, do you see something different?

**Comment by H0r53** [comment]
That did seem to work, although the example I referenced came from the docs at https://secretagent.dev/docs/basic-interfaces/interactions/#using-shortcuts which I'm guessing are out of date?

**Comment by blakebyrnes** [comment]
🤦 Yes.. I was going to say, what you're trying to do makes sense... I just don't think we know how to handle an empty click right now.

**Comment by H0r53** [comment]
I sorta get it, basically every interaction is in simple JSON format and you can specify multiple via comma delimiting. Cool! Seems like a good product, although it looks like it's being detected by anti bot services.

**Comment by blakebyrnes** [comment]
Thanks!

Yeah, there are still a few holes at the moment. Your mileage may vary based on the site in question though (most sites are still fine). 

CreepJS is kind of a theoretical kitchen sink of tests. The ones that are currently being detected are javascript level problems that every single tool using proxies are running into right now, and will be fixed in Chrome 91. We have a workaround right now, but it's still too slow to push out. 

The CloudFlare issue has a workaround too, but needs some work to be ready for primetime.

**Comment by H0r53** [comment]
Sorry to bump this thread, but do you have any details you can share about the Chrome 91 fix and how it helps in general? Thanks!

**Comment by blakebyrnes** [comment]
You can currently detect javascript Proxy objects by creating classes that extend them. The stack trace and error message convert overridden functions to a different value than a normal function: https://github.com/ulixee/secret-agent/issues/203

Chrome 91 has a patch that fixes the underlying issue in v8.
