### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by ctaity** [ulixee/secret-agent#232]
this scrapper should bypass cloudflare detection on https://imginn.com/ana_botin/ ?

Because i am getting cloudlare error 1020 or enable cookies. Thanks

**Comment by Sandy-Garrido** [comment]
This is most likely an IP ban and therefore, you'll need a proxy/vpn to get around that.

**Comment by ctaity** [comment]
No, with puppeter  with https://www.npmjs.com/package/puppeteer-extra-plugin-stealth, pass from same IP, same machine.
![Screen Shot 2021-05-03 at 18 56 26](https://user-images.githubusercontent.com/5207990/116938541-4c6d1100-ac41-11eb-9a1c-d21999b0b9cf.png)

**Comment by Sandy-Garrido** [comment]
Ah, does this happen with with the default configuration? or have you changed some, if so, what have you altered?

**Comment by blakebyrnes** [comment]
I see it getting blocked too. Will look into it and see what they're picking up on.

**Comment by ctaity** [comment]
Default configuration, this is only site happens, i am testing with:
http://www.mundoplus.tv/noticias/?seccion=tv_digital 
https://vlmi.biz/ 
https://raidforums.com/Forum-Cracked-Accounts  
https://www.cotilleando.com/forums/foro-libre.22/  
https://uberpeople.net/forums/Tips

**Comment by ctaity** [comment]
Hi , some news about cloudflare?

**Comment by blakebyrnes** [comment]
Hi @ctaity, this is next on my list, but it's going to be an effort. They're detecting something in our http2 stack, which we need to fix emulation on. I'm going to have a way to turn off the mitm in the next release as an interim fix.

**Comment by ctaity** [comment]
how i can help or contribute?

**Comment by blakebyrnes** [comment]
Thanks! I think this particular one is a biggie. 

Step 1 is to get double-agent collecting http2 data and not breaking the rest of the tests. I added some collectors, but they were in the middle of an overhaul and so they got disabled. We need to know 1) header order, 2) http2 settings, 3) default padding on http2 requests for chrome versions, 4) the frame order in http2 (ie, settings, headers, response headers, continue, rst, etc)

Once we have all that, we need to figure out if we can accomplish the emulation in nodejs, or we need to move this down a layer into the go-mitm code.

**Comment by ctaity** [comment]
@blakebyrnes  Ok, which tool i can use to get the info we need ?

**Comment by A-Posthuman** [comment]
I noticed apify has released [got-scraping](https://github.com/apify/got-scraping) recently and they updated apify-js today to use it to make more realistic HTTP2 requests. Not sure if looking into that would help solve this or not, but figured I'd mention it just in case. I haven't tested it with wireshark or anything, sorry.

**Comment by blakebyrnes** [comment]
@A-Posthuman Thanks for the rec! Interesting library. Unfortunately, it doesn't really do anything at a low level. All just nodejs javascript level changes. It got 503 errors too.

**Comment by ctaity** [comment]
Hi, i still getting CF error 1020 on https://imginn.com/ana_botin/  with this code

`  handler.dispatchAgent(async (agent, url) => {
    if(url == undefined)
        return;
    await agent.goto(url);
    const body = await agent.document.body.textContent;
    res.body = await agent.document.body.textContent;
    res.statusCode = HttpStatusCodes.OK;
    next();
//   }, 'https://imginn.com/taity/', { showReplay:false});   
}, 'https://imginn.com/ana_botin/');   `

The version of the package json of the secreat-agent is:  "version": "1.4.1-alpha.5", 

CF message: 

`Please enable cookies. Error 1020 Ray ID: 65d43bcaca1b74f7 • 2021-06-10 17:14:00 UTC Access denied What happened? This website is using a security service to protect itself from online attacks. Cloudflare Ray ID: 65d43bcaca1b74f7 • Your IP: 186.22.18.111 • Performance & security by Cloudflare window._cf_translation = {}; (function(){window['__CF$cv$params']={r:'65d43bcaca1b74f7',m:'51840612f048535ac02bb9510501d82bede0b2d2-1623345241-1800-AeDsUCFNP3SoBE4ySmv9TbzyHjWDY8GWPIjQQINJGFx3iOsD2UliKyNVuk7HjtFm8uRBp81ySOWfVKo3FuVXPTNJaZdAahkpuxtnLstmR1Dl4+LKg5pBurWm/DlbHfIiUQ==',s:[0x8272eebc36,0x8ddc2e89b5],}})(); `

**Comment by blakebyrnes** [comment]
Hi @ctaity, this fix hasn't made it into a release yet. Sorry. The repo got into a weird state when we tried to create a submodule for each browser emulator, and we're still working through the new approach. It's like 90% ready, just finishing up some tests.

**Comment by ctaity** [comment]
ohh, @blakebyrnes thanks!!!!
