### ISSUE TITLE
xpath selectors

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#239]
What would be the correct and best way to wait for and select elements using xpath?

**Comment by blakebyrnes** [comment]
This is how you run XPath: https://github.com/ulixee/secret-agent/blob/3d83fc74dd566a42ea1d131d36ceb34a82676163/full-client/test/document.test.ts#L175

If you want to wait for it to be "human visible", you can pass the resulting elements to `agent.waitForElement`. 

However, if you're waiting for an xpath to return a result, the simplest current option is to loop in your script and check if results exist/are visible.

We'll eventually add a helper/more performant method to waitForElement.

**Comment by janisblaus** [comment]
This is awesome enough, not even need helpers! :)
