### ISSUE TITLE
set custom locations based on latitude and longitude

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#243]
Is it possible with secret-agent? 

Some websites display different data based on users' geolocation. 

In puppeteer I could use overridePermissions(url, ["geolocation"]) and page.setGeolocation(options)

**Comment by blakebyrnes** [comment]
Hi @janisblaus, not yet :( When I briefly thought about whether we wanted this (when we forked off of pupp), I thought we'd probably need to really think about aligning user IP with any geolocation. Do you usually think about just making sure timezone/geo/ip/locale are all in alignment?

**Comment by janisblaus** [comment]
> Do you usually think about just making sure timezone/geo/ip/locale are all in alignment?
Oh, yes, I have all mentioned things in place for the puppeteer, for some of my specific scraping stuff - these are very important.

Brightdata(and many other) allows to set required proxy location, so when it comes to aligning IP - it's not a big issue.
