### ISSUE TITLE
Emulator Tcp Settings not working in docker

### ISSUE THREAD

**Issue by blakebyrnes** [ulixee/secret-agent#25]
When running Secret Agent in a Docker, the Tcp settings to emulate Windows 7/10 don't take. Need to investigate if this has to do with running in Docker "on a mac", or if this is because the Go configuration is not working in Linux/Docker-slim

**Comment by nickmurr** [comment]
@blakebyrnes can you please share your Dockerfile, because i have issues to even run secret-agent via docker?

**Comment by blakebyrnes** [comment]
There's a Dockerfile in the root. Check out this answer: https://github.com/ulixee/secret-agent/issues/401#issuecomment-997960927
