### ISSUE TITLE
Iframe content on Ubuntu not always loading

### ISSUE THREAD

**Issue by magicaltoast** [ulixee/secret-agent#270]
Secret agent is not rendering the inner HTML of the iframe, the small example shows the issue.
Even this example in docs doesn't work https://secretagent.dev/docs/basic-interfaces/frame-environment#find-frame
Basicly innerhtml is empty for some reason

Node version: 14.17.1
Secret agent version: 1.5.1
OS: Ubuntu 20.04

```js
(async () => {
    await agent.goto("https://www.w3schools.com/html/html_iframe.asp") // Alternatively https://patrickhlauke.github.io/recaptcha/
    await agent.waitForMillis(10000)
    await agent.close()
})();
```

**Comment by blakebyrnes** [comment]
@magicaltoast thanks for reporting. The link you shared has a documentation issue which I'll resolve (it should be `getFrameEnvironment`)

I'm seeing mixed results getting the frames to load (for what it's worth, they load in the real browser, but Replay is showing them blank some of the time). Appears to be an issue waiting for the frame to properly load.
```

(async function main() {
  await agent.goto('https://www.w3schools.com/html/html_iframe.asp');
  const { document } = agent.activeTab;
  await agent.waitForPaintingStable();

  const iframeElement = document.querySelector('iframe');

  const iframe = await agent.activeTab.getFrameEnvironment(iframeElement);

  await iframe.waitForLoad(LocationStatus.AllContentLoaded);

  agent.output.html = await iframe.document.body.outerHTML;
  const h4 = await iframe.document.querySelector('h4').textContent; // should be something like HTML demo: <iframe>
  agent.output.h4 = h4;
  await agent.close();
})();

```

**Comment by blakebyrnes** [comment]
Reopening per comment from @magicaltoast. Are you seeing issues using that same script you have above?

**Comment by blakebyrnes** [comment]
Picking up from your other comment. This is what I see in replay for the link you sent

![image](https://user-images.githubusercontent.com/115056/124009942-31521f80-d9ac-11eb-8884-caf8c5f2612b.png)

**Comment by blakebyrnes** [comment]
Maybe it's time to boot up ubuntu.. that's on a mac

**Comment by magicaltoast** [comment]
![Screenshot from 2021-06-30 20-05-49](https://user-images.githubusercontent.com/68669235/124010080-a8a0a700-d9de-11eb-9c01-e4ca5befe333.png)

**Comment by blakebyrnes** [comment]
Could you send me the session database for one of these? https://secretagent.dev/docs/advanced/session

**Comment by magicaltoast** [comment]
@blakebyrnes 
I send you it on discord because Github doesn't support this file type.

**Comment by magicaltoast** [comment]
After last patch - 1.5.3, everything seems to works ;) Thanks for quick fix

**Comment by A-Posthuman** [comment]
I think I might be running into something like this issue now on SA 1.5.14 on Ubuntu 20.04. I have a test script that when run on Windows finds some anchor tags inside iframes that I'm looking for, but on Ubuntu for some reason can't find any?

When I await anIFrameEnvironment.document.body.outerHTML to see what it's got, it isn't empty, there is some js in the iframes on both platforms, but for some reason the Windows one seems to be executing properly and generating the rest of the expected iframe html/anchor tag, but on Ubuntu for some reason either it isn't doing that, or is receiving truncated js from the website, not sure.

**Comment by blakebyrnes** [comment]
@A-Posthuman can you send me a session database where you're seeing this?

**Comment by A-Posthuman** [comment]
Just to follow up, I continue to see this difference in behavior between Windows and Ubuntu 20.04, where on Ubuntu the iframe content appears to not be fully rendered somehow - as if perhaps some js is not fully being run or something. Not sure, I still haven't been able to dig into the dbs or anything.

But I'd like to request you reopen this issue, or if you prefer I can start a new one more specific to this current behavior.

**Comment by blakebyrnes** [comment]
Ok, can you send me the session DBs if you've got them? We have a number of iframe tests that run on ubuntu, so it should not be every frame that can't load.

**Comment by blakebyrnes** [comment]
It might be helpful to see a windows vs Linux db that’s as similar as possible, but has one not loading the frame. Maybe we’ll be able to spot a difference

**Comment by A-Posthuman** [comment]
Ok I'll provide those over on discord

**Comment by blakebyrnes** [comment]
@A-Posthuman did we decide this is loading, just likely some kind of blocking happening at the target site? Safe to re-close?

**Comment by A-Posthuman** [comment]
I'd say don't close it yet, because on further testing through my proxy I mentioned, I found that although my Windows SA 1.6.1 was being blocked, my real Firefox and Chrome were not. So there still seems to be some detection going on where the ad server seems to be detecting SA I think. IP addresses probably are playing some factor, perhaps in an overall detection score I'd guess, but it seems SA vs real browsers may also be at least somewhat detectable.

**Comment by blakebyrnes** [comment]
Determined with @A-Posthuman that this is likely being done on target site. Don't understand enough about why they're changing behavior on frames to know if its SecretAgent. Re-closing
