### ISSUE TITLE
Issue with using secrt-agent with electron & reactJS

### ISSUE THREAD

**Issue by akavenus** [ulixee/secret-agent#279]
I'm facing a issue when trying to use secret-agent with electron & reactJS. It works fine with nodeJS though.

Error:
C:/Users/venus/node_modules/@secret-agent/mitm/handlers/HeadersHandler.js
Module not found: Can't resolve '_http_common' in 'C:\Users\venus\node_modules\@secret-agent\mitm\handlers'

example.js
`import { Agent } from 'secret-agent';
async function start(){
    process.env.SA_SHOW_BROWSER =' true';
    const agent = await new Agent();
    await agent.goto('url');
    await agent.close();
}
start()
module.exports = { start }`

package.json
`{
  "name": "react-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@secret-agent/client": "^1.5.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "electron-is-dev": "^2.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "main": "public/electron.js",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "dev": "concurrently -k \"npm start\" \"npm:electron\"",
    "electron": "wait-on tcp:3000 && electron ."
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "concurrently": "^6.2.0",
    "wait-on": "^5.3.0"
  }
}`

**Comment by blakebyrnes** [comment]
I was about to look into this. Did you find a workaround? The open pr removed this internal node module.
