### ISSUE TITLE
Browser Size Support

### ISSUE THREAD

**Issue by akavenus** [ulixee/secret-agent#292]
It would be really nice if you added support for us to set the size of the browser on launch

For example:

`const agent = await new Agent({
      browserSize: '400,800'
    });`

**Comment by blakebyrnes** [comment]
Hi @akavenus, is the viewport parameter what you're looking for?

**Comment by akavenus** [comment]
Yes

**Comment by akavenus** [comment]
![image](https://user-images.githubusercontent.com/71657809/125838051-2466fb1d-c204-42ce-8aa5-8679049980ea.png)

In puppeteer you can set the viewport or browser size, the browser size actually changes the size of the brower instead of just the view port

here is how you would do it in puppeteer
`var browser = await puppeteer.launch({
              headless: false,
                args: [
                  '--window-size=400,800',
                  '--hide-scrollbars',
                  `--proxy-server=http://${split_proxy[0]}:${split_proxy[1]}`
                ],
              })`

**Comment by blakebyrnes** [comment]
Can you tell me a bit more about what you're not able to do with this setup? I believe the render of the page is using the provided sizes, just as it does when you change the emulated viewport within the Chrome Devtools panel. This is the API being used: https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride.

**Comment by blakebyrnes** [comment]
BTW, I do agree it's confusing and looks weird. Just making sure I understand what you're trying to do.

**Comment by akavenus** [comment]
Well, i dont believe that this changes the browser size correctly. For example heres what the browser shows on this
`const agent = await new Agent({
      viewport: '400,800'
    });`
![image](https://user-images.githubusercontent.com/71657809/125840575-19a42d7c-70dd-448f-b9e1-62c6ab754407.png)

vs a puppeteer browser that shows the actually 400, 800 size browser on this
`args: [
                  '--window-size=400,800'
]`

Was this ever added? [](https://github.com/ulixee/secret-agent/issues/58) I feel like this would fix this issue

**Comment by akavenus** [comment]
I believe I could be setting the viewport incorrectly. is it done like this?
`viewport:  '400, 800'`

**Comment by blakebyrnes** [comment]
I was just looking at the docs to see what we've listed and realized it doesn't have enough details for you to really do this easily without Typescript.

It's expecting this set of params. I'll update the docs.
```
{
  /** The page width in pixels. */
  width: number;
  /** The page height in pixels. */
  height: number;
  /**
   * Specify device scale factor (can be thought of as dpr).
   * @default 1
   */
  deviceScaleFactor?: number;
  /** The screen width in pixels. */
  screenWidth: number;
  /** The screen height in pixels. */
  screenHeight: number;
  /** Overriding view X position on screen in pixels (minimum 0, maximum 10000000). */
  positionX: number;
  /** Overriding view Y position on screen in pixels (minimum 0, maximum 10000000). */
  positionY: number;
}
```

**Comment by akavenus** [comment]
This worked, but is there anyway to make it so the browser size is = to the viewport size?
![image](https://user-images.githubusercontent.com/71657809/125841579-608f7713-2e1b-44c6-aa97-73f5804622e1.png)
`const agent = await new Agent({
      viewport: {
        width: 400,
        height: 800,
        screenWidth: 400,
        screenheight: 800
      }
    });`

**Comment by blakebyrnes** [comment]
Not checked in yet ;) I'm fixing that now. It's just weird looking though, the actual webpage should not be able to detect it.

**Comment by akavenus** [comment]
Alright thank you!
