### ISSUE TITLE
Having trouble figuring out how to prevent dev tools from opening on launch

### ISSUE THREAD

**Issue by akavenus** [ulixee/secret-agent#294]
Hello, I'm having some trouble figuring out how to prevent dev tools from opening on launch

![image](https://user-images.githubusercontent.com/71657809/125839338-9ad302b1-c67a-4d97-b851-a46c128a7e90.png)

When launch of the browser, dev tools is open. How would I make sure its closed on launch?

**Comment by blakebyrnes** [comment]
@akavenus we're working on improving the headed use of SecretAgent right now, so this is not the longterm solution, but there's an environment variable that will disable it: SA_DISABLE_DEVTOOLS=1

**Comment by akavenus** [comment]
Where would I place this in my code? It didn't work for me but the placement of it was probably wrong

**Comment by akavenus** [comment]
This worked, thank you

**Comment by nlile** [comment]
> Where would I place this in my code? It didn't work for me but the placement of it was probably wrong

`process.env.SA_DISABLE_DEVTOOLS = 1;`

**Comment by blakebyrnes** [comment]
@nlile - Either first thing in your script, or command line (before secret agent is loaded)
