### ISSUE TITLE
How to prevent chrome.exe opening

### ISSUE THREAD

**Issue by akavenus** [ulixee/secret-agent#296]
Is there anyway to prevent this blank command line from opening while using secret agent?

![image](https://user-images.githubusercontent.com/71657809/125856779-c7253915-d86d-4466-a928-bdf179e77004.png)

**Comment by blakebyrnes** [comment]
@akavenus does that show up if you run headless? Or just when headed?

**Comment by nlile** [comment]
@blakebyrnes I'm also getting (multiple) blank command lines in both headed & headless.

**Comment by akavenus** [comment]
For me it happens on both

Full code 
`const { Agent } = require('secret-agent')
async function start(){
    process.env.SA_SHOW_BROWSER = 'true';
    process.env.SA_DISABLE_DEVTOOLS=1
    const agent = await new Agent({
      viewport: {
        width: 400,
        height: 800,
        screenWidth: 500,
        screenHeight: 900
      }
    });
    await agent.goto('https://www.target.com/bia');
}
start()
module.exports.start = start`

**Comment by A-Posthuman** [comment]
Just chiming in to say I also see the empty black command window labeled chrome popping up on Windows.

**Comment by blakebyrnes** [comment]
@akavenus @A-Posthuman @nlile  I'm assuming no one sees this using puppeteer or playwright?

**Comment by akavenus** [comment]
Yes, I do not see this on puppeter. As for playwright I can't comment as I dont use that

**Comment by nlile** [comment]
> Yes, I do not see this on puppeter. As for playwright I can't comment as I dont use that

Gotcha covered, I don't see this on playwright, haven't tried puppeteer.

**Comment by blakebyrnes** [comment]
This is being triggered by the "--enable-logging" Chromium launch argument. Will fix, but in interim, you can filter out using a plugin that overrides `onBrowserWillLaunch` and removes this argument. (https://secretagent.dev/docs/plugins/core-plugins)
