### ISSUE TITLE
Error in child frame navigation can incorrectly resolve main frame navigation

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#300]
Seem to have randomly run into this on SA 1.5.4 on Ubuntu 20.04, while testing a script that simply uses agent.goto() to go through several URLs sequentially. Pretty normal script. The error occurred specifically on the agent.goto() line of the script. Re-running the script immediately afterward did not recreate the error, I only ran into this one time during several runs of the script.

console output attached:
[debug5.txt](https://github.com/ulixee/secret-agent/files/6836364/debug5.txt)

**Comment by blakebyrnes** [comment]
@A-Posthuman Thanks for reporting this! Are you running a server on your local machine to connect to this? Or using default agent?

**Comment by blakebyrnes** [comment]
Any chance you could send over your session database for the stack trace (b83b7080-e782-11eb-8d98-6f02daf42492)?

Blake

**Comment by A-Posthuman** [comment]
This was all on 1 server locally, yes. Just imported the agent at top of script and then doing some .goto() requests, then I have it set currently to stop after doing 3 requests and .close(). I'll send over the .db on discord

**Comment by blakebyrnes** [comment]
@A-Posthuman Meant to send an update here. Your logs show that your network hiccuped while loading one of the amazon pages. You should generally handle "goto" errors just in case there are network hiccups. We don't have any built-in retry - we can't be 100% sure a goto is idempotent, so we don't try. That said, it looks like the actual failure (looking in your resources table) was for a nested iframe on the last page that happened to be resolving navigation at the same time as the third goto. I think we should handle this scenario better, so will fix that portion.

**Comment by A-Posthuman** [comment]
Ok I'll definitely wrap my goto's in a try/catch going forward and handle errors. I was using waitForPaintingStable after the goto to try and make sure the page had finished resolving most stuff before I continued on to evaluate some page bits, and then also slept for 1 sec after that to try and not cause an odd errors. But yeah some stuff can still happen I see.
