### ISSUE TITLE
Unclear examples/documentation on remote agent setup

### ISSUE THREAD

**Issue by pzeepablo** [ulixee/secret-agent#303]
Secretagent.dev regularly references 'SecretAgent Cores', is that this?
https://github.com/ulixee/secret-agent/blob/main/examples/core-server.mjs

I'm looking to configure a handler with two cores (itself + 1 remote) to distribute requests too, and while the docs wave over this as a simple use case I am struggling to sort out exactly how this is meant to work. 

Using the example (and passing the ip/port that is exposed to the handler) does not work, and while I am very unfamiliar with node/js I haven't been able to make much headway. Is it possible for a very simple example of this functionality?

**Comment by blakebyrnes** [comment]
"Core" was originally supposed to be an internal module, but has increasingly been something users have had to learn about. We're putting a lot of time in how to simplify the deployment process right now. Can you share a bit more of your code used in your setup? Are you looking at this page in the docs? https://secretagent.dev/docs/advanced/remote

**Comment by pzeepablo** [comment]
I ended up looking through those and was able to get it working....you are right, it was simpler than I thought, my apologies.

Another question I was unable to find the answer to is if the handler is able to be configured to automatically health check cores and dynamically route based on that? As it currently stands once a core goes down for whatever reason the handler will not route another request to it, which can be concerning

**Comment by blakebyrnes** [comment]
@pzeepablo You can try/catch around failed agents to see if you want to re-queue them. An agent that "never" runs will be automatically re-queued, but we can't know for certain if an agent that has run a few commands can safely run again, so we don't do it automatically.

I'm gonna close this for now since it seems like you were able to get going on remote.
