### ISSUE TITLE
CertificateGenerator throws error on first run (Windows 10)

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#309]
Using code like below on Windows / SA 1.5.4, this is a modified version of your starter example.org code, with just a console prompt added to stop the program flow after getting the page title. On my machine this repeatably results in the error I attached in the text file if I let the open Chrome window just sit there for a few seconds after the script gets/prints the title. If I try to add to the script further gotos after this browser crash/close happens, I get back a further error which I haven't attached, but basically SA stops working.

```
import agent from 'secret-agent';

// Used for console prompting
import readline from 'readline';
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});
rl.on("close", function() {
  console.log("\nExiting");
  process.exit(0);
});
async function input(prompt) {
  console.log(prompt);
  return (await rl[Symbol.asyncIterator]().next()).value;
}

(async () => {
  process.env.SA_SHOW_BROWSER = 'true';
  process.env.SA_SHOW_REPLAY = "true";
  // await agent.goto('https://example.org');
  await agent.goto('https://www.amazon.com/');
  let title = await agent.document.title;
  // const intro = await agent.document.querySelector('p').textContent;
  // agent.output = { title, intro };
  agent.output = { title };
  // console.log('Retrieved from https://example.org', agent.output);
  console.log('Retrieved from https://www.amazon.com', agent.output);

  // pause the program flow, wait to see if error occurs
  const typed = await input("Hit enter to exit");
  console.log(`You typed: ${typed}`);

  await agent.close();
  rl.close();
})();
```

[debug7.txt](https://github.com/ulixee/secret-agent/files/6890158/debug7.txt)

**Comment by A-Posthuman** [comment]
Follow up, noticed I still can reproduce this cert error on SA 1.5.5 if I start with a completely empty Temp/.secret-agent dir. After that first run after it has populated the Temp dir with some cert and other db files, if I then kill the SA process and run script again then the error is gone.

[debug10.txt](https://github.com/ulixee/secret-agent/files/6935716/debug10.txt)

**Comment by blakebyrnes** [comment]
Thanks. Looks like this is a different error stack, but probably just got further than the last error stack that we fixed. Will re-open
