### ISSUE TITLE
UnhandledError(fatal) / Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#311]
See comments/nodes in the attached debug file:

[debug6.txt](https://github.com/ulixee/secret-agent/files/6890293/debug6.txt)

**Comment by blakebyrnes** [comment]
For the Invalid session error, I fixed this last week in the Hero branch. For the second issue, is this after the Http2 error crashed that core? What did you expect to happen here vs what did?

**Comment by A-Posthuman** [comment]
Yes, the 2nd error was after the core crashed, and then I tried to call close() on that agent. I guess what I'd like to know is in a case where my script catches an error that indicates the core might have crashed, can you document somewhere what would be the recovery process after that? If I call close() and catch another error, should I assume then the core is gone, and then try to instantiate a new one into my agent variable?

**Comment by blakebyrnes** [comment]
Ok, good questions. I think it's like being on the client side of any server. If it crashes, there's not a ton you're going to get back. If you get an ECONNREFUSED or ECONNRESET from the server, I think you'd want to back down and try to reconnect in a bit. On server side, you probably need something like pm2 to restart it if it crashes.
