### ISSUE TITLE
Form input

### ISSUE THREAD

**Issue by ctaity** [ulixee/secret-agent#316]
Hi , do you have an example to complete the form  and submit, I need to do a login page, puppeter has sendKeys method to complete the inputs. 

Thanks

**Comment by blakebyrnes** [comment]
@ctaity is this helpful? https://secretagent.dev/docs/basic-interfaces/interactions

Or did you look through that and it's not clear?

**Comment by ctaity** [comment]
The interactions uses coordinates...

the most used case i thnk is for example: 

```
 await agent.document.getElementById("user").sendKeys("user");
 await agent.document.getElementById("password").sendKeys("user");

 await agent.document.getElementById("login-fake-btn").click();
 await agent.document.querySelector("button[data-testid='log-in']");

```
Maybe we can have a sendKeys method or somethink like "click", and dont use coordinates, what do you think?

**Comment by blakebyrnes** [comment]
I think docs are bad ;)

"MousePosition" is poorly named. It really takes in a) coordinates or b) an element (https://secretagent.dev/docs/basic-interfaces/interactions#mouseposition)

So you can do 
```
await agent.interact({ click: document.getElementById("user")} , { type: 'user' });
or 
await agent.click(document.getElementById("user"))
await agent.type('user');
```

We will likely add an agent.fill(document.getElementById("user"), 'user'), but haven't done it yet
