### ISSUE TITLE
Inconsistent behavior of agent.activeTab.waitForLocation('change')

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#317]
Working with test script on Windows / SA 1.5.5, script uses interact to type text into search box, which triggers page navigation to new URL of the search result. I have attempted to use agent.activeTab.waitForLocation('change') (also tried with saving a command ID prior to this and passing that ID as an option, but that also seems to result in hang until timeout) to wait until the new page is switched to, but although this often works on the first search, subsequent searches on the same session sometimes seem to hang until the timeout is reached. Other times they work, it's inconsistent.

My goal is simply to wait until the new page URL is loaded in, so I can safely start getting DOM bits from it. I also tried using a second call to waitForPaintingStable (already used it once in the session when first loading in the starting url), but the second call to it seems to return too fast, leading to parts of the DOM not available yet.

Is there a better way?

**Comment by blakebyrnes** [comment]
What you're doing sounds reasonable. Can you share a session database with this occurring?

**Comment by A-Posthuman** [comment]
I don't have session dbs handy, but here is a test script that allows for easy testing of various types of trying to wait for the body of the new page to be available. It starts at the Amazon homepage, then uses the search box to go to first one product, wait for that location change, then try to go to a second product and also wait for that location change and/or body to be available.

On Windows I see these behaviors:

1. With the agent.activeTab.waitForLocation('change'); lines uncommented, I repeatably see the second one of these get stuck while trying to wait for the second product page change to be awaited. Hangs until timeout.

2. Trying to use the alternate version of the lines, that use sinceCommandId : beforeClickId, this hangs/times out on the first one. Not clear if I'm using sinceCommandId correctly?

3. If I instead uncomment the 3rd waiting option after the search box typing product requests, the agent.waitForPaintingStable({ timeoutMs: 5000 }); lines, this seems to work ok, but I think the real work is being done by the agent.waitForElement(agent.document.body, { waitForVisible : true }); lines. In fact if I comment out all of the waiting options and just rely on the agent.waitForElement(agent.document.body, { waitForVisible : true });, it seems to work ok. So is simply waiting for the body element to be available generally an ok approach to take?

4. I've also experimented a bit with using agent.interact({ waitForElementVisible : agent.document.body }); instead of agent.waitForElement, is there any real difference between these two methods?


```
import { Agent } from 'secret-agent';

process.env.SA_SHOW_BROWSER = 'true';
process.env.SA_SHOW_REPLAY = 'true';

(async () => {
  try {
    // start agent at homepage
    let agent = await new Agent( { maxConcurrency: 1 } );
    let resource = await agent.goto('https://www.amazon.com/');
    await agent.waitForPaintingStable( { timeoutMs: 5000 } );
    let title = await agent.document.title;
    agent.output = { title };
    console.log('Retrieved from Amazon: ', agent.output);

    // try searching for something
    let typed = 'B00173K6BM';
    let aElem = agent.document.querySelector('[aria-label="Search"]');
    let beforeClickId = agent.lastCommandId;
    await agent.interact({ doubleclick : aElem, type : typed + "\n" });
    console.log('waiting for page location change');
    await agent.activeTab.waitForLocation('change');
    // await agent.activeTab.waitForLocation('change', { timeoutMs : 5000, sinceCommandId : beforeClickId });
    // await agent.waitForPaintingStable({ timeoutMs: 5000 });
    console.log('waiting for body element to be visible');
    // works on Windows, but not reliably on Ubuntu ?
    // await agent.interact({ waitForElementVisible : agent.document.body });
    await agent.waitForElement(agent.document.body, { waitForVisible : true });
    console.log('done');
    title = await agent.document.title;
    agent.output = { title };
    console.log('Got title: ', agent.output);
  
    // now try searching for something else
    typed = 'B0044O9U40';
    aElem = agent.document.querySelector('[aria-label="Search"]');
    beforeClickId = agent.lastCommandId;
    await agent.interact({ doubleclick : aElem, type : typed + "\n" });
    console.log('waiting for page location change');
    await agent.activeTab.waitForLocation('change');
    // await agent.activeTab.waitForLocation('change', { timeoutMs : 5000, sinceCommandId : beforeClickId });
    // await agent.waitForPaintingStable({ timeoutMs: 5000 });
    console.log('waiting for body element to be visible');
    // works on Windows, but not reliably on Ubuntu ?
    // await agent.interact({ waitForElementVisible : agent.document.body });
    await agent.waitForElement(agent.document.body, { waitForVisible : true });
    console.log('done');
    title = await agent.document.title;
    agent.output = { title };
    console.log('Got title: ', agent.output);

    await agent.close();
    process.exit();
  } catch (err) {
    console.log(`Caught an exception: ${err}`);
  }
})();
```

**Comment by A-Posthuman** [comment]
As a further followup, I'm finding waitForPaintingStable is turning out to be inconsistent when using it on these sample Amazon search result pages. When using it, and then trying to get the first search result item's a href link, sometimes I get the link, sometimes I get nothing from my xpath evaluate(). Is there something beyond waitForPaintingStable I can use to wait for the page to load in all its various javascript bits and be more complete before I try evaluate()ing stuff?

I guess I will end up using waitForElement, but this will require some extra logic in my code since sometimes there could be zero search results, or also it's hard to tell what exactly to wait for to determine all the search results are loaded in?

**Comment by A-Posthuman** [comment]
More further followup, while experimenting with await agent.interact({ waitForMillis: 2000 });, I find it works on the first use in my script, but then the next time through my loop when it is called again it seems to return immediately or almost immediately, definitely no longer waiting 2 seconds. On the plus side this seems to have made my xpath evaluatate()s magically more reliable, although I don't understand why.

**Comment by A-Posthuman** [comment]
Additional info: realized that querySelector() seems to return a promise I need to await, although in the SA docs I don't see this. Also for some reason in Visual Studio Code when I use await with querySelector() it is putting 3 "info" dots under the await with a hover text stating "'await" has no effect on this type of expression. (ts80007)"

**Comment by blakebyrnes** [comment]
`When using it, and then trying to get the first search result item's a href link, sometimes I get the link, sometimes I get nothing from my xpath evaluate(). Is there something beyond waitForPaintingStable I can use to wait for the page to load in all its various javascript bits and be more complete before I try evaluate()ing stuff?`

> Do you know if the page itself is rendered underneath? waitForPaintingStable is really measuring "above the fold" load-state. You can still use the browser "load" event (waitForLocation('AllContentLoaded') or waitForLocation("DomContentLoaded") which will sometimes trigger after paintingStable if the page is long.

`More further followup, while experimenting with await agent.interact({ waitForMillis: 2000 });, I find it works on the first use in my script, but then the next time through my loop when it is called again it seems to return immediately or almost immediately, definitely no longer waiting 2 seconds.`

> Is that the whole interact snippet? Or is that being combined with something else?

**Comment by blakebyrnes** [comment]
> Additional info: realized that querySelector() seems to return a promise I need to await, although in the SA docs I don't see this. Also for some reason in Visual Studio Code when I use await with querySelector() it is putting 3 "info" dots under the await with a hover text stating "'await" has no effect on this type of expression. (ts80007)"

Typescript seems to get aggressive with grabbing all `document` instances sometimes. I haven't narrowed down why it does that, but I've noticed it's worse when "dom" is enabled in the typescript library and you destruct document from agent.

You don't have to await querySelector until you want to resolve a property (ie, await document.querySelector('body').textContent`, or you want to resolve the element itself so you can log the high level internal state (`console.log(await document.querySelector('body'))`). SecretAgent will stop you from running a second command before the previous one is complete anyways, so the await is just for better error tracking (and preventing unhandledRejection errors in node)

**Comment by A-Posthuman** [comment]
> 
> 
> > When using it, and then trying to get the first search result item's a href link, sometimes I get the link, sometimes I get nothing from my xpath evaluate(). Is there something beyond waitForPaintingStable I can use to wait for the page to load in all its various javascript bits and be more complete before I try evaluate()ing stuff?
> 
> Do you know if the page itself is rendered underneath? waitForPaintingStable is really measuring "above the fold" load-state. You can still use the browser "load" event (waitForLocation('AllContentLoaded') or waitForLocation("DomContentLoaded") which will sometimes trigger after paintingStable if the page is long.

Using await agent.activeTab.waitForLoad('AllContentLoaded'); (note: AllContentLoaded not mentioned in docs, also this status doesn't seem to work with waitForLocation)

I'm still getting inconsistent behavior. It doesn't seem to be waiting long enough for the search results to be loaded. At this point I've tried pretty much every type of "waitFor" status in SA and I can't seem to hit on one that will generate consistent results with the evaluate() xpath query I run after that point in my script. Sometimes I get back the expected xpath result, other times I often get back a null result. Not sure what's up. The only thing that seems to let me reliably get the expected results on query after query is if I do a manual 1000 ms sleep using my own sleep function.

> 
> > More further followup, while experimenting with await agent.interact({ waitForMillis: 2000 });, I find it works on the first use in my script, but then the next time through my loop when it is called again it seems to return immediately or almost immediately, definitely no longer waiting 2 seconds.
> 
> Is that the whole interact snippet? Or is that being combined with something else?

Yes, just trying to using the waitForMillis interact option in place of my own sleep function, and it doesn't seem to work reliably.

**Comment by blakebyrnes** [comment]
Yes, sorry. Meant waitForLoad. We kind of deprecated AllContentLoaded since it leads to so many issues, but it's still in the code.

When these types of cases come up, I usually do a waitForElement and find a querySelector for an element that will only show up once all the results are there. It sounds like we need to improve the xpath experience, but does it work better with selectors?

Regarding waitForMillis, I haven't ever used it alone in interact. There's a waitForMillis that's on agent. Maybe it will give more reliable timers? That's the one I use for waiting

**Comment by A-Posthuman** [comment]
Ok, thanks for the additional tips, now I have gotten something working that seems more reliable. The agent.waitForMillis does work better.

Still see the problems with agent.activeTab.waitForLocation('change') mentioned up earlier this issue, for now I'm just not even using it after clicking to go to next page, an agent.waitForElement() seems to be enough to make things work.

**Comment by blakebyrnes** [comment]
@A-Posthuman This seems to be working reliably now with waitForLocation('change'). If you get a second, could you check if you're seeing more reliable results with your original script?

**Comment by A-Posthuman** [comment]
I just checked on SA 1.5.8 and yes those waitForLocation('change') lines seem to work now on that test script I posted above.

However when checking the alternate lines, by commenting out the 2 "await agent.activeTab.waitForLocation('change');" lines and then uncommenting the 2 lines after those, I'm getting an expected timeout error. I tried lengthening the timeout to 30000, but still get this error after only more like 5 seconds. Am I using the "sinceCommandId" feature incorrectly?

Here is the current test script and error:

```
import { Agent } from 'secret-agent';

process.env.SA_SHOW_BROWSER = 'true';
process.env.SA_SHOW_REPLAY = 'true';

async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

(async () => {
  try {
    // start agent at homepage
    let agent = await new Agent( { maxConcurrency: 1 } );
    let resource = await agent.goto('https://www.amazon.com/');
    await agent.waitForPaintingStable( { timeoutMs: 5000 } );
    let title = await agent.document.title;
    agent.output = { title };
    console.log('Retrieved from Amazon: ', agent.output);

    // try searching for something
    let typed = 'B00173K6BM';
    let aElem = agent.document.querySelector('[aria-label="Search"]');
    let beforeClickId = agent.lastCommandId;
    await agent.interact({ doubleclick : aElem, type : typed + "\n" });
    console.log('waiting for page location change');
    // await agent.activeTab.waitForLocation('change');
    await agent.activeTab.waitForLocation('change', { timeoutMs : 30000, sinceCommandId : beforeClickId });
    // await agent.waitForPaintingStable({ timeoutMs: 5000 });
    console.log('waiting for body element to be visible');
    // works on Windows, but not reliably on Ubuntu ?
    // await agent.interact({ waitForElementVisible : agent.document.body });
    await agent.waitForElement(agent.document.body, { waitForVisible : true });
    console.log('done');
    title = await agent.document.title;
    agent.output = { title };
    console.log('Got title: ', agent.output);
  
    // now try searching for something else
    typed = 'B0044O9U40';
    aElem = agent.document.querySelector('[aria-label="Search"]');
    beforeClickId = agent.lastCommandId;
    await agent.interact({ doubleclick : aElem, type : typed + "\n" });
    console.log('waiting for page location change');
    // await agent.activeTab.waitForLocation('change');
    await agent.activeTab.waitForLocation('change', { timeoutMs : 30000, sinceCommandId : beforeClickId });
    // await agent.waitForPaintingStable({ timeoutMs: 5000 });
    console.log('waiting for body element to be visible');
    // works on Windows, but not reliably on Ubuntu ?
    // await agent.interact({ waitForElementVisible : agent.document.body });
    await agent.waitForElement(agent.document.body, { waitForVisible : true });
    console.log('done');
    title = await agent.document.title;
    agent.output = { title };
    console.log('Got title: ', agent.output);

    console.log('sleeping 5 seconds');
    await sleep(5000);

    await agent.close();
    process.exit();
  } catch (err) {
    console.log(`Caught an exception: ${err}`);
  }
})();
```

> PS {path to my script}> node waitforlocationchangetest.mjs
> Retrieved from Amazon:  { title: 'Amazon.com. Spend less. Smile more.' }
> waiting for page location change
> 2021-08-31T18:50:35.441Z ERROR [{path to my script}\node_modules\@secret-agent\core\index] UnhandledErrorOrRejection {
>   clientError: 'TimeoutError: Timeout waiting for promise',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> } TimeoutError: undefined
>     at new Resolvable ({path to my script}\node_modules\commons\Resolvable.ts:17:18)
>     at CertificateGenerator.generateCerts ({path to my script}\node_modules\mitm-socket\lib\CertificateGenerator.ts:44:24)
>     at Function.getCertificate ({path to my script}\node_modules\mitm\lib\MitmProxy.ts:508:34)
>     at MitmProxy.addSecureContext ({path to my script}\node_modules\mitm\lib\MitmProxy.ts:431:18)

**Comment by A-Posthuman** [comment]
Ahh ok duh, yes that fixed it, all working now.
