### ISSUE TITLE
XPathResult iterateNext() returns object promise instead of null

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#318]
When I try an xpath evaluate that seems to result in no nodes, and I've specifiied the result type should be awaitedDOM.XPathResult.ORDERED_NODE_ITERATOR_TYPE, and then I try to use iterateNext(), the docs say it should return null, but I'm getting an object promise that I seem to have to await in order to resolve to null. Not sure if that is how it is supposed to work?

**Comment by blakebyrnes** [comment]
@A-Posthuman I think this is a case of the docs being copied from mdn incorrectly. All of AwaitedDom requires awaiting promises to know if things will resolve or not since it's running remotely in the actual browser, and javascript's event stack wouldn't wait for it to complete otherwise. Is the behavior confusing? Or just the bad documentation?

**Comment by A-Posthuman** [comment]
Yes I think the docs were just slightly confusing me, because many of the Properties on the XPathResult doc page show they return a Promise of some type, but these two methods below didn't mention it.

By the way, do you know of any good logging or other inspection methods that would make it easier for me to log or see/play with the object returned as something like XPathResult? When I try to log it I just end up seeing a bunch of promises, it's hard to see what my xpath query is actually returning?

**Comment by blakebyrnes** [comment]
Ok, I see it now. We are pulling over the full documentation from mdn and trying to modify to match the awaited part of our api, but there are holes like this one that happen in the text. You can "await" the result to see if it's null, but you can also dig further into the resulting SuperNode to get a sub-property before we make a round-trip to the browser.

What is it showing you when you console log? It's supposed to be including some details about some of the internals of the object that we've retrieved from the browser (this only occurs once you've awaited some property on it, however).
