### ISSUE TITLE
1.5.5 upgrade issue: could not find module 'chrome-latest'

### ISSUE THREAD

**Issue by 4caoi** [ulixee/secret-agent#319]
After upgrading from ^1.4.1-alpha.5 to 1.5.5, an error stating it could not find 'chrome-latest' was thrown on starting my server. 

 I didn't save the output, but it was approximately: call stack:  @secret-agent/plugin-utils/lib/utils/requirePlugins.js -> core/index.js

Chrome was installed in .cache/secret-agent and I uninstalled/reinstalled several times.

Reverting back to ^1.4.1-alpha.5 resolved the issue.

This is running on Arch.

**Comment by blakebyrnes** [comment]
Hi @4caoi, thanks for reporting this. Could you share your agent initialization configuration? I'm wondering if you had a legacy browser emulator id being copied over (those changed structure significantly across versions).

**Comment by 4caoi** [comment]
Thanks and good call on the emulator id ... I took out "browserEmulatorId", re-upgraded and it works without issue now.  

```js
const createAgent = async options => {
	const agentOptions = options || {
		showReplay: false,
		browserEmulatorId: "chrome-latest",
		blockedResourceTypes: ["All"],
	};
	const agent = await new Agent(agentOptions);
	return agent;
};


```
