### ISSUE TITLE
Edited Title: ClientPlugin Typescript definitions not registering

### ISSUE THREAD

**Issue by andynuss** [ulixee/secret-agent#320]
In my package.json for my project, I specify the latest version of secret-agent:

    "dependencies": {
      ...
      "secret-agent": "^1.5.5"
    },

But I am getting errors in my typescript snippet to call executeJs() taken from this repo's latest tests and some recent issues:

    /* eslint-disable no-console */
    import { Agent } from 'secret-agent';
    import ExecuteJsPlugin from '@secret-agent/execute-js-plugin';

    (async() => {
      const requestUrl: string = 'https://example.com';

      const userAgent =
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.165 Safari/537.36';
      const agent = new Agent({
        userAgent,
      });

      agent.use(ExecuteJsPlugin);
      await agent.goto(requestUrl);
      await agent.waitForPaintingStable();

      const response = await agent.executeJs((num) => {
        return num;
      }, 1);
      console.log('response', response);
      await agent.close();

    })();

The first error is the attempt to import ExecuteJsPlugin.  That is flagged in vscode.
The second error flagged in vscode is the attempt to call agent.executeJs.

So I looked in my compiled node_modules, in the file that implements the Agent class,
which is node_modules/@secret-agent/client/lib, and sure enough did not find the
executeJs member function there.

What am I doing wrong?

**Comment by ctaity** [comment]
Hi, exists a way to use the Agent Output from the executeJs function? to debug a script ? thanks

**Comment by andynuss** [comment]
Sorry, don't understand.  What I am saying is that I was wanting to do as in issue 281, and followed the example code in plugins/execute-js/test/basic.test.ts

... but it did not work for me because apparently executeJs is not a function in the Agent class.

**Comment by blakebyrnes** [comment]
@andynuss Thanks for reporting this! If you @ts-ignore that line, does the code work? I think we might have an issue getting the typescript declaration file loading.

**Comment by andynuss** [comment]
Actually, yes it does work.  My guess is that this is possible only because the call to ExecuteJsPlugin injects the executeJs function into the Agent class's prototype?

But I did have to @ts-ignore both the import ExecuteJsPlugin statement, and the executeJs() call.

**Comment by andynuss** [comment]
I was also wondering in keeping with the overall goal of secret-agent, you guys were able to figure out how to accomplish the executeJs() without leaving a detectable "trace" of some kind, such as a global variable in the webpage's dom?

**Comment by blakebyrnes** [comment]
>  My guess is that this is possible only because the call to ExecuteJsPlugin injects the executeJs function into the Agent class's prototype?

Yep! I'm 99% sure there's a way to get the global overrides to register when you include a module. Just need to dig in and figure it out. You don't happen to know how? :)

**Comment by andynuss** [comment]
No, I don't, sorry

**Comment by andynuss** [comment]
BTW, it makes sense that it would be difficult to allow calls to executeJs without the @ts-ignore since it is not there in the compiled Agent class.  And I'm fine if nothing can be done about this.  However, why do I have to @ts-ignore the import statement for the function implemented in '@secret-agent/execute-js-plugin'?

**Comment by blakebyrnes** [comment]
@andynuss 

> I was also wondering in keeping with the overall goal of secret-agent, you guys were able to figure out how to accomplish the executeJs() without leaving a detectable "trace" of some kind, such as a global variable in the webpage's dom?

Really depends what you "do" in javascript. We were hesitant to put executeJs into SecretAgent "core" because it opens the door to people running things that can get them detected (dom modification, modify cookies, etc, etc). That's why it lives in a plugin.

________

Regarding the import issue, what's the typescript error?

**Comment by andynuss** [comment]
It was my mistake, sorry, I needed to add '@secret-agent/execute-js-plugin' to my dependencies.  Mousing over the error told me that.
