### ISSUE TITLE
strange behaviour https://mewe.com/login

### ISSUE THREAD

**Issue by ctaity** [ulixee/secret-agent#323]
when navigate the page with firefox o chrome the login button is enabled and works fine, when navigate with SA, the login button is always disabled:

code : 

 ```
@Get('test')
  test(@Res() res: Response) {
    this.handler.dispatchAgent(
      async (agent: Agent) => {
        try {
          const { activeTab } = agent;

          this.logger.log('https://mewe.com/login');
          await agent.goto('https://mewe.com/login');
          // await agent.waitForMillis(10 * 1000);
          await agent.waitForPaintingStable();
          await activeTab.waitForLoad(LocationStatus.DomContentLoaded);

          res.status(HttpStatus.OK);
        } catch (e) {
          this.logger.error(e);
          res.send(e).status(HttpStatus.INTERNAL_SERVER_ERROR);
        }
      },
      {
        showReplay: true,
      },
    );
  }
```
 
![Screen Shot 2021-08-07 at 15 28 21](https://user-images.githubusercontent.com/5207990/128610487-66a48df6-71e6-462e-b7eb-1a0db8919310.png)
vs
![Screen Shot 2021-08-07 at 15 28 05](https://user-images.githubusercontent.com/5207990/128610483-80ccf791-c4fd-4816-b468-3719739e5b5f.png)

**Comment by blakebyrnes** [comment]
Hi @ctaity, I think this is only happening in Replay. If you launch the browser headed it seems to show the button normally. Are you seeing odd scraping behavior? Or just rendering of the replay?

**Comment by ctaity** [comment]
the button always stays disabled with showReplay: false, and showReplay:true.

await button.hasAttribute('disabled')

how i can launch the browser  headed mode ?

**Comment by blakebyrnes** [comment]
Oh, interesting. Maybe they're somehow detecting headless or triggering off some kind of page or mouse interaction? `process.env.SA_SHOW_BROWSER="1"` will launch the browser (put at top of your script or set var on command line if mac/linux)

**Comment by ctaity** [comment]
Thanks a lot, is working now. now i only need to get all cookies after the login, but i cant, this is the code 

```
  try {
          const { activeTab, document } = agent;

          this.logger.log('https://mewe.com/login');
          await agent.goto('https://mewe.com/login');
          await agent.waitForMillis(2 * 1000);
          await agent.waitForPaintingStable();
          await activeTab.waitForLoad(LocationStatus.DomContentLoaded);

          await agent.interact(
            { click: document.getElementById('email') },
            { type: 'leandro.escugil@yahoo.com' },
          );

          await agent.interact(
            { click: document.getElementById('password') },
            { type: 'trendiT-30' },
          );

          const submit = await agent.document.querySelector(
            "form button[type='submit']",
          );
          await submit.click();

          await activeTab.waitForLocation('change');
          await agent.waitForMillis(2 * 1000);
          await agent.waitForPaintingStable();
          await activeTab.waitForLoad(LocationStatus.DomContentLoaded);

          const cookieStorage = agent.activeTab.cookieStorage;
          const cookies = await cookieStorage.getItems();
          this.logger.log(util.inspect(cookies));

          res.status(HttpStatus.OK).send(cookies);
        } catch (e) {
          this.logger.error(e);
          res.send(e).status(HttpStatus.INTERNAL_SERVER_ERROR);
        }
```

exists other form to get the cookies?

**Comment by blakebyrnes** [comment]
You could try exportUserProfile. What's not coming back?

**Comment by ctaity** [comment]
Yes, with export profile i get all cookies. thanks!
