### ISSUE TITLE
What is the set of commands to build the Dockerfile?

### ISSUE THREAD

**Issue by nlile** [ulixee/secret-agent#325]
The `Dockerfile` seems to be broken and/or outdated. I tried building it a couple different ways, and I couldn't get it to work. However, I'm not fluent in JS/Ts/GO so this might be a dumb config question.

```
 => ERROR [6/9] COPY ./build-dist /app/secret-agent/                                                                                                                               0.0s
------
 > [6/9] COPY ./build-dist /app/secret-agent/:
------
failed to compute cache key: "/build-dist" not found: not found

```

Before digging through every reference to `build-dist` I figured I'd ask.

The documentation on Docker is a bit confusing/lacking. For example, the [final comment](https://github.com/ulixee/secret-agent/blob/main/Dockerfile) in the Dockerfile references a non-existent file: 
> To run this docker, please see /tools/docker/docker-run.sh

**Comment by blakebyrnes** [comment]
Hi @nlile, this dockerfile might indeed be out of date. We were using it actively but it's kind of become an artifact lately. 

It's meant to be run from the monorepo. You run `yarn build:docker`

Then the scripts that the comment is referring to is at: `https://github.com/ulixee/secret-agent/tree/main/tools/docker`

**Comment by nlile** [comment]
> It's meant to be run from the monorepo. You run `yarn build:docker`

I figured I was doing a basic step incorrectly with the monorepo. Turns out I was running `docker build .` when I should have been using `yarn build:docker`.

The Dockerfile build is failing me on the final step

`[9/9] RUN node core/start;`

It gets stuck there indefinitely, forgot about it and left it running for over an hour. This was on Windows 10, I'll report back after I get a chance to build it on Linux.

**Comment by blakebyrnes** [comment]
@nlile I just double-checked what CMD does. It shouldn't be running anything during "build". It's just an instruction for what to run when the docker is actually run. Could this be something else going on with uploading the build?

**Comment by caerulescens** [comment]
Here are the steps for building `secret-agent`'s `Dockerfile` for Linux based on @blakebyrnes advice

* install [nvm](https://github.com/nvm-sh/nvm#installing-and-updating)
* Install `node`: `nvm install node`
* Install `yarnpkg`: `npm install --global yarn`
* Install project dependencies: `yarnpkg install`
* Build `Dockerfile` with `yarnpkg`: `yarnpkg build:docker`

```
$ docker images
REPOSITORY     TAG       IMAGE ID       CREATED              SIZE
secret-agent   latest    638885d4d9bb   About a minute ago   1.83GB
node           14-slim   4db9829fac0a   26 hours ago         168MB
```

**Comment by blakebyrnes** [comment]
Thanks @caerulescens 

@nlile should I close this ticket?
