### ISSUE TITLE
IndexedDB.requestDatabaseNames: No document for given frame found

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#327]
![image](https://user-images.githubusercontent.com/1029697/129307858-dc614fac-be8f-426c-9bd5-4db139ff9dc9.png)

Code attached as zip.

[problem-2.zip](https://github.com/ulixee/secret-agent/files/6980048/problem-2.zip)

**Comment by blakebyrnes** [comment]
Fixed in latest version
