### ISSUE TITLE
storage when using exportUserProfile() is saved only for last domain visited

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#328]
Storage part when using await agent.exportUserProfile(); gets overwritten by last domain visited. 

If userprofile is used in more than one domain that uses localstorage, it will not be saved for all domains.

Code attached. 

[problem-3.zip](https://github.com/ulixee/secret-agent/files/6980063/problem-3.zip)

**Comment by janisblaus** [comment]
I've started to think and I guess this could be because of using incognito and should be expected behavior then?

Probably a workaround would be to store storage after every domain change?

**Comment by blakebyrnes** [comment]
@janisblaus Thanks for reporting this. This is a big difficiency in the way things are built at the moment. For localstorage (and indexedDbs) Devtools makes you provide the secureOrigin to read storage and indexedDb, and it has to be an "Active" origin, so we need to do a better job tracking the urls coming in and then creating fake pages to load up the state... 

Or find a way to read the user-data-dir.

**Comment by janisblaus** [comment]
>find a way to read the user-data-dir.
I think this could be very, very hard as they protect the user data dir even against moving to another machine. 

I kinda resolved this issue by just reading storage state with exportUserProfile() after doing anything, like navigation, etc. Seems to work fine.
