### ISSUE TITLE
Cloudflare bot detection under attack mode.

### ISSUE THREAD

**Issue by ctaity** [ulixee/secret-agent#329]
Cloudflare in under attack mode is detecting SA again, you can test it on https://api.shodan.io/ for example. 

Thanks for all and this great product.

**Comment by blakebyrnes** [comment]
@ctaity that url is giving me a 404. Could you share a session database where you got blocked again?

**Comment by blakebyrnes** [comment]
@ctaity did you ever get more info on this?

**Comment by ctaity** [comment]
Yes shodan is under cloudflare protection called: under attack mode. 
In this mode time to time cloudflare ask for a challenge (I attach a image)
![Screen Shot 2021-09-07 at 18 55 52](https://user-images.githubusercontent.com/5207990/132415979-27e1cdd4-4481-4887-949f-1e78c70ee57a.png)
)
In normal circumstances, after waits 5 o 6 seconds, Cloudflare redirects the browser and sets some cookies. 
But now, the browser never redirected, Cloudflare asks to wait 5 seconds over and over again. 

to share my sessiondatabase i need to do:

put  SessionReplay On 
and later send to you the folder in /tmp/.secret-agent, is ok?

I am using OSX.
Thabnks

**Comment by blakebyrnes** [comment]
Ok, yes please. I can't access the url, so can't do much to test or validate at the moment.

**Comment by ctaity** [comment]
@blakebyrnes please send me an email to: ctaity@gmail.com and I will send you a link to access it.

**Comment by ctaity** [comment]
@blakebyrnes another page with a defense system is https://doxbin.org/, can detect SA too. 

![Screen Shot 2021-09-07 at 22 50 37](https://user-images.githubusercontent.com/5207990/132433124-a331da28-3a80-43c9-89e9-02409bc8ac7a.png)

**Comment by ctaity** [comment]
@blakebyrnes you are a genius.
