### ISSUE TITLE
Keystroke delay

### ISSUE THREAD

**Issue by akavenus** [ulixee/secret-agent#330]
There should be a option to set a custom keystroke delay when using secret agent. The default one is very slow

In puppeteer/playwright I can do this by adding {delay: delay} to the type command

ex: 
~ await agent.type('user', {delay: 5});

**Comment by blakebyrnes** [comment]
The best way to do this right now is to modify the default-human-emulator. You can load your own default human emulator if you want to override the provided example. We're going to eventually add variables to tweak some of the settings in the human emulator to adjust the speed it types and moves. You can also just ignore any human-like behavior by having a HumanEmulator plugin that just clears out the human emulator behavior

// core side (needs to be in same process as core - see (interact.test.ts)[https://github.com/ulixee/secret-agent/blob/e8e400b2d23092ccbcb652349f5053dd8fd5074d/full-client/test/interact.test.ts] for examples)
```
Core.use(class BasicHumanEmulator extends HumanEmulator {
  static id = 'basic';
})
```

// client side needs to then create an agent with the emulator: `new Agent({ humanEmulatorId: 'basic', connectionToCore: { host .. })`
