### ISSUE TITLE
Option for chrome exe path

### ISSUE THREAD

**Issue by akavenus** [ulixee/secret-agent#331]
There should be a option to set a custom path for browser to launch, in puppeteer/playwright it's executablePath

**Comment by blakebyrnes** [comment]
@akavenus we do allow you to specify the chrome path, but SecretAgent is doing work to mask browser differences from headed Chrome in each version. So you will want to make sure to align your emulator data with the version of Chrome you're using.

Secret Agent is built so you can roll your own "BrowserEmulator" altogether - your own dom polyfills, browser, devtools api calls, etc. (Check out CorePlugins/BrowserEmulators in docs if that's what you'd like to do)

Would love to understand better what you want to do with a custom path.

**Comment by blakebyrnes** [comment]
Within each chrome version installed (ie @secret-agent/chrome-88) you can override the chrome executablePath using CHROME_${major}_BIN (eg, CHROME_88_BIN)
