### ISSUE TITLE
Support media stream

### ISSUE THREAD

**Issue by merloisac** [ulixee/secret-agent#337]
I am trying to scrape some HTTP Live Streaming (HLS) Transmissions, but I couldn't find a way to do, is it supported by SA?

```typescript
import {Agent} from 'secret-agent';

(async () => {
    process.env.SA_SHOW_BROWSER = 'true';
    process.env.SA_SHOW_REPLAY = "true";
    const agent = new Agent({
        userAgent: 'chrome-latest',
    });

    await agent.goto(`https://hls-js.netlify.app/demo/`);
    await agent.waitForMillis(100000);

})();
```
`Status: Your Browser does not support MediaSourceExtension / MP4 mediasource`

**Comment by ctaity** [comment]
cannot get de m3u8 file? what protection have that server?

**Comment by merloisac** [comment]
I'm not sure what kind on protection it does have, but the m3u8 file keep loading forever when the request is made outside the initial browser

**Comment by ctaity** [comment]
can you share the m3u8 url?

**Comment by merloisac** [comment]
I can't send here cause there are some personal data on the URL I wouldn't mind to share on private

**Comment by blakebyrnes** [comment]
It looks like there's a bug in the "codecs" overrides. Will fix shortly - I need to figure out if we still even need these overrides now that we're running on full-chrome

**Comment by merloisac** [comment]
Re-opening it cause the same problem started to happen, the website I'm trying to scrape now is twitch.tv, the m3u8 is loading forever until it reaches timeout

```typescript
import {Agent} from 'secret-agent';

(async () => {
    process.env.SA_SHOW_BROWSER = "true";
    const agent = new Agent();
    await agent.goto(`https://player.twitch.tv/?channel=gaules&enableExtensions=true&muted=false&parent=twitch.tv&player=popout&volume=0.5&mature=true&quality=160p30`);
    const m3u8 = await agent.waitForResource({url:/m3u8/}, {timeoutMs: 120000});
    console.log(m3u8[0].url);
    await agent.waitForMillis(100000);

})();
```
