### ISSUE TITLE
WebRTC leaks real ip when using proxy

### ISSUE THREAD

**Issue by pashkasan** [ulixee/secret-agent#340]
tested on WSL Ubuntu20, here https://abrahamjuliot.github.io/creepjs/

**Comment by blakebyrnes** [comment]
Can you share a screenshot? Also, can you confirm your proxy is working on a whatsmyip type of site?

**Comment by pashkasan** [comment]
tested both headless/headfull
![code](https://user-images.githubusercontent.com/55329774/131899415-b688fabd-8433-4717-bfe7-3bf421d7b705.jpg)
![gogol](https://user-images.githubusercontent.com/55329774/131899416-793866b4-e49c-497a-862f-8245407dad61.jpg)
![screepjs](https://user-images.githubusercontent.com/55329774/131899419-6f4ebbdf-41ee-4156-b162-78dbde930f64.jpg)

**Comment by blakebyrnes** [comment]
Thanks. 👍  This is the flag turned on the default browser emulator: --force-webrtc-ip-handling-policy=default_public_interface_only

Reading up a bit, it sounds like some people have seen better results with --force-webrtc-ip-handling-policy=disable_non_proxied_udp

**Comment by pashkasan** [comment]
checked documentation, seems like there is no option yet to override browser launch flags?

**Comment by blakebyrnes** [comment]
You can't do it from the client options (clients share the same browser engine and create independent incognito windows), but you CAN do it by extending the default BrowserEmulator and overriding the launch options (https://github.com/ulixee/secret-agent/blob/424c445687e3458d7609c187974f0fce09802ab7/plugins/default-browser-emulator/index.ts#L157)

**Comment by pashkasan** [comment]
tested this flag and it also leak ip, maybe cause  of 88 engine, i will try on new versions and seems like "--force-webrtc-ip-handling-policy=default_public_interface_only" is correct, but not working as expected

**Comment by blakebyrnes** [comment]
@pashkasan I tested this flag as well and didn't see correct behavior: --enforce-webrtc-ip-permission-check. Did you test anything else?

**Comment by JokerGT** [comment]
Any news on this? How can we disable this or let WebRTC report the IP from the used proxy? Is there a way to tweak this somehow? Is it possible to add a chrome plugin which could fix this issue?
