### ISSUE TITLE
Missing iframes / unexpected behavior on first page goto of a session

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#343]
Attached a console log of the output of 4 runs of the following test script.

Run 1 & 2 with the reload() on line 17 uncommented. This produces expected results on all 3 page gotos, the only difference between the runs is the order of the ASINs/page URLs, to verify a similar number of iframes is returned for each URL no matter the order it is gone to during the session.

Run 3 & 4 is with reload() on line 17 commented out. In this case the first goto of each run of the script returns 0 usable iframes. It does actually return I think 1 iframe, but the check for a usable .name property of it on line 25 fails because the name property seems to be missing or something. So there appear to be iframes missing, and the 1 returned is missing info perhaps. The 2nd and 3rd gotos of the session are normal, only the 1st one is incorrect.

```
process.env.SA_SHOW_REPLAY = 'false';
process.env.SA_SHOW_BROWSER = 'false';
process.env.NODE_DISABLE_COLORS = 1;
process.env.NODE_ENV = 'dev';

import { Agent } from 'secret-agent'

var agent = await new Agent( { maxConcurrency: 1 } );

async function run() {
  let someASINs = ['B00D3OR58A', 'B079ZV4V3C', 'B08PW73XGF'];
  // let someASINs = ['B079ZV4V3C', 'B00D3OR58A', 'B08PW73XGF'];
  for (let anASIN of someASINs) {
    let href = `https://www.amazon.com/dp/${anASIN}/ref=sr_1_1?dchild=1&keywords=${anASIN}`;
    console.log(`Working on: ${href}`);
    await agent.goto(href);
    await agent.reload();
    console.log(`waitForPaintingStable 1`);
    await agent.waitForPaintingStable( { timeoutMs: 20000 } );
    let someIFrames = await agent.document.querySelectorAll(`iframe`);
    let framesWithNames = 0;
    let okAnchors = 0;
    for (let anIFrame of someIFrames) {
      let aName = await anIFrame.name;
      if (aName) {
        framesWithNames++;
      }
      let anIFrameEnvironment = await agent.mainFrameEnvironment.getFrameEnvironment(anIFrame);
      let someAnchors = await anIFrameEnvironment.document.querySelectorAll(`a`);
      if (someAnchors !== null) {
        for (let anAnchor of someAnchors) {
          okAnchors++;
        }
      }
    }
    console.log(`Found ${framesWithNames} iframes with names, and ${okAnchors} anchors within them`);
  }
  await agent.close();
}

run();
```

[iframes-test.debug.txt](https://github.com/ulixee/secret-agent/files/7124347/iframes-test.debug.txt)

**Comment by blakebyrnes** [comment]
I took a look at this and see what you're talking about now. I toyed with waiting for elements, but something is definitely stalling out loading that first page. That said, there are like 50 resources loaded for the page and a ton of frames. Can you think of any ideas to help try to narrow down what could be triggering that first ad frame to not load? It appears to load fine in regular Chrome (besides that first time it stalled for me) - so I'm not sure it's cookies or referer.

**Comment by A-Posthuman** [comment]
Not really sure what it could be, when I visit in regular chrome not only do I get the first ad iframe but 6 others (all ads I think). So it isn't just that an iframe stalling out but that I'm only getting 1 iframe found via querySelectorAll() instead of 6 or 7.
