### ISSUE TITLE
The example https://secretagent.dev/docs/plugins/client-plugins/#client-plugins dont work

### ISSUE THREAD

**Issue by ctaity** [ulixee/secret-agent#344]
i think the example is out of date. Thanks

**Comment by blakebyrnes** [comment]
Can you share a bit more about what's not working? Is it throwing an error, or just silently not working?

**Comment by ctaity** [comment]
Module '"@secret-agent/plugin-utils"' has no exported member 'ClientPlugin'.ts(2305)

![Screen Shot 2021-09-07 at 19 03 06](https://user-images.githubusercontent.com/5207990/132416549-b743d7f0-8b13-4de2-aeed-90b43f4b8662.png)
