### ISSUE TITLE
can't run the example in node.js 12.14.1

### ISSUE THREAD

**Issue by pydeveloper78** [ulixee/secret-agent#35]
My node.js version is 12.14.1. I just tried to install it and run the example script in the document, but I got such error.

2020-07-22T02:37:00.770Z ERROR UnhandledClientError {
  clientError: TypeError: SecretAgent.createBrowser is not a function
      at /media/mine/Work/fiverr/keadam/index.js:4:37
      at Object.<anonymous> (/media/mine/Work/fiverr/keadam/index.js:9:3)
      at Module._compile (internal/modules/cjs/loader.js:955:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
      at Module.load (internal/modules/cjs/loader.js:811:32)
      at Function.Module._load (internal/modules/cjs/loader.js:723:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
      at internal/main/run_main_module.js:17:11
}

**Comment by pydeveloper78** [comment]
2020-07-22T02:49:14.926Z ERROR UnhandledClientError {
  clientError: Error: Cannot find module '@secret-agent/replay-app'
  Require stack:
  - /media/mine/Work/fiverr/keadam/node_modules/@secret-agent/replay/index.js
  - /media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/lib/ScriptInstance.js
  - /media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/lib/Browser.js
  - /media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/index.js
  - /media/mine/Work/fiverr/keadam/node_modules/secret-agent/index.js
  - /media/mine/Work/fiverr/keadam/index.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
      at Function.resolve (internal/modules/cjs/helpers.js:80:19)
      at replay (/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/replay/index.js:13:17)
      at ScriptInstance.launchReplay (/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/lib/ScriptInstance.js:22:9)
      at Object.createBrowser (/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/lib/Browser.js:137:20)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
      at async /media/mine/Work/fiverr/keadam/index.js:4:19 {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/replay/index.js',
      '/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/lib/ScriptInstance.js',
      '/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/lib/Browser.js',
      '/media/mine/Work/fiverr/keadam/node_modules/@secret-agent/client/index.js',
      '/media/mine/Work/fiverr/keadam/node_modules/secret-agent/index.js',
      '/media/mine/Work/fiverr/keadam/index.js'
    ]
  }
}

**Comment by pydeveloper78** [comment]
There is my example code.

const SecretAgent = require('secret-agent').default;
    
(async () => {
  const browser = await SecretAgent.createBrowser();
  await browser.goto('https://example.org');
  const title = await browser.document.querySelector('title').textContent;
  const intro = await browser.document.querySelector('p:first-child').textContent;
  await browser.close();
})();

**Comment by blakebyrnes** [comment]
Hi @pydeveloper78, sorry you're running into this. Appears to be something with our new Replay app. 

Could you share your:
1) package.json 
2) what operating system you're using?

**Comment by pydeveloper78** [comment]
Hi @blakebyrnes,
Thank you for quick reply.

1. Yes, I attached my package.json. It's very basic.
[package.json.zip](https://github.com/ulixee/secret-agent/files/4960232/package.json.zip)

2. I am using ubuntu 16.04

**Comment by pydeveloper78** [comment]
![Selection_022](https://user-images.githubusercontent.com/39677652/88182207-977ce100-cc38-11ea-87ae-5fe472732251.jpg)
Really there is no @secret-agent/replay-app

**Comment by blakebyrnes** [comment]
Yeah, replay-app is a generator project to create an electron app to be able to visually see your scripts replaying. The @secret-agent/replay package tries to install a distributable version into /dist in it's project. If it can't find a a dist, it'll default to trying to launch the app from the monorepo (replay-app). We probably need to change the fallback behavior.

Could you do an ls inside the replay directory? It should have installed a /dist directory, but I'm guessing it either didn't translate ubuntu correctly to a Replay path.

**Comment by pydeveloper78** [comment]
![Selection_023](https://user-images.githubusercontent.com/39677652/88183530-3e15b180-cc3a-11ea-9c71-61e9a42337eb.jpg)

**Comment by blakebyrnes** [comment]
Interesting. Anything in the dist dir?

**Comment by pydeveloper78** [comment]
![Selection_024](https://user-images.githubusercontent.com/39677652/88183844-a5cbfc80-cc3a-11ea-830d-f9dbd2100f2d.jpg)

**Comment by blakebyrnes** [comment]
I think I have an idea what's going on. You can work around this by hiding replay using the env variable below. Should be able to get a fix up shortly. 

SA_SHOW_REPLAY=false

**Comment by pydeveloper78** [comment]
![Selection_025](https://user-images.githubusercontent.com/39677652/88184374-46bab780-cc3b-11ea-8969-9c871e14c6bd.jpg)

**Comment by blakebyrnes** [comment]
Let me pull down an ubuntu docker and dig in.

**Comment by pydeveloper78** [comment]
Ok, thank you

**Comment by blakebyrnes** [comment]
Didn't mean to auto-close this. Would you mind checking if this new version fixes your issues?

**Comment by pydeveloper78** [comment]
Thanks for the quick fix. I will check and get back to you.

**Comment by pydeveloper78** [comment]
![Selection_027](https://user-images.githubusercontent.com/39677652/88199810-f9941100-cc4d-11ea-82e8-848411285b7e.jpg)

**Comment by blakebyrnes** [comment]
Ok, good and bad. Good: looks like it's working! Bad, it appears you have a querySelector on line 7 that's broken. If I run your same query selector on example.org, it appears it's failing there too:

![image](https://user-images.githubusercontent.com/115056/88200212-d9dff700-cc13-11ea-9f83-e8b55b2bc334.png)

I'm gonna close this issue. Feel free to log anything else you encounter though.

**Comment by pydeveloper78** [comment]
Sorry there is such selector in this page. It seems to work now.
BTW the app isn't existed automatically. it's still waiting.

**Comment by pydeveloper78** [comment]
and another question. how can I see it works or not? ( non-headless)

**Comment by blakebyrnes** [comment]
Oh, hmm. Ok, I need to get a headed version of Ubuntu I can test Replay with. The Replay app should be giving you visual feedback that it's working, but need to figure out why it's not showing up for you. You could always log out to console your results. Is the app launching for you, but just pausing? Or is it not doing anything at all?

**Comment by pydeveloper78** [comment]
It's running on me, but didn't close automatically and it's in pause state now.

**Comment by blakebyrnes** [comment]
Can you drag the playbar back to the beginning?

**Comment by blakebyrnes** [comment]
Would you mind sending a screenshot?

**Comment by pydeveloper78** [comment]
![Selection_028](https://user-images.githubusercontent.com/39677652/88201743-83dd7480-cc50-11ea-97e7-8b4bbd6a6e22.jpg)
![Selection_029](https://user-images.githubusercontent.com/39677652/88201801-98217180-cc50-11ea-8036-16a7702eafee.jpg)

It's still running.

**Comment by blakebyrnes** [comment]
Oh, I misunderstood you. Are you not seeing any "desktop app" launched? It looks like your script completed but something is just keeping the process alive. Thanks, will look into this also.

**Comment by calebjclark** [comment]
@blakebyrnes I wonder if we should have browser.close() trigger a full SecretAgent.shutdown() unless:

A) another browser window is still open, or
B) SecretAgent.start() had been used.

Otherwise, it's going to hang without calling SecretAgent.shutdown(), but that seems overkill in the majority of use-cases.
