### ISSUE TITLE
trouble obtaining document outerHTML from cors protected iframes

### ISSUE THREAD

**Issue by andynuss** [ulixee/secret-agent#355]
I am using the recently improved plugin behavior to try to get the outerHTML for the main page and the two iframes that the main page contains.  The key to this bug is that the two iframes in the main page are in this case referring to a different domain than the main page, such that in the browser's dom, the main page does not have access to the frame windows' document outerHTML.

This is my plugin code:

    import ClientPlugin from '@secret-agent/plugin-utils/lib/ClientPlugin';
    import CorePlugin from '@secret-agent/plugin-utils/lib/CorePlugin';
    import { ISendToCoreFn } from '@secret-agent/interfaces/IClientPlugin';
    import { IOnClientCommandMeta } from '@secret-agent/interfaces/ICorePlugin';
    import { IPuppetPage } from '@secret-agent/interfaces/IPuppetPage';
    import { IPuppetFrame } from '@secret-agent/interfaces/IPuppetFrame';

    export class MyClientPlugin extends ClientPlugin {

      static readonly id = 'my-evaluate-plugin';
      static coreDependencyIds = [MyClientPlugin.id];

      public onAgent(agent, sendToCore: ISendToCoreFn): void {
        agent.execFunc = (funcName: string, frameIndex: number, evalFn: string, ...args:any[]) => {
          return this.execFunc(sendToCore, funcName, frameIndex, evalFn, args);
        };
      }

      public onTab(tab, sendToCore: ISendToCoreFn): void {
        tab.execFunc = (funcName: string, frameIndex: number, evalFn: string, ...args:any[]) => {
          return this.execFunc(sendToCore, funcName, frameIndex, evalFn, args);
        };
      }

      private async execFunc(
        sendToCore: ISendToCoreFn,
        funcName: string,
        frameIndex: number,
        evalFn: string,
        args:any[]
      ): Promise<any> {
        return await sendToCore(MyClientPlugin.id, funcName, frameIndex, evalFn, args);
      }
    }

    export class MyCorePlugin extends CorePlugin {

      static readonly id = 'my-evaluate-plugin';

      public async onClientCommand(
        { puppetPage }: IOnClientCommandMeta,
        funcName: string,
        frameIndex: number,
        callbackFuncStr: string,
        args: any[]
      ): Promise<any> {
        const page: IPuppetPage = puppetPage;
        const frames: IPuppetFrame[] = page.frames;

        if (funcName === 'numFrames') {
          return frames.length;
        }

        if (funcName === 'evaluate') {
          const frame: IPuppetFrame = frames[frameIndex];
          const expression: string = `((args) => {
            const fn = ${callbackFuncStr};
            return fn.apply(null, JSON.parse(args));
          })("${JSON.stringify(args)}")`;
          return frame.evaluate(expression, true);
        }

        throw new Error('invalid funcName: ' + funcName);
      }
    }

and this is how I use it:

    import { Agent, ConnectionFactory, ConnectionToCore, LocationStatus } from 'secret-agent';
    import Path from 'path';

    const ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.165 Safari/537.36';

    let sharedConnection: ConnectionToCore = null;

    function getConnection (): ConnectionToCore {
      if (sharedConnection !== null) return sharedConnection;
      sharedConnection = ConnectionFactory.createConnection({
        maxConcurrency: 4,
      });
      return sharedConnection;
    }

    export async function testUrl(requestUrl: string, imageName: string): Promise<void> {
      const myagent = new Agent({
        userAgent: ua,
        viewport: {
          screenHeight: 768,
          screenWidth: 1024,
          height: 768,
          width: 1024,
        },
        connectionToCore: getConnection(),
      });

      try {
        myagent.use(Path.resolve(__dirname, 'plugin'));
        await myagent.goto(requestUrl);
        await myagent.waitForPaintingStable();
        await myagent.activeTab.waitForLoad(LocationStatus.DomContentLoaded);

        // @ts-ignore
        let result = await myagent.execFunc('numFrames');
        console.log('result1', result);

        const callback = (a, b) => {
          // @ts-ignore
          return document.documentElement.outerHTML + '\n' + a + '\n' + b;
        };

        // @ts-ignore
        result = await myagent.execFunc('evaluate', 0, callback.toString(), 33, 123);
        console.log('result2', result);

        // @ts-ignore
        result = await myagent.execFunc('evaluate', 1, callback.toString(), 33, 123);
        console.log('result2', result);

        // @ts-ignore
        result = await myagent.execFunc('evaluate', 2, callback.toString(), 33, 123);
        console.log('result2', result);

      } finally {
        try {
          await myagent.close();
        } catch (e) {
          console.log('unexpected error closing new Agent', e);
        }
      }
    }

    (async () => {
      await testUrl('http://mylocaldomain.com/catchly/stagcore/test/corsframes.html', 'dummy');
    })();

The big question is whether or not it is currently possible to scrape frame content using the IPuppetFrame evaluate method, for all the cases of scraping iframes that reference cross-domain urls in their 'src' attribute.

What I am seeing is that it is not possible.

**Comment by blakebyrnes** [comment]
You are not restricted by CORs in those evaluate functions - it's the same behavior you can see in Chrome devtools when you select a different "context" from within the console (top left) and run commands from a chosen frame.

What error are you seeing? Did you try a version where you just "print" the functions you're trying to run? I don't think this will work in your core plugin: `return fn.apply(null, JSON.parse(args));`. I don't think the args are going to be json at that point.

```
public async onClientCommand(
    { puppetPage }: IOnClientCommandMeta,
    funcName: string,
    frameIndex: number,
    callbackFuncStr: string,
    args: any[]
  ): Promise<any> {
    const page: IPuppetPage = puppetPage;
    const frames: IPuppetFrame[] = page.frames;

    if (funcName === 'numFrames') {
      return frames.length;
    }

    if (funcName === 'evaluate') {
      const frame: IPuppetFrame = frames[frameIndex];
      const expression: string = `((args) => {
        const fn = ${callbackFuncStr};
        return fn.apply(null, JSON.parse(args));
      })("${JSON.stringify(args)}")`;
     console.log('Running expression', expression);
      return frame.evaluate(expression, true);
    }

    throw new Error('invalid funcName: ' + funcName);
  }
```

**Comment by andynuss** [comment]
My test program called my 'evaluate' (funcName) 3 times for index 0 (apparently the main page), index 1 (the first real iframe, in this case CORS relative to main page), and index 2 (the second and last real iframe, in this case also CORS relative to main page).  This is my output:

    result2 <html><head></head><body>
            <iframe src="https://iframeserver-test.widdix.perm.io/stagcore/test/frame1.html"></iframe>
            <iframe src="https://iframeserver-test.widdix.perm.io/stagcore/test/frame2.html"></iframe>
    
    </body></html>
    33
    123
    result2 <html><head></head><body></body></html>
    33
    123
    result2 <html><head></head><body></body></html>
    33
    123

as you can see, the main frame evaluate worked.  It did get the outerHTML.  However, for the other two frames, the output makes it appear that the iframe html is an empty body, which is not in fact the case for my test CORS frames, but is the behavior the browser gives when embedding javascript in a main page and trying to get the outerHTML of a CORS protected iframe contentWindow.

**Comment by blakebyrnes** [comment]
@andynuss Is it possible those frames just haven't loaded yet? waitForPaintingStable is only running on your main frame (the way you've done it). You can't use waitForPaintingStable on the subframes, but you could do a waitForLoad();

**Comment by blakebyrnes** [comment]
You could also try just waiting a bit

**Comment by andynuss** [comment]
I did see that my JSON stringify/parse to attach extra args to the function is working with numbers, but not with strings, because I am not yet escaping the double-quotes.  But otherwise, the test code is in fact trying to use IPuppetPage to get access to the CORS IPuppetFrame(s), and then calling evaluate on them with a javascript snippet that essentially returns document.documentElement.outerHTML.

I am able to do this kind of thing with puppeteer.  But with secret-agent, it appears that the evaluation of "document.documentElement.outerHTML" in the CORS iPuppetFrame is being restricted by the browser enforced security for the main page, and its ability to access to CORS iframe dom.

Do you see what I mean?

**Comment by blakebyrnes** [comment]
Puppeteer does a bunch of stuff to wait for all subframes to fully load if you say waitForLoad. Could be part of what you're seeing.

I would guess Chrome would throw an error if there was actually a CORs violation.

**Comment by andynuss** [comment]
You are absolutely right.  It was due to not waiting long enough.  I added a delay of 10 secs, and though I got a visible warning from secret-agents' little ui that my script appeared hung, waiting that extra time allowed the evaluate function to get all the data.

BTW, I would have thought waiting for the dom to load would include all frames, just as when the document.body tag's onload attribute only fires when all iframes are done.  I.e. why isn't this working for me?  If not a bug, what is the correct way for me to wait?

    await myagent.activeTab.waitForLoad(LocationStatus.DomContentLoaded);

**Comment by andynuss** [comment]
Oh, I see, there is a waitForLoad on the IPuppetFrame interface.  This seems resolved.

**Comment by blakebyrnes** [comment]
Ok, cool. Was writing back that you can try using agent.activeTab.waitForLoad(LocationStatus.AllContentLoaded), but I'm not sure it's actually the dom behavior to trigger load when all frames have also triggered their own load event. Puppeteer has that functionality, but they're working around the default dom behavior by waiting for each frame to load or fail (last time I looked).

In any case, best approach is to wait for load of specific frames - SecretAgent has taken the stance that for the majority of cases, you don't care about the frames loading.

**Comment by andynuss** [comment]
One last problem: I mentioned above that I hadn't yet solved passing string arguments into the evaluate function, because using simple idea of JSON.parse and JSON.stringify there are double-quote escaping needs that I didn't want to figure out.

I noticed in your example code this file: TypeSerializer.test.ts and thought maybe that would work for me as follows:

    public async onClientCommand(
      { puppetPage }: IOnClientCommandMeta,
      funcName: string,
      frameIndex: number,
      callbackFuncStr: string,
      args: any[]
    ): Promise<any> {
      const page: IPuppetPage = puppetPage;

      if (funcName === 'numFrames') {
        return page.frames.length;
      }

      if (funcName === 'evaluate') {
        const frame: IPuppetFrame = await this.getAwaitedFrame(page, frameIndex);
        if (!frame) return null;
        const rawIn: string = TypeSerializer.stringify(args);
        const expression: string = `((args) => {
          args = TypeSerializer.parse(JSON.stringify(args));
          const fn = ${callbackFuncStr};
          const result = fn.apply(null, JSON.parse(args));
          return TypeSerializer.stringify(result);
        })(${rawIn})`;
        const rawOut: string = await frame.evaluate(expression, true);
        return TypeSerializer.parse(rawOut);
      }

      throw new Error('invalid funcName: ' + funcName);
    }

Though your jest test works obviously, and in it, you are able to use static TypeSerializer methods INSIDE the evaluate function, for me, I am getting the following exception on the first use of TypeSerializer inside the evaluate call:

    2021-09-24T16:37:05.884Z ERROR [/Users/andynuss/repos/stag-secret-agent/app/node_modules/@secret-agent/core/index] UnhandledErrorOrRejection {
      clientError: 'Error: Uncaught',
      context: {},
      sessionId: null,
      sessionName: undefined
    } ReferenceError: TypeSerializer is not defined
        at <anonymous>:2:9
        at <anonymous>:9:9
    ------REMOTE CORE---------------------------------
        at Function.reviver (/Users/andynuss/repos/stag-secret-agent/app/node_modules/commons/TypeSerializer.ts:208:26)
        at JSON.parse (<anonymous>)
        at Function.parse (/Users/andynuss/repos/stag-secret-agent/app/node_modules/commons/TypeSerializer.ts:24:17)
        at WebSocket.<anonymous> (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/connections/RemoteConnectionToCore.ts:67:42)
        at WebSocket.emit (events.js:315:20)
        at Receiver.receiverOnMessage (/Users/andynuss/repos/stag-secret-agent/app/node_modules/ws/lib/websocket.js:983:20)
        at Receiver.emit (events.js:315:20)
        at Receiver.dataMessage (/Users/andynuss/repos/stag-secret-agent/app/node_modules/ws/lib/receiver.js:517:14)
        at Receiver.getData (/Users/andynuss/repos/stag-secret-agent/app/node_modules/ws/lib/receiver.js:435:17)
        at Receiver.startLoop (/Users/andynuss/repos/stag-secret-agent/app/node_modules/ws/lib/receiver.js:143:22)
    ------CONNECTION----------------------------------
        at new Resolvable (/Users/andynuss/repos/stag-secret-agent/app/node_modules/commons/Resolvable.ts:17:18)
        at Object.createPromise (/Users/andynuss/repos/stag-secret-agent/app/node_modules/commons/utils.ts:68:10)
        at RemoteConnectionToCore.createPendingResult (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/connections/ConnectionToCore.ts:328:31)
        at RemoteConnectionToCore.internalSendRequestAndWait (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/connections/ConnectionToCore.ts:253:43)
        at RemoteConnectionToCore.sendRequest (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/connections/ConnectionToCore.ts:156:17)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at Object.cb (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/lib/CoreCommandQueue.ts:104:26)
        at Queue.next (/Users/andynuss/repos/stag-secret-agent/app/node_modules/commons/Queue.ts:82:19)
    ------CORE COMMANDS-------------------------------
        at Queue.run (/Users/andynuss/repos/stag-secret-agent/app/node_modules/commons/Queue.ts:35:19)
        at CoreCommandQueue.run (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/lib/CoreCommandQueue.ts:100:8)
        at SessionConnection.sendToActiveTab (/Users/andynuss/repos/stag-secret-agent/app/node_modules/client/lib/Agent.ts:584:33)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at MyClientPlugin.execFunc (/Users/andynuss/repos/stag-secret-agent/app/src/plugin.js:22:16)
        at testUrl (/Users/andynuss/repos/stag-secret-agent/app/src/test.js:46:18)
        at /Users/andynuss/repos/stag-secret-agent/app/src/test.js:68:5

    --------------------------------------------------
    ------default-session-2---------------------------
    ------a686cac0-1d55-11ec-8145-97d94c6223aa--------
    -------------------------------------------------- {
      message: 'Uncaught'

**Comment by blakebyrnes** [comment]
TypeSerializer isn't available globally in the environment - it's just wrapped in with the default scripts. I don't think you need it though.

This is a simpler way to do what you're wanting to do:
```
const expresssion = `${fnName}(${args
      .map(x => {
        if (!x) return 'undefined';
        return JSON.stringify(x);
      })
      .join(', ')})`;
```
