### ISSUE TITLE
custom chrome launch arguments

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#358]
What would be the best way to add them?

e.g. I would love to add --mute-audio to some of sessions

**Comment by blakebyrnes** [comment]
The best way atm is to create your own BrowserEmulator. You can do a really simple one that extends the default one and overrides `onBrowserWillLaunch`(https://github.com/ulixee/secret-agent/blob/0d2fa8cdd4309cf860d0149363dd70e1e0cfbdd6/plugins/default-browser-emulator/index.ts#L149)

**Comment by janisblaus** [comment]
That will do! :)
