### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by spignataro** [ulixee/secret-agent#372]
Another super secret link

https://github.com/ulixee/secret-agent/projects/1

Mouse over the version number and click "Roadmap". It takes you to a dead link. Maybe a roadmap to nowhere?

**Comment by blakebyrnes** [comment]
Haha. I deleted that because we weren't updating it and it seemed silly to leave it up. Guess I forgot to update the site.

Thanks

**Comment by spignataro** [comment]
Welcome
