### ISSUE TITLE
how to set specific user agent (android/ios)

### ISSUE THREAD

**Issue by kenobikdi** [ulixee/secret-agent#381]
Tried options like this in new object Agent, configs:

'Mozilla/5.0 (Linux; Android 9; LM-G710 Build/PKQ1.181105.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile Safari/537.36'

if create new Agent() i was taken  error - "TypeError: Cannot read property 'android' of undefined"
if add configuration after create Agent - nothing happened

**Comment by blakebyrnes** [comment]
We don't have any mobile browser emulators at the moment. We will likely add some ability to use an arbitrary UserAgent string, but it would increase your detection surface area.
