### ISSUE TITLE
Problem with Dialog

### ISSUE THREAD

**Issue by luka-dev** [ulixee/secret-agent#397]
Hi, when i maked a test scenarion based on [Headless Detector](https://infosimples.github.io/detect-headless/), i faced problem with Dialog.
I when i try `dismiss` dialog, script freezing and crash into a timeout in while.

Error Message
``` UnhandledRejection (Client) { context: {}, sessionId: null, sessionName: undefined } TimeoutError: undefined```

Script
```js
import {Handler} from 'secret-agent';

function randomInt(min: number, max: number) {
    return Math.random() * (max - min) + min;
}

(async () => {
    const handler = new Handler();

    const agent = await handler.createAgent();

    agent.activeTab.on('dialog', async (dialog) => {
        dialog.dismiss(true);
        console.log('dialog');
    });

    await agent.goto('https://infosimples.github.io/detect-headless/');

    console.log('goto');

    await agent.interact({
        move: [randomInt(1, 1000), randomInt(1, 1000)]
    }, {
        move: [randomInt(1, 1000), randomInt(1, 1000)]
    });

    console.log('interact');

    console.log(await agent.document.title);

    await handler.close();
})();
```
In a test run, i see in log ```goto```, ```dialog``` and after mentioned error, without ```interact``` and title output.
Am i wrong in my actions? Or it's a problem on SecretAgent side?

**Comment by blakebyrnes** [comment]
Poked around here a bit. This is interesting - the dialog is blocking DOMContentLoaded from firing, and interact has an implicit waitFor("DOMContentLoaded"), so it's hanging in this setup. I can get this to move forward if I wait for the dialog before calling interact

```
 const gotDialog = new Promise<void>(resolve => {
    agent.activeTab.on('dialog', async dialog => {
      console.log('got dialog');
      await dialog.dismiss(true);
      resolve();
      console.log('dialog');
    });
  });

  await agent.goto('https://infosimples.github.io/detect-headless/');
  await gotDialog;
  console.log('goto');
```

**Comment by luka-dev** [comment]
Thank you for help with 'bypassing' dialog))
I've think, this strange behavior should be noted at DOCS to prevent same issues (or make bypass on the SecretAgent side).

**Comment by blakebyrnes** [comment]
I do think we want to fix SA to address this potentially getting stuck in this scenario.
