### ISSUE TITLE
Defaulting to random emulatorID causes inconsistant results

### ISSUE THREAD

**Issue by calebjclark** [ulixee/secret-agent#4]
By default SA should use a consistent emulatorID on every run. To randomly cycle through emulators, the user must explicitly set a `default` flag.

Proposal:

> If emulatorId is null or undefined when calling SecretAgent.createBrowser() then default emulatorId will be used (for now, it will be chrome-80).

> If emulatorId is set to "random" then a random emulator will be picked.

> If emulatorId is set to a valid/known emulator then use that.

> Otherwise (if emulatorId is invalid/unknown) then throw an error.

**Comment by blakebyrnes** [comment]
I wonder if this shouldn't evolve into looking a bit like Browserlist:
- Defaults
- Top 3 Browsers
- Last 3 versions Chrome, Last 2 versions Safari

**Comment by calebjclark** [comment]
@blakebyrnes v2?

**Comment by blakebyrnes** [comment]
For sure. Just wondering where an api like this goes.
