### ISSUE TITLE
Small issue with indexedb

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#402]
Hi, 

Sometimes indexedb does not get exported correctly or something goes wrong and json dump with all storage gets corrupted. 

Problem starts here 

https://github.com/ulixee/secret-agent/blob/92c89af44b0fcb2c5ac346f5e113f4f8a2f59659/core/injected-scripts/domStorage.ts#L102

![image](https://user-images.githubusercontent.com/1029697/146378672-c11b0d51-0796-4cb1-9b44-f00e9d892312.png)

I've solved it by adding a check if restoreDB is set and name property exists. 

```
async function restoreIndexedDb(restoreDBs) {
    if (!restoreDBs || !restoreDBs.length)
        return;
    for (const restoreDB of restoreDBs) {
        await new Promise((resolve, reject) => {

            if( !indexedDB || !indexedDB.hasOwnProperty('name') ){
                resolve();
            }
```

Hope this helps, unfortunately I don't know when and why this issue happens as it seems to be random.

**Comment by blakebyrnes** [comment]
Thanks @janisblaus. Do you happen to have a copy of what it was trying to restore? Can send privately on discord if you don't want to post on here.
