### ISSUE TITLE
Can't connect with upstream proxy using brightdata service, Error: connection refused (403)

### ISSUE THREAD

**Issue by johnHastings772** [ulixee/secret-agent#422]
Can't connect with upstream proxy using brightdata service Error: connection refused (403)

Hi! You have a really nice project here. I've been testing it for a few days, coming from using Selenium I find it awesome, wish I'd have found it much earlier.

Sadly I can't get it to work with brightdata's residential proxy service, I've tested it with Selenium plus curl and it works just fine. Maybe it's due to the way the mitm-socket module works or maybe the problem comes from brightdata side... not sure at all.

Thanks for your time and the whole project!

Os: Ubuntu 20.04.3 LTS (Under WSL)
Nodejs version: v17.3.1
Go version: go1.13.8 linux/amd64

Used code:

```
import { Agent} from 'secret-agent';
(async () => {
    const agent = new Agent({
        upstreamProxyUrl: 'http://lum-customer-id-zone-residential:pass@zproxy.lum-superproxy.io:22225',
    })
    await agent.goto('https://nowsecure.nl');
})();
```

log:

> node:internal/process/promises:246
>           triggerUncaughtException(err, true /* fromPromise */);
>           ^
> Error: connection refused (403)
>     at buildConnectError (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:245:13)
>     at MitmSocket.triggerConnectErrorIfNeeded (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:189:7)
>     at MitmSocket.onError (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:212:12)
>     at MitmSocket.onMessage (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:165:12)
>     at MitmSocketSession.onMessage (/home/jhast/secret_agent/node_modules/mitm-socket/lib/MitmSocketSession.ts:51:41)
>     at MitmSocketSession.onIpcData (/home/jhast/secret_agent/node_modules/mitm-socket/lib/BaseIpcHandler.ts:154:10)
>     at Socket.emit (node:events:390:28)
>     at addChunk (node:internal/streams/readable:324:12)
>     at readableAddChunk (node:internal/streams/readable:297:9)
>     at Socket.Readable.push (node:internal/streams/readable:234:10)
> ------DIAL----------------------------------------
>     at new MitmSocket (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:59:22)
>     at MitmRequestAgent.createSocketConnection (/home/jhast/secret_agent/node_modules/mitm/lib/MitmRequestAgent.ts:145:24)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Object.lookupPublicIp [as default] (/home/jhast/secret_agent/plugins/default-browser-emulator/lib/helpers/lookupPublicIp.ts:20:21)
>     at DefaultBrowserEmulator.onHttpAgentInitialized (/home/jhast/secret_agent/plugins/default-browser-emulator/index.ts:121:44)
>     at async Promise.all (index 0)
>     at CorePlugins.onHttpAgentInitialized (/home/jhast/secret_agent/node_modules/core/lib/CorePlugins.ts:141:5)
>     at Session.initialize (/home/jhast/secret_agent/node_modules/core/lib/Session.ts:270:5)
>     at Function.createSessionNow (/home/jhast/secret_agent/node_modules/core/lib/GlobalPool.ts:152:7)
>     at ConnectionToClient.createSession (/home/jhast/secret_agent/node_modules/core/server/ConnectionToClient.ts:212:21)
> ------REMOTE CORE---------------------------------
>     at Function.reviver (/home/jhast/secret_agent/node_modules/commons/TypeSerializer.ts:208:26)
>     at JSON.parse (<anonymous>)
>     at Function.parse (/home/jhast/secret_agent/node_modules/commons/TypeSerializer.ts:24:17)
>     at WebSocket.<anonymous> (/home/jhast/secret_agent/node_modules/client/connections/RemoteConnectionToCore.ts:67:42)
>     at WebSocket.emit (node:events:390:28)
>     at Receiver.receiverOnMessage (/home/jhast/secret_agent/node_modules/ws/lib/websocket.js:1008:20)
>     at Receiver.emit (node:events:390:28)
>     at Receiver.dataMessage (/home/jhast/secret_agent/node_modules/ws/lib/receiver.js:517:14)
>     at /home/jhast/secret_agent/node_modules/ws/lib/receiver.js:468:23
>     at /home/jhast/secret_agent/node_modules/ws/lib/permessage-deflate.js:308:9
> ------CONNECTION----------------------------------
>     at new Resolvable (/home/jhast/secret_agent/node_modules/commons/Resolvable.ts:17:18)
>     at Object.createPromise (/home/jhast/secret_agent/node_modules/commons/utils.ts:68:10)
>     at RemoteConnectionToCore.createPendingResult (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:357:31)
>     at RemoteConnectionToCore.internalSendRequestAndWait (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:263:43)
>     at RemoteConnectionToCore.sendRequest (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:164:17)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at CoreCommandQueue.sendRequest (/home/jhast/secret_agent/node_modules/client/lib/CoreCommandQueue.ts:145:22)
>     at Object.cb (/home/jhast/secret_agent/node_modules/client/lib/CoreCommandQueue.ts:112:16)
>     at Queue.next (/home/jhast/secret_agent/node_modules/commons/Queue.ts:82:19)
> ------CORE COMMANDS-------------------------------
>     at Queue.run (/home/jhast/secret_agent/node_modules/commons/Queue.ts:35:19)
>     at CoreCommandQueue.run (/home/jhast/secret_agent/node_modules/client/lib/CoreCommandQueue.ts:109:8)
>     at RemoteConnectionToCore.createSession (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:205:51)
>     at SessionConnection.getCoreSessionOrReject (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:559:36)
>     at SessionConnection.get activeTab [as activeTab] (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:480:10)
>     at Agent.get activeTab [as activeTab] (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:152:37)
>     at Agent.goto (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:365:17)
>     at file:///home/jhast/secret_agent/min_test.js:6:17
>     at file:///home/jhast/secret_agent/min_test.js:7:3
>     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
> 
> Node.js v17.3.1

debug log:

> 2022-01-13T10:26:59.336Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/core/index] Core.start { options: { isPersistent: false }, context: {} }
> 2022-01-13T10:26:59.343Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/core/lib/GlobalPool] StartingGlobalPool { context: {} }
> 2022-01-13T10:26:59.421Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/core/index] Core started {
>   coreHost: 'ws://localhost:37537',
>   sessionsDir: '/tmp/.secret-agent',
>   context: {}
> }
> 2022-01-13T10:26:59.432Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/CertificateGenerator] CertsIpcHandler.stdout: SessionArgs main.SessionArgs{IpcSocketPath:"/tmp/sa-ipc-certs-57154360-745b-11ec-a3c2-cd16aef76498.sock", RejectUnauthorized:false, ClientHelloId:"", TcpTtl:0, TcpWindowSize:0, Debug:true, Mode:"certs"}
>  { context: {} }
> 2022-01-13T10:26:59.433Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/CertificateGenerator] CertificateGenerator.onMessage {
>   privateKey: '-----BEGIN RSA PRIVATE KEY-----\n' +
>     'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDpJwsD0nlmidbB\n' +
>     'AB8nnLHe288baLsBOqa6gMlqyMUAX4wyiBL76kosNqGXZTW0fhqLXHRBRO06vWc9\n' +
>     'QJTbZ65wY9Jk6SLuYg9iIkls2M8zJwbprJRfQ/7LFX9cqzt3BmZJUhdjSTKqaOmA\n' +
>     'UbPAJ6kR/uatfmgkQ8H0qH19LUCq40DtQc3Q9jIuT8yeJYBKM+ZD7mnHaoENO4zL\n' +
>     '7+lfBkND1rh06PVvFcCJ5HzPpiMuL3KEQ6EKOqsDPg/fI0W98agj4cLtkNQhzyO2\n' +
>     'ODCWREKksEIA0rUqAH1VzLnoDPMaXGF1mJDoOsjU2T9mNj+cAucpFwPAf2OYYBuA\n' +
>     'sOnrG9vxAgMBAAECggEAZi44Q5qQngG23qrg/IlN4u/OmqKRon5D5+TdYTFQNVOq\n' +
>     'q9K7DzClBS+ELkeq+8lwdLc2NAyzM1Ui09Nj6axM5PC6moMaTgMn3shMCaoTVMW7\n' +
>     '39lExWOVXQe047Yfv5BMb8HMgjToQYrtGtGzx3kaPcrK6ipGFe6kKEdXh+63MqzD\n' +
>     '9mWm5bN6ek6HbbK79P15eqibex45YJIqPzpa7ZuGYpA/zy6EtiRjnctalcwBtr3d\n' +
>     'CMNQ/vS32udpSBkbw8bKSIsXs80zBjXVXrPA9OVHMzUCMIyJ/1inU2pLhgDU6KUt\n' +
>     'QRLnkZ0PNVerfI4F2ltZKARt9/Gm7kAIu4yzGyHS4QKBgQDx8UXv+W9hCypBY8PS\n' +
>     '+5w3spRZBkjFI4LMz1N8H1cREfZCkZbBEnLGQbp3jPs6PXWOwkSOedpYLNvBoDi9\n' +
>     'VvT0Ik/+09AFQLyhzrHsi6D1OJZR2ND7K2euV/GgtFiL1WaHAiDUsyye1rkuB+p2\n' +
>     'xAP9P2N9JIPcIOi7w7vu1jpBXQKBgQD2swZ2J0t9f9VLFn8KITZiEzIv89TqydW+\n' +
>     '4w+Zeb1ivAFYo/bh8jSMIg+rlckFwiaBfre8GuxEyzs/QigxwoBLaKUtKM7iIvez\n' +
>     'Zw9VWEk+jQ9RtFO0JgpIguCUm+40hfQSVWA8FjXtOFZbztYX4Y7BqtUcOFaYPepK\n' +
>     'MKvDaYv3pQKBgF9aTMsATqI7iULOM+5iFbZp3kebz3BKx5E6oNeJboIexySDRpv/\n' +
>     'TlbOrtPRL25LrJo//E7+vUwFGfMc11/f9piFMWvoRNLdKbrHwJ3Ohfg/fhbx0aM7\n' +
>     '/xfaNzO0ADXUPB03fIL3vr03OTJoEkMOi9fydJ5slr9aBP+Da/z8V2dNAoGAB5Ho\n' +
>     'wdlk1J4Gkn5HOa1ZONsz8ArAXtAAshHPmbsFl7EDLZAidD51ZFNrPa2j9HxHqDOW\n' +
>     'ObxtwZKm58ME7rn0K9wzLVaSOpguF6Ay9UB3RucXMD+jTeTY7e6uK4E5Zv0xRxq9\n' +
>     'kDpyPyw6YijPov313nV6gpor9hH4TXx+2Mk1VU0CgYEAwQi98ipGa4xiploQ60cK\n' +
>     'v13sZv2vq9r6O7SgcRLaV7Y9yoWb3OVyrU3rRbKCY5iQwHogrjfwxrzbc+1+48Ba\n' +
>     'zFcQIMdyJRJ08gAuuSzRGTUB+6MwprmZcwd+qom/j3p1TxAAsbxjnoB9b3wZFUVc\n' +
>     'DFAB89XtbGnmhQX+EBCaycc=\n' +
>     '-----END RSA PRIVATE KEY-----\n',
>   status: 'init',
>   context: {}
> }
> 2022-01-13T10:26:59.449Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/client/connections/ConnectionToCore] Overriding max concurrency with Core value { maxConcurrency: 10, context: {} }
> 2022-01-13T10:26:59.453Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/core/lib/GlobalPool] AcquiringChrome { maxConcurrentAgentsCount: 10, context: {} }
> 2022-01-13T10:26:59.685Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/index] Puppet.Starting { name: 'chrome', fullVersion: '88.0.4324.182', context: {} }
> 2022-01-13T10:26:59.692Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/lib/BrowserProcess] chrome.LaunchProcess {
>   executablePath: '/home/jhast/.cache/secret-agent/chrome/88.0.4324.182/chrome',
>   launchArguments: [
>     '--proxy-bypass-list=<-loopback>',
>     '--proxy-server=localhost:40145',
>     '--remote-debugging-pipe',
>     '--ignore-certificate-errors',
>     '--headless',
>     '--disable-background-networking',
>     '--enable-features=NetworkService,NetworkServiceInProcess',
>     '--disable-background-timer-throttling',
>     '--disable-backgrounding-occluded-windows',
>     '--disable-breakpad',
>     '--disable-client-side-phishing-detection',
>     '--disable-domain-reliability',
>     '--disable-default-apps',
>     '--disable-dev-shm-usage',
>     '--disable-extensions',
>     '--disable-features=PaintHolding,TranslateUI,site-per-process,OutOfBlinkCors,DestroyProfileOnBrowserClose',
>     '--disable-blink-features=AutomationControlled',
>     '--disable-hang-monitor',
>     '--disable-ipc-flooding-protection',
>     '--disable-prompt-on-repost',
>     '--disable-renderer-backgrounding',
>     '--disable-sync',
>     '--force-color-profile=srgb',
>     '--use-gl=any',
>     '--disable-partial-raster',
>     '--disable-skia-runtime-opts',
>     '--incognito',
>     '--use-fake-device-for-media-stream',
>     '--no-default-browser-check',
>     '--metrics-recording-only',
>     '--no-first-run',
>     '--enable-auto-reload',
>     '--password-store=basic',
>     '--use-mock-keychain',
>     '--allow-running-insecure-content',
>     '--window-size=1440,900',
>     '--force-webrtc-ip-handling-policy=default_public_interface_only',
>     '--no-startup-window',
>     '--hide-scrollbars',
>     '--mute-audio',
>     '--blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4'
>   ],
>   context: {}
> }
> 2022-01-13T10:26:59.701Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/MitmSocketSession] ProxyIpcHandler.stdout: SessionArgs main.SessionArgs{IpcSocketPath:"/tmp/sa-ipc-proxy-57481330-745b-11ec-a3c2-cd16aef76498.sock", RejectUnauthorized:false, ClientHelloId:"chrome-88", TcpTtl:64, TcpWindowSize:65535, Debug:true, Mode:"proxy"} { context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' } }
> 2022-01-13T10:26:59.750Z WARN [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/lib/BrowserProcess] chrome.stderr {
>   message: '[0113/112659.749220:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> }
> 2022-01-13T10:26:59.751Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/puppet-chrome/lib/Browser] Browser.create {
>   protocolVersion: '1.3',
>   product: 'HeadlessChrome/88.0.4324.182',
>   revision: '@73ee5087001dcef33047c4ed650471b225dd8caf',
>   userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.182 Safari/537.36',
>   jsVersion: '8.8.278.17',
>   executablePath: '/home/jhast/.cache/secret-agent/chrome/88.0.4324.182/chrome',
>   desiredFullVersion: '88.0.4324.182',
>   context: {}
> }
> 2022-01-13T10:26:59.754Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/index] Puppet.Started { context: {} }
> 2022-01-13T10:26:59.767Z WARN [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/lib/BrowserProcess] chrome.stderr {
>   message: '[0113/112659.761340:ERROR:vaapi_wrapper.cc(549)] Could not get a valid VA display',
>   context: {},
>   sessionId: null,
>   sessionName: undefined
> }
> 2022-01-13T10:27:00.049Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/MitmSocketSession] ProxyIpcHandler.stdout: [id=1] Serving at socket path /tmp/sa-5724fad0-745b-11ec-a3c2-cd16aef76498-1.sock. ConnectArgs main.ConnectArgs{Id:1, SocketPath:"/tmp/sa-5724fad0-745b-11ec-a3c2-cd16aef76498-1.sock", Host:"api.ipify.org", Port:"80", IsSsl:false, Servername:"api.ipify.org", ProxyUrl:"http://lum-customer-id-zone-residential:pass@zproxy.lum-superproxy.io:22225", KeepAlive:false, IsWebsocket:false, KeylogPath:""}
> Dialing proxy connect zproxy.lum-superproxy.io:22225 to api.ipify.org:80
>  { context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' } }
> 2022-01-13T10:27:01.532Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/MitmSocketSession] MitmSocketSession.onMessage {
>   error: 'HTTP_PROXY_ERR connection refused (403)\n',
>   'error-step': 'dial',
>   id: 1,
>   status: 'error',
>   context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' }
> }
> 2022-01-13T10:27:01.532Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/index] MitmSocket.error {
>   message: 'HTTP_PROXY_ERR connection refused (403)\n',
>   host: 'api.ipify.org',
>   context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' }
> }
> 2022-01-13T10:27:01.534Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/index] MitmSocket.Closing { context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' } }
> 2022-01-13T10:27:01.535Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/index] MitmSocket.Closed { context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' } }
> 2022-01-13T10:27:01.535Z WARN [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/index] MitmSocket.SocketError {
>   socketPath: '/tmp/sa-5724fad0-745b-11ec-a3c2-cd16aef76498-1.sock',
>   host: 'api.ipify.org',
>   context: { sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498' },
>   sessionId: '5724fad0-745b-11ec-a3c2-cd16aef76498',
>   sessionName: 'default-session-2'
> } HttpProxyConnectError: connection refused (403)
>     at buildConnectError (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:245:13)
>     at MitmSocket.cleanupSocket (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:221:11)
>     at MitmSocket.close (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:109:10)
>     at MitmSocket.onError (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:214:10)
>     at MitmSocket.onMessage (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:165:12)
>     at MitmSocketSession.onMessage (/home/jhast/secret_agent/node_modules/mitm-socket/lib/MitmSocketSession.ts:51:41)
>     at MitmSocketSession.onIpcData (/home/jhast/secret_agent/node_modules/mitm-socket/lib/BaseIpcHandler.ts:154:10)
>     at Socket.emit (node:events:390:28)
>     at addChunk (node:internal/streams/readable:324:12)
>     at readableAddChunk (node:internal/streams/readable:297:9)
> ------DIAL----------------------------------------
>     at new MitmSocket (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:59:22)
>     at MitmRequestAgent.createSocketConnection (/home/jhast/secret_agent/node_modules/mitm/lib/MitmRequestAgent.ts:145:24)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Object.lookupPublicIp [as default] (/home/jhast/secret_agent/plugins/default-browser-emulator/lib/helpers/lookupPublicIp.ts:20:21)
>     at DefaultBrowserEmulator.onHttpAgentInitialized (/home/jhast/secret_agent/plugins/default-browser-emulator/index.ts:121:44)
>     at async Promise.all (index 0)
>     at CorePlugins.onHttpAgentInitialized (/home/jhast/secret_agent/node_modules/core/lib/CorePlugins.ts:141:5)
>     at Session.initialize (/home/jhast/secret_agent/node_modules/core/lib/Session.ts:270:5)
>     at Function.createSessionNow (/home/jhast/secret_agent/node_modules/core/lib/GlobalPool.ts:152:7)
>     at ConnectionToClient.createSession (/home/jhast/secret_agent/node_modules/core/server/ConnectionToClient.ts:212:21)
> 2022-01-13T10:27:01.545Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/commons/ShutdownHandler] ShutdownHandler.onSignal { signal: 'exit', context: {} }
> 2022-01-13T10:27:01.545Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/commons/ShutdownHandler] ShutdownHandler.execute {
>   signal: 'exit',
>   fn: '() => connection.disconnect()',
>   callsite: 'at Function.client_1.ConnectionFactory.createLocalConnection (/home/jhast/secret_agent/full-client/index.ts:23:19)',
>   context: {}
> }
> 2022-01-13T10:27:01.546Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/client/connections/ConnectionToCore] ConnectionToCore.Disconnecting { host: {}, context: {} }
> 
> node:internal/process/promises:246
>           triggerUncaughtException(err, true /* fromPromise */);
>           ^
> Error: connection refused (403)
>     at buildConnectError (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:245:13)
>     at MitmSocket.triggerConnectErrorIfNeeded (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:189:7)
>     at MitmSocket.onError (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:212:12)
>     at MitmSocket.onMessage (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:165:12)
>     at MitmSocketSession.onMessage (/home/jhast/secret_agent/node_modules/mitm-socket/lib/MitmSocketSession.ts:51:41)
>     at MitmSocketSession.onIpcData (/home/jhast/secret_agent/node_modules/mitm-socket/lib/BaseIpcHandler.ts:154:10)
>     at Socket.emit (node:events:390:28)
>     at addChunk (node:internal/streams/readable:324:12)
>     at readableAddChunk (node:internal/streams/readable:297:9)
>     at Socket.Readable.push (node:internal/streams/readable:234:10)
> ------DIAL----------------------------------------
>     at new MitmSocket (/home/jhast/secret_agent/node_modules/mitm-socket/index.ts:59:22)
>     at MitmRequestAgent.createSocketConnection (/home/jhast/secret_agent/node_modules/mitm/lib/MitmRequestAgent.ts:145:24)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Object.lookupPublicIp [as default] (/home/jhast/secret_agent/plugins/default-browser-emulator/lib/helpers/lookupPublicIp.ts:20:21)
>     at DefaultBrowserEmulator.onHttpAgentInitialized (/home/jhast/secret_agent/plugins/default-browser-emulator/index.ts:121:44)
>     at async Promise.all (index 0)
>     at CorePlugins.onHttpAgentInitialized (/home/jhast/secret_agent/node_modules/core/lib/CorePlugins.ts:141:5)
>     at Session.initialize (/home/jhast/secret_agent/node_modules/core/lib/Session.ts:270:5)
>     at Function.createSessionNow (/home/jhast/secret_agent/node_modules/core/lib/GlobalPool.ts:152:7)
>     at ConnectionToClient.createSession (/home/jhast/secret_agent/node_modules/core/server/ConnectionToClient.ts:212:21)
> ------REMOTE CORE---------------------------------
>     at Function.reviver (/home/jhast/secret_agent/node_modules/commons/TypeSerializer.ts:208:26)
>     at JSON.parse (<anonymous>)
>     at Function.parse (/home/jhast/secret_agent/node_modules/commons/TypeSerializer.ts:24:17)
>     at WebSocket.<anonymous> (/home/jhast/secret_agent/node_modules/client/connections/RemoteConnectionToCore.ts:67:42)
>     at WebSocket.emit (node:events:390:28)
>     at Receiver.receiverOnMessage (/home/jhast/secret_agent/node_modules/ws/lib/websocket.js:1008:20)
>     at Receiver.emit (node:events:390:28)
>     at Receiver.dataMessage (/home/jhast/secret_agent/node_modules/ws/lib/receiver.js:517:14)
>     at /home/jhast/secret_agent/node_modules/ws/lib/receiver.js:468:23
>     at /home/jhast/secret_agent/node_modules/ws/lib/permessage-deflate.js:308:9
> ------CONNECTION----------------------------------
>     at new Resolvable (/home/jhast/secret_agent/node_modules/commons/Resolvable.ts:17:18)
>     at Object.createPromise (/home/jhast/secret_agent/node_modules/commons/utils.ts:68:10)
>     at RemoteConnectionToCore.createPendingResult (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:357:31)
>     at RemoteConnectionToCore.internalSendRequestAndWait (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:263:43)
>     at RemoteConnectionToCore.sendRequest (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:164:17)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at CoreCommandQueue.sendRequest (/home/jhast/secret_agent/node_modules/client/lib/CoreCommandQueue.ts:145:22)
>     at Object.cb (/home/jhast/secret_agent/node_modules/client/lib/CoreCommandQueue.ts:112:16)
>     at Queue.next (/home/jhast/secret_agent/node_modules/commons/Queue.ts:82:19)
> ------CORE COMMANDS-------------------------------
>     at Queue.run (/home/jhast/secret_agent/node_modules/commons/Queue.ts:35:19)
>     at CoreCommandQueue.run (/home/jhast/secret_agent/node_modules/client/lib/CoreCommandQueue.ts:109:8)
>     at RemoteConnectionToCore.createSession (/home/jhast/secret_agent/node_modules/client/connections/ConnectionToCore.ts:205:51)
>     at SessionConnection.getCoreSessionOrReject (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:559:36)
>     at SessionConnection.get activeTab [as activeTab] (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:480:10)
>     at Agent.get activeTab [as activeTab] (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:152:37)
>     at Agent.goto (/home/jhast/secret_agent/node_modules/client/lib/Agent.ts:365:17)
>     at file:///home/jhast/secret_agent/min_test.js:6:17
>     at file:///home/jhast/secret_agent/min_test.js:7:3
>     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
> 
> Node.js v17.3.1
> (.env) jhast@LENOVO-JPR:~/secret_agent$ 2022-01-13T10:27:01.555Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/server/ConnectionToClient] ConnectionToClient.Disconnecting { context: {} }
> 2022-01-13T10:27:01.557Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/core/index] Core.shutdown { context: {} }
> 2022-01-13T10:27:01.557Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/server/ConnectionToClient] ConnectionToClient.Disconnected { context: {} }
> 2022-01-13T10:27:01.558Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/lib/GlobalPool] GlobalPool.Closing { context: {} }
> 2022-01-13T10:27:01.558Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/index] Puppet.Closing { context: {} }
> 2022-01-13T10:27:01.558Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/CertificateGenerator] CertsIpcHandler.Closing { context: {} }
> 2022-01-13T10:27:01.559Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/mitm-socket/lib/CertificateGenerator] CertsIpcHandler.Closed { context: {} }
> 2022-01-13T10:27:01.560Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/mitm/lib/MitmProxy] MitmProxy.Closing { context: {} }
> 2022-01-13T10:27:01.561Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/mitm/lib/MitmProxy] MitmProxy.Closed { closeErrors: [], context: {} }
> 2022-01-13T10:27:01.568Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/lib/BrowserProcess] chrome.ProcessExited { context: {} }
> 2022-01-13T10:27:01.568Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/puppet/index] Puppet.Closed { context: {} }
> 2022-01-13T10:27:01.569Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/lib/GlobalPool] GlobalPool.Closed { context: {} }
> 2022-01-13T10:27:01.569Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/server/index] CoreServer.Closing { waitForOpenConnections: true, context: {} }
> 2022-01-13T10:27:01.569Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/server/index] CoreServer.Closed { context: {} }
> 2022-01-13T10:27:01.569Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/core/start] Exiting Core Process { context: {} }
> 2022-01-13T10:27:01.570Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/commons/ShutdownHandler] ShutdownHandler.onSignal { signal: 'exit', context: {} }
> 2022-01-13T10:27:01.570Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/commons/ShutdownHandler] ShutdownHandler.execute {
>   signal: 'exit',
>   fn: '() => Core.shutdown()',
>   callsite: 'at Function.registerSignals (/home/jhast/secret_agent/node_modules/core/index.ts:180:21)',
>   context: {}
> }
> 2022-01-13T10:27:01.571Z INFO [/home/jhast/secret_agent/node_modules/@secret-agent/core/index] Core.shutdownComplete { context: {} }
> 2022-01-13T10:27:01.571Z STATS [/home/jhast/secret_agent/node_modules/@secret-agent/commons/ShutdownHandler] ShutdownHandler.shutdownComplete { signal: 'exit', exiting: true, context: {} }

**Comment by blakebyrnes** [comment]
I've had another user report this on Discord but never heard a followup. Any chance you'd be willing to privately share your credentials for me to test with? Or create a test account I could use?

**Comment by johnHastings772** [comment]
> I've had another user report this on Discord but never heard a followup. Any chance you'd be willing to privately share your credentials for me to test with? Or create a test account I could use?

Thanks, where should I send you the test credentials?

**Comment by blakebyrnes** [comment]
You can email me at blake at ulixee.org or message me on discord
