### ISSUE TITLE
use chrome folder instead of json

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#428]
Would it be possible to use chrome dir instead of json input for user profiles? 

When json profile gets too big it becomes unusable, loading all cookies and restoring storages takes a lot of time as well.

**Comment by blakebyrnes** [comment]
I've looked into this a couple times. I'm intrigued by it as well. The main thing I don't think works with our current setup is that (from what I understand) headless incognito contexts don't save to disk at the end of a session. (I'm unsure if they'll load up at the beginning either). I think running some experiments to learn what you can get headless incognito contexts to do would be a good starting point.

**Comment by blakebyrnes** [comment]
I've done an experiment that will let us load big profiles far faster (basically we restore session/db in frames on a single page). That should help in the short-term. You can also obviously cut down on the things that don't actually matter in the profile.
