### ISSUE TITLE
Failed to launch chrome 88.0.4324.182

### ISSUE THREAD

**Issue by TonyKun7** [ulixee/secret-agent#431]
```2022-01-22T18:49:07.367Z ERROR [/root/csgo/node_modules/@secret-agent/core/server/ConnectionToClient] ConnectionToClient.HandleRequestError { context: {}, sessionId: undefined, sessionName: undefined } PuppetLaunchError: Failed to launch chrome 88.0.4324.182:
6|csgo  | Please re-install the browser engine:
6|csgo  | -------------------------------------------------
6|csgo  | -------------- NPM INSTALL ----------------------
6|csgo  | -------------------------------------------------
6|csgo  |  npm install @secret-agent/chrome-88-0
6|csgo  | -------------------------------------------------
6|csgo  | Error: Failed to launch chrome 88.0.4324.182:
6|csgo  | Please re-install the browser engine:
6|csgo  | -------------------------------------------------
6|csgo  | -------------- NPM INSTALL ----------------------
6|csgo  | -------------------------------------------------
6|csgo  |  npm install @secret-agent/chrome-88-0
6|csgo  | -------------------------------------------------
6|csgo  |     at BrowserEngine.verifyLaunchable (/root/csgo/node_modules/plugin-utils/lib/BrowserEngine.ts:55:13)
6|csgo  |     at Puppet.start (/root/csgo/node_modules/puppet/index.ts:64:34)
6|csgo  |     at Function.getPuppet (/root/csgo/node_modules/core/lib/GlobalPool.ts:120:19)
6|csgo  |     at Function.createSessionNow (/root/csgo/node_modules/core/lib/GlobalPool.ts:139:33)
6|csgo  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
6|csgo  |     at ConnectionToClient.createSession (/root/csgo/node_modules/core/server/ConnectionToClient.ts:212:21)
6|csgo  |     at ConnectionToClient.executeCommand (/root/csgo/node_modules/core/server/ConnectionToClient.ts:295:16)
6|csgo  |     at ConnectionToClient.handleRequest (/root/csgo/node_modules/core/server/ConnectionToClient.ts:70:14) {
6|csgo  |   isSandboxError: false
6|csgo  | }```

After reinstall still this error

Debian 11

**Comment by TonyKun7** [comment]
> ```
> 6|csgo  | Please re-install the browser engine:
> 6|csgo  | -------------------------------------------------
> 6|csgo  | -------------- NPM INSTALL ----------------------
> 6|csgo  | -------------------------------------------------
> 6|csgo  |  npm install @secret-agent/chrome-88-0
> 6|csgo  | -------------------------------------------------
> 6|csgo  | Error: Failed to launch chrome 88.0.4324.182:
> 6|csgo  | Please re-install the browser engine:
> 6|csgo  | -------------------------------------------------
> 6|csgo  | -------------- NPM INSTALL ----------------------
> 6|csgo  | -------------------------------------------------
> 6|csgo  |  npm install @secret-agent/chrome-88-0
> 6|csgo  | -------------------------------------------------
> 6|csgo  |     at BrowserEngine.verifyLaunchable (/root/csgo/node_modules/plugin-utils/lib/BrowserEngine.ts:55:13)
> 6|csgo  |     at Puppet.start (/root/csgo/node_modules/puppet/index.ts:64:34)
> 6|csgo  |     at Function.getPuppet (/root/csgo/node_modules/core/lib/GlobalPool.ts:120:19)
> 6|csgo  |     at Function.createSessionNow (/root/csgo/node_modules/core/lib/GlobalPool.ts:139:33)
> 6|csgo  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 6|csgo  |     at ConnectionToClient.createSession (/root/csgo/node_modules/core/server/ConnectionToClient.ts:212:21)
> 6|csgo  |     at ConnectionToClient.executeCommand (/root/csgo/node_modules/core/server/ConnectionToClient.ts:295:16)
> 6|csgo  |     at ConnectionToClient.handleRequest (/root/csgo/node_modules/core/server/ConnectionToClient.ts:70:14) {
> 6|csgo  |   isSandboxError: false
> 6|csgo  | }```
> 
> After reinstall still this error
> 
> Debian 11
> ```

I corrected the error

**Comment by blakebyrnes** [comment]
Do you mean you figured this out?

**Comment by Apina-32** [comment]
> > ```
> > 6|csgo  | Please re-install the browser engine:
> > 6|csgo  | -------------------------------------------------
> > 6|csgo  | -------------- NPM INSTALL ----------------------
> > 6|csgo  | -------------------------------------------------
> > 6|csgo  |  npm install @secret-agent/chrome-88-0
> > 6|csgo  | -------------------------------------------------
> > 6|csgo  | Error: Failed to launch chrome 88.0.4324.182:
> > 6|csgo  | Please re-install the browser engine:
> > 6|csgo  | -------------------------------------------------
> > 6|csgo  | -------------- NPM INSTALL ----------------------
> > 6|csgo  | -------------------------------------------------
> > 6|csgo  |  npm install @secret-agent/chrome-88-0
> > 6|csgo  | -------------------------------------------------
> > 6|csgo  |     at BrowserEngine.verifyLaunchable (/root/csgo/node_modules/plugin-utils/lib/BrowserEngine.ts:55:13)
> > 6|csgo  |     at Puppet.start (/root/csgo/node_modules/puppet/index.ts:64:34)
> > 6|csgo  |     at Function.getPuppet (/root/csgo/node_modules/core/lib/GlobalPool.ts:120:19)
> > 6|csgo  |     at Function.createSessionNow (/root/csgo/node_modules/core/lib/GlobalPool.ts:139:33)
> > 6|csgo  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 6|csgo  |     at ConnectionToClient.createSession (/root/csgo/node_modules/core/server/ConnectionToClient.ts:212:21)
> > 6|csgo  |     at ConnectionToClient.executeCommand (/root/csgo/node_modules/core/server/ConnectionToClient.ts:295:16)
> > 6|csgo  |     at ConnectionToClient.handleRequest (/root/csgo/node_modules/core/server/ConnectionToClient.ts:70:14) {
> > 6|csgo  |   isSandboxError: false
> > 6|csgo  | }```
> > 
> > After reinstall still this error
> > 
> > Debian 11
> > ```
> 
> I corrected the error

Mind sharing how you fixed the issue, I'm facing a similar one now.

**Comment by blakebyrnes** [comment]
@Apina-32 Sorry, I realized you didn't get a response. You might need to trigger linux to install dependencies: `npx install-browser-deps`. This will run a .deb file with all the Chrome dependencies

**Comment by TonyKun7** [comment]
.
