### ISSUE TITLE
how to set proxy url  and get raw html content

### ISSUE THREAD

**Issue by icesmartjuan** [ulixee/secret-agent#448]
Thanks for sharing this great project. 
It seems we can set proxy or new user-agent via `Agent `constructor or  `agent.configure()`  from the [full API docs](https://secretagent.dev/docs)

```
process.env.DEBUG = true;
const { Agent } = require('secret-agent');

const proxyUrl = http://xxx:80
const agent = await new Agent({
    upstreamProxyUrl:proxyUrl
  });

OR:
await agent.configure({ upstreamProxyUrl: proxyUrl }); 
```
but it failed with errors: 
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://localhost:57654)
    at RemoteConnectionToCore.onRespo
...

await agent.configure({ upstreamProxyUrl: proxyUrl });
              ^

TypeError: Cannot read properties of undefined (reading 'configure')

```
Any insight on setting proxyUrl?  Do we need to set different user-agent for our proxy? and how can we get rawl html content from the agent?  thank you.

**Comment by blakebyrnes** [comment]
Thanks for logging @icesmartjuan. Can you share your exact code snippet?

**Comment by icesmartjuan** [comment]
@blakebyrnes sure, here it is:
```// const proxyUrl = 'http://xxx:80'
process.env.DEBUG = true;
const { agent } = require('secret-agent');
//const { Agent } = require('secret-agent');

(async () => {
  // const agent = await new Agent({
  //   upstreamProxyUrl:proxyUrl
  // });

 // await agent.configure({ upstreamProxyUrl: proxyUrl });
  await agent.goto('https://www.example.com/');

 // const doc = await agent.document
  const title =  agent.document.title;
  const intro =  agent.document.querySelector('html').textContent;

  console.log(title)
  console.log(agent.document)
  await agent.close();
})();

**Comment by blakebyrnes** [comment]
Ah, I think I see. You are exporting lowercase agent from secret agent as a named export, but it needs to be default `const agent = require('secret-agent')`

The capitalized version of agent is correctly exported.

Hope that helps!

**Comment by icesmartjuan** [comment]
Thank you @blakebyrnes , perfect , it works with `const agent = require('secret-agent'),..await agent.configure({ upstreamProxyUrl: proxyUrl });`.  

And do we need to set different user-agent for scraping a mount or Urls(what kind of user-agents are recommended to avoid being blocked   )? and how can we get raw html content(with all html tags, just like the page view: source view-source:https://secretagent.dev/docs/) from the agent? thank you.

**Comment by blakebyrnes** [comment]
Your user agent will rotate by default. You are likely ok with the built-in, but if you run into issues, you can supply a user agent or targeted Chrome version/OS using the userAgent configuration for a new Agent.

To get outer html, just use regular dom calls. `await document.body.outerHTML`
