### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by 0jsk** [ulixee/secret-agent#450]
When trying to connect to any host using secure protocols, the certificate verification fails.
I get this behavior for any configuration I use, when using example from documentation too.

Is there a possibility to fix this?

![image](https://user-images.githubusercontent.com/90405410/159174731-a5b8d39f-dc72-4123-a9d3-802b340cd258.png)

**Comment by blakebyrnes** [comment]
I don't think it's possible to remove it - Secret Agent runs through a man-in-the-middle proxy that is faking out certificates to sites. It should not have any security impact to you as long as you maintain control of your machines 😀 Is there any reason you were hoping to see this fixed?
