### ISSUE TITLE
EDIT: waitForFileChooser does not work when using userProfile with 2+ sessionStorage domains

### ISSUE THREAD

**Issue by Baker68** [ulixee/secret-agent#452]
In order to reproduce you need to :

- start a new instance of a secret-agent via `new Agent({...options})`
- export and save the profile on disk
```
  const profile = await agent.exportUserProfile();
  fs.writeFileSync('profile.json', JSON.stringify(profile));
```
- close the current secret-agent instance
- start a new instance of a secret-agent via 
`new Agent({...options, userProfile: JSON.parse(fs.readFileSync('profile.json'))})`

`waitForFileChooser` won't work when loading a userProfile.

If there are any workarounds, could you please post it ? I know it takes time to fix issues. Thanks in advance.

**Comment by blakebyrnes** [comment]
Thanks for logging @Baker68. Do you have a full code snippet you could share? And/or a session database?

**Comment by Baker68** [comment]
@blakebyrnes this is the full log
[debug.txt](https://github.com/ulixee/secret-agent/files/8351099/debug.txt)
 the code : 
```javascript
  const chosenFiles = readFiles(files);
  const photoButton = agent.document.querySelector(
    selectors.post_attach_file_button
  );
  await agent.interact({ move: photoButton }); // ads the <input type="file"> to DOM
  await agent.click(photoButton);
  const fileChooser = await agent.waitForFileChooser();

  await fileChooser.chooseFiles(...chosenFiles);
```

**Comment by blakebyrnes** [comment]
Would you be willing to send me a session database privately? I don't see anything that stands out in these logs. You can reach me on discord or blake at ulixee.org

**Comment by Baker68** [comment]
@blakebyrnes sure, I've joined the discord server

**Comment by blakebyrnes** [comment]
Issue appears to be related to loading a userProfile with more than 1 sessionStorage. Creating multiple session "restoration" tabs seems to break the events for FileInputs. 

Needs investigation into what is causing events to not fire when > 1 domain.

```js
const agent = await handler.createAgent({
      humanEmulatorId: 'basic',
      userProfile: {
        cookies: [],
        storage: {
          'https://domain1.com': {
            indexedDB: [],
            localStorage: [],
            sessionStorage: [['2', '1']],
          },
          'https://domain2.com': {
            indexedDB: [],
            localStorage: [],
            sessionStorage: [['1', '2']],
          },
        },
      },
    });


    const file1 = await Fs.promises.readFile(`${__dirname}/filechooser.test.js`);
    const file2 = await Fs.promises.readFile(`${__dirname}/filechooser.test.js.map`);

    await agent.goto(`${koaServer.baseUrl}/get-upload-multi`);
    await agent.waitForPaintingStable();
    const input = await agent.document.querySelector('#sourcefiles');
    await agent.click(input);
    const chooser = await agent.waitForFileChooser(); <-- HANGS
```
