### ISSUE TITLE
Chrome version updates?

### ISSUE THREAD

**Issue by luka-dev** [ulixee/secret-agent#461]
Hi, played around with SA, and founded thats it's using outdated chrome version due to [this](https://github.com/ulixee/secret-agent/blob/main/plugins/default-browser-emulator/package.json#L7) dependency.
I watched [`default-browser-emulator`](https://github.com/ulixee/secret-agent/tree/main/plugins/default-browser-emulator) to find latest version, but discovered thats version is [hardcoded](https://github.com/ulixee/secret-agent/blob/main/plugins/default-browser-emulator/index.ts#L45), and data-set of `as-chrome-*` is a full year behind actual [`chrome-versions`](https://github.com/ulixee/chrome-versions/releases).  

Is it planned to updated? 
Or maybe you have some scripts or something that can help catch and generate all this stuff for missed versions to pull it here?

**Comment by blakebyrnes** [comment]
Hi @luka-dev, yes, SecretAgent got way behind. We've updated in Hero, and plan on making it more regular there. Should we be cutting over to the new version in a few weeks. We're also planning to open up more that lets you update the emulators - there are some parts of it that can't be automated all the way yet. Maybe someone from the community will help out with that. The Hero updates are here (https://github.com/ulixee/hero).

**Comment by luka-dev** [comment]
Thanks for fast answer! Will switch to `hero`.
Propose - maybe make a notice in readme that's project maintaining but not updating?

**Comment by blakebyrnes** [comment]
We are in the process of switching! Will definitely do that. Hero isn't on npm yet though, so you will have to use the monorepo for a few weeks. We're putting docs/website at the moment to start switching over!

**Comment by luka-dev** [comment]
Sounds great! Thank you for your time!
