### ISSUE TITLE
no webgl support in headed mode, Windows VPS.

### ISSUE THREAD

**Issue by fernandobragasilva** [ulixee/secret-agent#464]
no webgl support in headed mode, Windows VPS.

in headless mode it works normally

Url Test: https://get.webgl.org/
headed mode result:

_Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.
For more help, please click this link._

**Comment by blakebyrnes** [comment]
Thanks for reporting @fernandobragasilva! There's a flag we have turned on to get headless to use webgl ('--use-gl=any'). You might see if removing that or changing to a different value makes windows headed work for you. You can create a copy of the `plugins/default-browser-emulator` folder and change `lib/helpers/configureBrowserLauncherArgs` to remove the variable (or make it conditional on being headless)

**Comment by fernandobragasilva** [comment]
ok, thanks for the quick reply, congratulations on the project.
Can me modifying this value impact the detection of my bot?
does this modification make me lose the secrete-agent concept?
And do you have any predictions to make Hero available on NPM?

**Comment by blakebyrnes** [comment]
I don't think it would impact your detection. We're masking the actual engine. I think we'll have an alpha of Hero up this week.

**Comment by fernandobragasilva** [comment]
OK thank you
