### ISSUE TITLE
Allow executing javascript / setting document properties

### ISSUE THREAD

**Issue by zedd3v** [ulixee/secret-agent#57]
I am trying to edit some cookies but cannot find a method to execute code. And the document is read-only.
Let me know if I missed something or if this is not yet released

**Comment by calebjclark** [comment]
We currently allow reading cookies but not writing/editing them, however it wouldn't be too difficult to add.

What is your use case for editing cookies?

We hadn't imagined a viable scraping use-case for this, but perhaps we're overlooking something. Let us know... we're open to making this a high priority feature.

**Comment by zedd3v** [comment]
@calebjclark 
Some websites have cookies which are added by doing multiple actions and I want to skip those actions and edit the cookie myself to save memory and time

**Comment by blakebyrnes** [comment]
@zedd3v 
Have you seen the UserProfiles function? https://secretagent.dev/docs/advanced/user-profile

We've imagined use cases where you would accumulate cookies as above, and then save off a profile to a file or database.
`const profile = await browser.user.exportProfile();`

Then when you're ready to resume, you'd create a new Browser with:
`
const browserWithProfile = await SecretAgent.createBrowser({
  userProfile: profile,
});
`

By setting up cookies, dom storage, etc this way, we believe it is significantly harder to detect. If you don't want to "save" the state of your session, you could look at the format of the profile and just recreate a profile with your cookies.

**Comment by zedd3v** [comment]
@blakebyrnes 
I saw that function but that's not what I'm looking for.

The cookies need to be edited programmatically after the website sets them

**Comment by blakebyrnes** [comment]
@zedd3v 
Thanks for clarifying. Would you just want to be able to add "set" to the document.cookie api? Or are you "waiting" for the cookies to be set, and want to be able to intercept and change them before they're saved?

**Comment by zedd3v** [comment]
@blakebyrnes I would just like a set (replace) cookie API.
But the most preferable solution would be to add javascript execution which most of the users (including me) will probably need

**Comment by blakebyrnes** [comment]
We've been hesitant to add the ability to execute arbitrary js code because it opens up things that are hard for us to properly capture in Replay (which is our browser session recording and replay app), and it reintroduces the environment context confusion that puppeteer and playwright have. 

Most importantly, it also doesn't emulate what a real user would do, which is our current thinking for how make secret agent the most effective. 

Do you have any other examples off the top of your head for things you need (or have needed) for executing raw JavaScript code?

**Comment by zedd3v** [comment]
Do not have an example currently but I'm sure something will pop up sooner or later.

**Comment by calebjclark** [comment]
At the very least, it seems we should implement the DOM's set cookie functionality.
