### ISSUE TITLE
Provide args to Chrome

### ISSUE THREAD

**Issue by trnj** [ulixee/secret-agent#58]
Hello,

Thank you for your excellent work. 

Is it possible to provide args like  --no-sandbox to the browser?

**Comment by blakebyrnes** [comment]
Hi @trnj,

Thanks for saying that! This is something we definitely need to do. I think we'll probably add an option to initialize a browser emulator with extra args. Or maybe we just need an ability to add --no-sandbox globally. Is that the only option you foresee needing?

**Comment by trnj** [comment]
Unable to lauch it on windows without --no-sandbox.

Currently, I use the following in Puppeteer.            
   
```
     "--disable-gpu",
                "--disable-dev-shm-usage",
                "--no-sandbox",

              '--window-size=1600,900',
               '--start-maximized',

                '--disable-web-security', 
              '--silent-debugger-extension-api',  

                '--allow-running-insecure-content',
                '--disable-strict-mixed-content-checking',
                '--ignore-certificate-errors',

```

Also, is it possible to take screenshots? Sometimes it is useful. Also, I need it for OCR. 

And I would like to bypass multiple bot test like https://pixelscan.net/   https://bot.sannysoft.com 

There are some problems like, when I change IP or proxy, I need to set correct timezone for the new IP in order to bypass bot tests. Would be great to have it out of the box.

```
 const fetch = require('cross-fetch');
let info = await (await fetch('https://ipinfo.io/json')).json();
await page.emulateTimezone(info.timezone);

```

Also, I set webgl vendors. 

Another important point is the correct Screen resolution and Available screen size (it should be smaller).

**Comment by calebjclark** [comment]
Excellent feedback, @trnj. Those features are definitely needed.

**Comment by trnj** [comment]
Another usefull feature is mouse moves, key up, down, clicks.  Puppeeteer has a problem with clicks. If element is hovered, or replaces by React frequently, then click does not work.  Some bot protection services collect clicks, mouse moves.

**Comment by calebjclark** [comment]
@trnj, we have mouse move capabilities: https://secretagent.dev/docs/basic-interfaces/interactions

**Comment by trnj** [comment]
> @trnj, we have mouse move capabilities: https://secretagent.dev/docs/basic-interfaces/interactions

Thank you. Is it possible to click an element if it is hovered by another element?

**Comment by blakebyrnes** [comment]
@trnj Do you have a page or example with the react hover? Would love to add a unit test. For not being able to launch on Windows, what version are you using? Our CI is passing on Windows Server, and I've been able to launch on a Windows 10 VM fine.

**Comment by blakebyrnes** [comment]
Are you running your own custom chrome instance as well? Or the one packaged with the secret-agent chrome-83 emulator plugin?

**Comment by trnj** [comment]
For some reason, I get the following. Why it lunches the puppeteer instead? 

```
ERROR UnhandledClientError {
   clientError: Error: Failed to launch the browser process! spawn C:\Users\Home\AppData\Local\chromium-756035\win64-756035\chrome-win\chrome.exe ENOENT


   TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

       at onClose (C:\Users\Home2017\Dropbox\_current_projects\jobot\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
       at ChildProcess.<anonymous> (C:\Users\Home2017\Dropbox\_current_projects\jobot\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserRunner.js:185:85)

```

**Comment by trnj** [comment]
Also, tried and got blocked immediately.

For example,
https://www.expertflyer.com - distil, blocked
https://www.leboncoin.fr/ - another bot protection, but unable to open the website.

**Comment by calebjclark** [comment]
@trnj, we'll look into both of these issues and get back to you.
