### ISSUE TITLE
Create a consistent data directory for .sessions and .mitm-ca

### ISSUE THREAD

**Issue by calebjclark** [ulixee/secret-agent#6]
At the moment SA creates two directories (.sessions and .mitm-ca) in your CWD (current working directory) every time a script is run. This creates a confusing clutter of directories.

Both directories need to be organized under a single `.secret-agent` directory. The big question is, where should this new directory go?

A few options:

- Keep it in the *CWD*. Seems like a bad idea as the same script could have multiple .secret-agent directories depending on where it was run each time.

- Put it in the *scriptEntrypoint* directory. This is better than the previous option, but still seems a bit overkill (multiple .secret-agent directories if you have scripts in multiple directories). However, the bigger challenge is the data dir is created inside Core, which means it doesn't have access to scriptEntrypoint if working with remote client.

- Put it in the "*project root*". This would be ideal, except that determining the "project root" is tricky. It seems the project root can change substantially depending on how the script was launched, which in some circumstances, could make it frustrating to find the data directory. See https://stackoverflow.com/questions/10265798/determine-project-root-from-a-running-node-js-application

- Put it in */tmp*. The pro is that it's consistently in the same place every time. The con is that data from ALL scripts and projects is going to be jumbled together into the same directory.

Thoughts?

**Comment by blakebyrnes** [comment]
I think /tmp makes the most sense. If we put in the project directory, you can see the files are there, but they're of limited utility unless you know what to actually do with them. Tmp means "temporary files". If a user wants to persist them, they'll choose the appropriate location to store them.

If we really want to separate the files inside /tmp, we could separate specific sessions by the scriptEntrypoint as a prefix folder

**Comment by calebjclark** [comment]
I'm not sure we can "separate specific sessions by the scriptEntrypoint", at least not if Core is running through a remote connection. There could be multiple scriptEntrypoints with the same value.

**Comment by blakebyrnes** [comment]
We could introduce the idea of a config file that goes into a project directory. It would give us something to go locate...

**Comment by blakebyrnes** [comment]
One challenge with the tmp directory is that we could end up needing multiple processes accessing the sessions database at once. Sqlite3 is not multi-threaded by default, I don't believe.
