### ISSUE TITLE
AwaitedDom Iterators should be accessible by index

### ISSUE THREAD

**Issue by blakebyrnes** [ulixee/secret-agent#64]
When you run a document.querySelectorAll, you should be able to get an index out of the resultset:

``
const results = await document.querySelectorAll('a');
const href = await results[0].getAttribute('href')
``

**Comment by calebjclark** [comment]
It seems you should be able to use an index regardless of whether you await querySelectorAll:

```
const href = await document.querySelectorAll('a')[0].getAttribute('href');
```
This is how the rest of the AwaitedDOM works.
