### ISSUE TITLE
How to open a new tab?

### ISSUE THREAD

**Issue by petrpatek** [ulixee/secret-agent#66]
I found a `browser.closeTab` function. Is there a way to open a new tab manually? How does secret-agent manage the opening of new tabs?

**Comment by blakebyrnes** [comment]
Hi @petrpatek

We don't yet have the ability to explicitly spawn a new tab. The tabs feature comes in handy when clicking a link goes to target="_blank" or the page does a `window.open` in the javascript. If you really want new tabs from links, you can also use the MetaLeft key to open links in a new window (that's mac, use equivalent for other OSes).

SecretAgent treats each "Browser" as a unique sandbox of cookies, storage, etc. It's very lightweight - akin to an Incognito Window in Chrome. When you run SecretAgent.createBrowser, it will automatically establish a tab for you. You just run "goto" to send it wherever you want it to go. 

Hopefully that answers your question.

If you need to wait for newly "spawned" tabs, there's a `browser.waitForNewTab` method.

**Comment by blakebyrnes** [comment]
@petrpatek following up. Is there anything you would like fixed/improved/changed here? If not, going to close this one out.

**Comment by petrpatek** [comment]
Hi @blakebyrnes,

Thank you very much for your answer. 

I think I get it now. I am used to the puppeteer/playwright logic, so when I want to run some tasks in parallel and don't really care about the cookies or the fingerprint. The tasks are executed in multiple pages (tabs or windows). In secret-agent, I am supposed to spawn multiple browsers with the default tab, am I right? 

Thank you again!

**Comment by blakebyrnes** [comment]
@petrpatek 

Yep, that's what you'd do for generating multiple tasks. @calebjclark and I talked about this a good bit after your question. We're considering renaming "createBrowser" to something a little lighter weight sounding.

**Comment by calebjclark** [comment]
@petrpatek to add a little more color to what @blakebyrnes just mentioned...

We're considering renaming createBrowser to something like createSession, because createBrowser isn't really accurate. You're not spinning up an entirely new browser... just an isolated browser session.

**Comment by petrpatek** [comment]
@blakebyrnes  @calebjclark Thank you for the clarification. To me `createSession` sounds less like I should worry about the performace.

**Comment by blakebyrnes** [comment]
@petrpatek Thanks for the feedback!
